import random
from typing import NamedTuple, Optional, List
from BaseClasses import Item, Region, ItemClassification


class LK2Item(Item):
    name: str
    id: int

    def __init__(self, name: str, classification: ItemClassification, item_id, player: int):
        super(LK2Item, self).__init__(name, classification, item_id, player=player)

        self.name = name
        self.id = item_id



lost_kingdoms_2_items = {}

lost_kingdoms_2_cards = {
    'Skeleton': {'DolphinAddress': '802589a6', 'element': 'Earth', 'hexCode': '01', 'isKeyCard': 0, 'isShopCard': 1, 'number': 1, 'orderInMemory': 0, 'rarity': 1, 'type': 'Independent', 'hasCombo': 1, 'price': 30, 'mana_cost': 1, 'item_id': 1},
    'Ghost Armor': {'DolphinAddress': '802589ba', 'element': 'Wood', 'hexCode': '02', 'isKeyCard': 0, 'isShopCard': 1, 'number': 2, 'orderInMemory': 1, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 720, 'mana_cost': 4, 'item_id': 2},
    'Red Dragon': {'DolphinAddress': '802589ce', 'element': 'Fire', 'hexCode': '03', 'isKeyCard': 0, 'isShopCard': 1, 'number': 3, 'orderInMemory': 2, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 2700, 'mana_cost': 10, 'item_id': 3},
    'Lizardman': {'DolphinAddress': '802589f6', 'element': 'Earth', 'hexCode': '05', 'isKeyCard': 0, 'isShopCard': 1, 'number': 4, 'orderInMemory': 4, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 1, 'price': 50, 'mana_cost': 2, 'item_id': 4},
    'Mandragora': {'DolphinAddress': '80258a5a', 'element': 'Wood', 'hexCode': '0A', 'isKeyCard': 1, 'isShopCard': 1, 'number': 5, 'orderInMemory': 9, 'rarity': 1, 'type': 'Helper', 'hasCombo': 1, 'price': 45, 'mana_cost': 1, 'item_id': 5},
    'Elephant': {'DolphinAddress': '80259216', 'element': 'Earth', 'hexCode': '6d', 'isKeyCard': 0, 'isShopCard': 1, 'number': 6, 'orderInMemory': 108, 'rarity': 1, 'type': 'Summons', 'hasCombo': 1, 'price': 90, 'mana_cost': 4, 'item_id': 6},
    'Red Lizard': {'DolphinAddress': '80258a6e', 'element': 'Fire', 'hexCode': '0B', 'isKeyCard': 0, 'isShopCard': 1, 'number': 7, 'orderInMemory': 10, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 1, 'price': 100, 'mana_cost': 3, 'item_id': 7},
    'Unicorn': {'DolphinAddress': '80258a82', 'element': 'Wood', 'hexCode': '0C', 'isKeyCard': 0, 'isShopCard': 1, 'number': 8, 'orderInMemory': 11, 'rarity': 7, 'type': 'Transform', 'hasCombo': 0, 'price': 5400, 'mana_cost': 4, 'item_id': 8},
    'Hobgoblin': {'DolphinAddress': '80258a96', 'element': 'Fire', 'hexCode': '0D', 'isKeyCard': 0, 'isShopCard': 1, 'number': 9, 'orderInMemory': 12, 'rarity': 1, 'type': 'Independent', 'hasCombo': 1, 'price': 30, 'mana_cost': 1, 'item_id': 9},
    'Sand Golem': {'DolphinAddress': '80258abe', 'element': 'Earth', 'hexCode': '0F', 'isKeyCard': 0, 'isShopCard': 1, 'number': 10, 'orderInMemory': 14, 'rarity': 2, 'type': 'Helper', 'hasCombo': 0, 'price': 300, 'mana_cost': 7, 'item_id': 10},
    'Jack-O-Lantern': {'DolphinAddress': '80258ad2', 'element': 'Fire', 'hexCode': '10', 'isKeyCard': 0, 'isShopCard': 0, 'number': 11, 'orderInMemory': 15, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 11, 'item_id': 11},
    'Man Trap': {'DolphinAddress': '80258afa', 'element': 'Wood', 'hexCode': '12', 'isKeyCard': 0, 'isShopCard': 1, 'number': 12, 'orderInMemory': 17, 'rarity': 1, 'type': 'Independent', 'hasCombo': 0, 'price': 15, 'mana_cost': 1, 'item_id': 12},
    'Sand Worm': {'DolphinAddress': '80258b22', 'element': 'Earth', 'hexCode': '14', 'isKeyCard': 0, 'isShopCard': 1, 'number': 13, 'orderInMemory': 19, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 600, 'mana_cost': 7, 'item_id': 13},
    'Mummy': {'DolphinAddress': '80258b36', 'element': 'Earth', 'hexCode': '15', 'isKeyCard': 0, 'isShopCard': 1, 'number': 14, 'orderInMemory': 20, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 1, 'price': 225, 'mana_cost': 1, 'item_id': 14},
    'Cockatrice': {'DolphinAddress': '80258b4a', 'element': 'Wood', 'hexCode': '16', 'isKeyCard': 0, 'isShopCard': 1, 'number': 15, 'orderInMemory': 21, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 750, 'mana_cost': 4, 'item_id': 15},
    'Sasquatch': {'DolphinAddress': '80258b5e', 'element': 'Water', 'hexCode': '17', 'isKeyCard': 0, 'isShopCard': 1, 'number': 16, 'orderInMemory': 22, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 2200, 'mana_cost': 6, 'item_id': 16},
    'Wraith': {'DolphinAddress': '80258b72', 'element': 'Water', 'hexCode': '18', 'isKeyCard': 0, 'isShopCard': 1, 'number': 17, 'orderInMemory': 23, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 1, 'price': 300, 'mana_cost': 4, 'item_id': 17},
    'Orc': {'DolphinAddress': '80258b86', 'element': 'Fire', 'hexCode': '19', 'isKeyCard': 0, 'isShopCard': 1, 'number': 18, 'orderInMemory': 24, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 1, 'price': 135, 'mana_cost': 3, 'item_id': 18},
    'Fairy': {'DolphinAddress': '80258bae', 'element': 'Water', 'hexCode': '1B', 'isKeyCard': 0, 'isShopCard': 1, 'number': 19, 'orderInMemory': 26, 'rarity': 1, 'type': 'Helper', 'hasCombo': 1, 'price': 240, 'mana_cost': 3, 'item_id': 19},
    'Vampire Bush': {'DolphinAddress': '80259202', 'element': 'Fire', 'hexCode': '6c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 20, 'orderInMemory': 107, 'rarity': 4, 'type': 'Helper', 'hasCombo': 1, 'price': 690, 'mana_cost': 3, 'item_id': 20},
    'Catoblepas': {'DolphinAddress': '80258bfe', 'element': 'Earth', 'hexCode': '1F', 'isKeyCard': 0, 'isShopCard': 1, 'number': 21, 'orderInMemory': 30, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 900, 'mana_cost': 5, 'item_id': 21},
    'Kraken': {'DolphinAddress': '80258c12', 'element': 'Water', 'hexCode': '20', 'isKeyCard': 0, 'isShopCard': 1, 'number': 22, 'orderInMemory': 31, 'rarity': 7, 'type': 'Summons', 'hasCombo': 0, 'price': 3300, 'mana_cost': 6, 'item_id': 22},
    'Water Reaper': {'DolphinAddress': '80258c26', 'element': 'Water', 'hexCode': '21', 'isKeyCard': 0, 'isShopCard': 1, 'number': 23, 'orderInMemory': 32, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 0, 'price': 45, 'mana_cost': 1, 'item_id': 23},
    'Fenril': {'DolphinAddress': '80258c3a', 'element': 'Wood', 'hexCode': '22', 'isKeyCard': 0, 'isShopCard': 1, 'number': 24, 'orderInMemory': 33, 'rarity': 6, 'type': 'Summons', 'hasCombo': 1, 'price': 3480, 'mana_cost': 9, 'item_id': 24},
    'Lich': {'DolphinAddress': '80258c4e', 'element': 'Earth', 'hexCode': '23', 'isKeyCard': 0, 'isShopCard': 1, 'number': 25, 'orderInMemory': 34, 'rarity': 6, 'type': 'Weapon', 'hasCombo': 1, 'price': 2100, 'mana_cost': 5, 'item_id': 25},
    'Carbuncle': {'DolphinAddress': '80258c62', 'element': 'Earth', 'hexCode': '24', 'isKeyCard': 0, 'isShopCard': 1, 'number': 26, 'orderInMemory': 35, 'rarity': 3, 'type': 'Helper', 'hasCombo': 1, 'price': 450, 'mana_cost': 4, 'item_id': 26},
    'Flayer Spawn': {'DolphinAddress': '80258c8a', 'element': 'Fire', 'hexCode': '26', 'isKeyCard': 0, 'isShopCard': 1, 'number': 27, 'orderInMemory': 37, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 0, 'price': 100, 'mana_cost': 1, 'item_id': 27},
    'Golden Goose': {'DolphinAddress': '802589e2', 'element': 'Neutral', 'hexCode': '04', 'isKeyCard': 0, 'isShopCard': 1, 'number': 28, 'orderInMemory': 3, 'rarity': 6, 'type': 'Helper', 'hasCombo': 0, 'price': 4500, 'mana_cost': 4, 'item_id': 28},
    'Zombie Dragon': {'DolphinAddress': '80258cb2', 'element': 'Earth', 'hexCode': '28', 'isKeyCard': 0, 'isShopCard': 1, 'number': 29, 'orderInMemory': 39, 'rarity': 7, 'type': 'Summons', 'hasCombo': 0, 'price': 2400, 'mana_cost': 8, 'item_id': 29},
    'Fire Golem': {'DolphinAddress': '80258cc6', 'element': 'Fire', 'hexCode': '29', 'isKeyCard': 0, 'isShopCard': 1, 'number': 30, 'orderInMemory': 40, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 570, 'mana_cost': 5, 'item_id': 30},
    'Running Bird': {'DolphinAddress': '80258cda', 'element': 'Earth', 'hexCode': '2A', 'isKeyCard': 0, 'isShopCard': 1, 'number': 31, 'orderInMemory': 41, 'rarity': 3, 'type': 'Helper', 'hasCombo': 1, 'price': 240, 'mana_cost': 5, 'item_id': 31},
    'Giant Crab': {'DolphinAddress': '80258cee', 'element': 'Water', 'hexCode': '2b', 'isKeyCard': 0, 'isShopCard': 1, 'number': 32, 'orderInMemory': 42, 'rarity': 1, 'type': 'Summons', 'hasCombo': 0, 'price': 120, 'mana_cost': 2, 'item_id': 32},
    'Banshee': {'DolphinAddress': '80258d02', 'element': 'Wood', 'hexCode': '2c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 33, 'orderInMemory': 43, 'rarity': 5, 'type': 'Weapon', 'hasCombo': 0, 'price': 300, 'mana_cost': 2, 'item_id': 33},
    'Land Shark': {'DolphinAddress': '80258d16', 'element': 'Water', 'hexCode': '2D', 'isKeyCard': 0, 'isShopCard': 1, 'number': 34, 'orderInMemory': 44, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 270, 'mana_cost': 6, 'item_id': 34},
    'Berserker': {'DolphinAddress': '80258d2a', 'element': 'Fire', 'hexCode': '2e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 35, 'orderInMemory': 45, 'rarity': 2, 'type': 'Independent', 'hasCombo': 0, 'price': 540, 'mana_cost': 5, 'item_id': 35},
    'Flying Ray': {'DolphinAddress': '80258d3e', 'element': 'Water', 'hexCode': '2f', 'isKeyCard': 0, 'isShopCard': 1, 'number': 36, 'orderInMemory': 46, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 1, 'price': 30, 'mana_cost': 1, 'item_id': 36},
    'Demon Hound': {'DolphinAddress': '80258d52', 'element': 'Wood', 'hexCode': '30', 'isKeyCard': 0, 'isShopCard': 1, 'number': 37, 'orderInMemory': 47, 'rarity': 2, 'type': 'Independent', 'hasCombo': 0, 'price': 360, 'mana_cost': 6, 'item_id': 37},
    'Behemoth': {'DolphinAddress': '80258d66', 'element': 'Earth', 'hexCode': '31', 'isKeyCard': 0, 'isShopCard': 1, 'number': 38, 'orderInMemory': 48, 'rarity': 6, 'type': 'Summons', 'hasCombo': 1, 'price': 3150, 'mana_cost': 9, 'item_id': 38},
    'Basilisk': {'DolphinAddress': '802591b2', 'element': 'Water', 'hexCode': '68', 'isKeyCard': 0, 'isShopCard': 1, 'number': 39, 'orderInMemory': 103, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 1, 'price': 105, 'mana_cost': 3, 'item_id': 39},
    'Mole Monster': {'DolphinAddress': '80258d7a', 'element': 'Neutral', 'hexCode': '32', 'isKeyCard': 0, 'isShopCard': 1, 'number': 40, 'orderInMemory': 49, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 999, 'mana_cost': 6, 'item_id': 40},
    'Maelstrom': {'DolphinAddress': '80258d8e', 'element': 'Water', 'hexCode': '33', 'isKeyCard': 0, 'isShopCard': 1, 'number': 41, 'orderInMemory': 50, 'rarity': 2, 'type': 'Helper', 'hasCombo': 0, 'price': 60, 'mana_cost': 1, 'item_id': 41},
    'Lycanthrope': {'DolphinAddress': '80258db6', 'element': 'Wood', 'hexCode': '35', 'isKeyCard': 0, 'isShopCard': 1, 'number': 42, 'orderInMemory': 52, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 0, 'price': 375, 'mana_cost': 6, 'item_id': 42},
    'Sand Beetle': {'DolphinAddress': '80258dca', 'element': 'Earth', 'hexCode': '36', 'isKeyCard': 0, 'isShopCard': 1, 'number': 43, 'orderInMemory': 53, 'rarity': 2, 'type': 'Independent', 'hasCombo': 0, 'price': 420, 'mana_cost': 5, 'item_id': 43},
    'Necromancer': {'DolphinAddress': '80258dde', 'element': 'Neutral', 'hexCode': '37', 'isKeyCard': 0, 'isShopCard': 1, 'number': 44, 'orderInMemory': 54, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 900, 'mana_cost': 6, 'item_id': 44},
    'Great Turtle': {'DolphinAddress': '80258df2', 'element': 'Earth', 'hexCode': '38', 'isKeyCard': 0, 'isShopCard': 0, 'number': 45, 'orderInMemory': 55, 'rarity': 8, 'type': 'Independent', 'hasCombo': 1, 'price': 0, 'mana_cost': 20, 'item_id': 45},
    'Gold Butterfly': {'DolphinAddress': '80258e06', 'element': 'Wood', 'hexCode': '39', 'isKeyCard': 0, 'isShopCard': 1, 'number': 46, 'orderInMemory': 56, 'rarity': 3, 'type': 'Helper', 'hasCombo': 1, 'price': 180, 'mana_cost': 5, 'item_id': 46},
    'Ghoul': {'DolphinAddress': '80258e1a', 'element': 'Wood', 'hexCode': '3a', 'isKeyCard': 0, 'isShopCard': 1, 'number': 47, 'orderInMemory': 57, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 0, 'price': 75, 'mana_cost': 1, 'item_id': 47},
    'Treant': {'DolphinAddress': '80258e2e', 'element': 'Wood', 'hexCode': '3b', 'isKeyCard': 0, 'isShopCard': 1, 'number': 48, 'orderInMemory': 58, 'rarity': 3, 'type': 'Helper', 'hasCombo': 1, 'price': 240, 'mana_cost': 5, 'item_id': 48},
    'Sea Monk': {'DolphinAddress': '80258e56', 'element': 'Water', 'hexCode': '3d', 'isKeyCard': 0, 'isShopCard': 1, 'number': 49, 'orderInMemory': 60, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 1440, 'mana_cost': 10, 'item_id': 49},
    'King Mandragora': {'DolphinAddress': '8025919e', 'element': 'Wood', 'hexCode': '67', 'isKeyCard': 0, 'isShopCard': 1, 'number': 50, 'orderInMemory': 102, 'rarity': 7, 'type': 'Helper', 'hasCombo': 1, 'price': 2100, 'mana_cost': 4, 'item_id': 50},
    'Larval Fly': {'DolphinAddress': '802591c6', 'element': 'Water', 'hexCode': '69', 'isKeyCard': 0, 'isShopCard': 1, 'number': 51, 'orderInMemory': 104, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 180, 'mana_cost': 5, 'item_id': 51},
    'Crystal Rose': {'DolphinAddress': '80258e6a', 'element': 'Water', 'hexCode': '3E', 'isKeyCard': 0, 'isShopCard': 1, 'number': 52, 'orderInMemory': 61, 'rarity': 3, 'type': 'Weapon', 'hasCombo': 1, 'price': 270, 'mana_cost': 4, 'item_id': 52},
    'Dark Raven': {'DolphinAddress': '80258e7e', 'element': 'Fire', 'hexCode': '3F', 'isKeyCard': 0, 'isShopCard': 1, 'number': 53, 'orderInMemory': 62, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 1, 'price': 15, 'mana_cost': 1, 'item_id': 53},
    'Wizard': {'DolphinAddress': '80258ea6', 'element': 'Fire', 'hexCode': '41', 'isKeyCard': 0, 'isShopCard': 1, 'number': 54, 'orderInMemory': 64, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 360, 'mana_cost': 6, 'item_id': 54},
    'Dragonoid': {'DolphinAddress': '80258eba', 'element': 'Earth', 'hexCode': '42', 'isKeyCard': 0, 'isShopCard': 1, 'number': 55, 'orderInMemory': 65, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 0, 'price': 300, 'mana_cost': 3, 'item_id': 55},
    'Dryad': {'DolphinAddress': '80258ece', 'element': 'Wood', 'hexCode': '43', 'isKeyCard': 0, 'isShopCard': 1, 'number': 56, 'orderInMemory': 66, 'rarity': 2, 'type': 'Helper', 'hasCombo': 1, 'price': 510, 'mana_cost': 5, 'item_id': 56},
    'Birdman': {'DolphinAddress': '80258ee2', 'element': 'Wood', 'hexCode': '44', 'isKeyCard': 1, 'isShopCard': 0, 'number': 57, 'orderInMemory': 67, 'rarity': 5, 'type': 'Transform', 'hasCombo': 0, 'price': 0, 'mana_cost': 5, 'item_id': 57},
    "Will 'o wisp": {'DolphinAddress': '80258ef6', 'element': 'Fire', 'hexCode': '45', 'isKeyCard': 0, 'isShopCard': 1, 'number': 58, 'orderInMemory': 68, 'rarity': 1, 'type': 'Helper', 'hasCombo': 0, 'price': 150, 'mana_cost': 3, 'item_id': 58},
    'Archer Tree': {'DolphinAddress': '80258f0a', 'element': 'Wood', 'hexCode': '46', 'isKeyCard': 0, 'isShopCard': 1, 'number': 59, 'orderInMemory': 69, 'rarity': 3, 'type': 'Weapon', 'hasCombo': 1, 'price': 120, 'mana_cost': 3, 'item_id': 59},
    'Stone Head': {'DolphinAddress': '80258f1e', 'element': 'Fire', 'hexCode': '47', 'isKeyCard': 0, 'isShopCard': 1, 'number': 60, 'orderInMemory': 70, 'rarity': 5, 'type': 'Helper', 'hasCombo': 1, 'price': 630, 'mana_cost': 5, 'item_id': 60},
    'Blood Bush': {'DolphinAddress': '80258f32', 'element': 'Fire', 'hexCode': '48', 'isKeyCard': 0, 'isShopCard': 1, 'number': 61, 'orderInMemory': 71, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 0, 'price': 120, 'mana_cost': 4, 'item_id': 61},
    'Efreet': {'DolphinAddress': '80258f46', 'element': 'Fire', 'hexCode': '49', 'isKeyCard': 0, 'isShopCard': 1, 'number': 62, 'orderInMemory': 72, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 840, 'mana_cost': 4, 'item_id': 62},
    'Dragon Knight': {'DolphinAddress': '80258f5a', 'element': 'Water', 'hexCode': '4a', 'isKeyCard': 0, 'isShopCard': 1, 'number': 63, 'orderInMemory': 73, 'rarity': 3, 'type': 'Weapon', 'hasCombo': 1, 'price': 270, 'mana_cost': 3, 'item_id': 63},
    'Demon Fox': {'DolphinAddress': '80258f6e', 'element': 'Fire', 'hexCode': '4b', 'isKeyCard': 0, 'isShopCard': 1, 'number': 64, 'orderInMemory': 74, 'rarity': 6, 'type': 'Summons', 'hasCombo': 1, 'price': 3330, 'mana_cost': 9, 'item_id': 64},
    'Juggernaut': {'DolphinAddress': '80258f82', 'element': 'Earth', 'hexCode': '4c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 65, 'orderInMemory': 75, 'rarity': 5, 'type': 'Helper', 'hasCombo': 1, 'price': 720, 'mana_cost': 5, 'item_id': 65},
    'Fire Gargoyle': {'DolphinAddress': '80258f96', 'element': 'Fire', 'hexCode': '4D', 'isKeyCard': 0, 'isShopCard': 1, 'number': 66, 'orderInMemory': 76, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 600, 'mana_cost': 8, 'item_id': 66},
    'Great Demon': {'DolphinAddress': '80258faa', 'element': 'Fire', 'hexCode': '4e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 67, 'orderInMemory': 77, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 0, 'price': 720, 'mana_cost': 4, 'item_id': 67},
    'Evil Eye': {'DolphinAddress': '80258fbe', 'element': 'Wood', 'hexCode': '4F', 'isKeyCard': 0, 'isShopCard': 1, 'number': 68, 'orderInMemory': 78, 'rarity': 1, 'type': 'Helper', 'hasCombo': 0, 'price': 240, 'mana_cost': 5, 'item_id': 68},
    'Blue Dragon': {'DolphinAddress': '80258fd2', 'element': 'Water', 'hexCode': '50', 'isKeyCard': 0, 'isShopCard': 0, 'number': 69, 'orderInMemory': 79, 'rarity': 8, 'type': 'Summons', 'hasCombo': 1, 'price': 0, 'mana_cost': 20, 'item_id': 69},
    'Gnome': {'DolphinAddress': '80258fe6', 'element': 'Earth', 'hexCode': '51', 'isKeyCard': 0, 'isShopCard': 1, 'number': 70, 'orderInMemory': 80, 'rarity': 2, 'type': 'Helper', 'hasCombo': 1, 'price': 480, 'mana_cost': 5, 'item_id': 70},
    'Venom Lizard': {'DolphinAddress': '802592b6', 'element': 'Wood', 'hexCode': '75', 'isKeyCard': 0, 'isShopCard': 1, 'number': 71, 'orderInMemory': 116, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 1, 'price': 120, 'mana_cost': 2, 'item_id': 71},
    'Tiger Mage': {'DolphinAddress': '80258ffa', 'element': 'Fire', 'hexCode': '52', 'isKeyCard': 0, 'isShopCard': 1, 'number': 72, 'orderInMemory': 81, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 1800, 'mana_cost': 6, 'item_id': 72},
    'Hydra': {'DolphinAddress': '8025900e', 'element': 'Water', 'hexCode': '53', 'isKeyCard': 0, 'isShopCard': 1, 'number': 73, 'orderInMemory': 82, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 1500, 'mana_cost': 11, 'item_id': 73},
    'Siren': {'DolphinAddress': '80259022', 'element': 'Wood', 'hexCode': '54', 'isKeyCard': 0, 'isShopCard': 1, 'number': 74, 'orderInMemory': 83, 'rarity': 5, 'type': 'Independent', 'hasCombo': 1, 'price': 480, 'mana_cost': 4, 'item_id': 74},
    'Salamander': {'DolphinAddress': '802592a2', 'element': 'Fire', 'hexCode': '74', 'isKeyCard': 0, 'isShopCard': 1, 'number': 75, 'orderInMemory': 115, 'rarity': 2, 'type': 'Helper', 'hasCombo': 1, 'price': 510, 'mana_cost': 5, 'item_id': 75},
    'Chimera': {'DolphinAddress': '80259036', 'element': 'Fire', 'hexCode': '55', 'isKeyCard': 0, 'isShopCard': 1, 'number': 76, 'orderInMemory': 84, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 690, 'mana_cost': 7, 'item_id': 76},
    'Goblin Lord': {'DolphinAddress': '8025922a', 'element': 'Neutral', 'hexCode': '6e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 77, 'orderInMemory': 109, 'rarity': 4, 'type': 'Helper', 'hasCombo': 1, 'price': 1140, 'mana_cost': 5, 'item_id': 77},
    'Scythe Beast': {'DolphinAddress': '8025905e', 'element': 'Wood', 'hexCode': '57', 'isKeyCard': 0, 'isShopCard': 1, 'number': 78, 'orderInMemory': 86, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 0, 'price': 120, 'mana_cost': 2, 'item_id': 78},
    'Kitty Trap': {'DolphinAddress': '80259072', 'element': 'Fire', 'hexCode': '58', 'isKeyCard': 0, 'isShopCard': 1, 'number': 79, 'orderInMemory': 87, 'rarity': 2, 'type': 'Helper', 'hasCombo': 0, 'price': 450, 'mana_cost': 5, 'item_id': 79},
    'Night Mare': {'DolphinAddress': '80259086', 'element': 'Neutral', 'hexCode': '59', 'isKeyCard': 0, 'isShopCard': 1, 'number': 80, 'orderInMemory': 88, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 1800, 'mana_cost': 7, 'item_id': 80},
    'Golden Phoenix': {'DolphinAddress': '8025909a', 'element': 'Fire', 'hexCode': '5a', 'isKeyCard': 0, 'isShopCard': 0, 'number': 81, 'orderInMemory': 89, 'rarity': 8, 'type': 'Helper', 'hasCombo': 1, 'price': 0, 'mana_cost': 20, 'item_id': 81},
    'Rheebus': {'DolphinAddress': '8025904a', 'element': 'Wood', 'hexCode': '56', 'isKeyCard': 0, 'isShopCard': 1, 'number': 82, 'orderInMemory': 85, 'rarity': 4, 'type': 'Helper', 'hasCombo': 1, 'price': 450, 'mana_cost': 5, 'item_id': 82},
    'White Tiger': {'DolphinAddress': '802590ae', 'element': 'Wood', 'hexCode': '5b', 'isKeyCard': 0, 'isShopCard': 0, 'number': 83, 'orderInMemory': 90, 'rarity': 8, 'type': 'Summons', 'hasCombo': 1, 'price': 0, 'mana_cost': 20, 'item_id': 83},
    'Venus Spider': {'DolphinAddress': '802590c2', 'element': 'Earth', 'hexCode': '5C', 'isKeyCard': 0, 'isShopCard': 1, 'number': 84, 'orderInMemory': 91, 'rarity': 2, 'type': 'Summons', 'hasCombo': 0, 'price': 150, 'mana_cost': 3, 'item_id': 84},
    'Vampire': {'DolphinAddress': '802590d6', 'element': 'Neutral', 'hexCode': '5D', 'isKeyCard': 0, 'isShopCard': 1, 'number': 85, 'orderInMemory': 92, 'rarity': 6, 'type': 'Summons', 'hasCombo': 0, 'price': 2700, 'mana_cost': 9, 'item_id': 85},
    'Sphinx': {'DolphinAddress': '802590ea', 'element': 'Earth', 'hexCode': '5E', 'isKeyCard': 0, 'isShopCard': 1, 'number': 86, 'orderInMemory': 93, 'rarity': 6, 'type': 'Weapon', 'hasCombo': 1, 'price': 1650, 'mana_cost': 10, 'item_id': 86},
    'Mermaid': {'DolphinAddress': '802591da', 'element': 'Water', 'hexCode': '6a', 'isKeyCard': 0, 'isShopCard': 1, 'number': 87, 'orderInMemory': 105, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 720, 'mana_cost': 6, 'item_id': 87},
    'Puppet Master': {'DolphinAddress': '802590fe', 'element': 'Neutral', 'hexCode': '5F', 'isKeyCard': 0, 'isShopCard': 1, 'number': 88, 'orderInMemory': 94, 'rarity': 6, 'type': 'Summons', 'hasCombo': 0, 'price': 1800, 'mana_cost': 7, 'item_id': 88},
    'Plague Rat': {'DolphinAddress': '80259112', 'element': 'Earth', 'hexCode': '60', 'isKeyCard': 0, 'isShopCard': 1, 'number': 89, 'orderInMemory': 95, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 60, 'mana_cost': 4, 'item_id': 89},
    'Undine': {'DolphinAddress': '80259126', 'element': 'Water', 'hexCode': '61', 'isKeyCard': 0, 'isShopCard': 1, 'number': 90, 'orderInMemory': 96, 'rarity': 2, 'type': 'Helper', 'hasCombo': 1, 'price': 480, 'mana_cost': 5, 'item_id': 90},
    'Whip Worm': {'DolphinAddress': '8025913a', 'element': 'Wood', 'hexCode': '62', 'isKeyCard': 0, 'isShopCard': 1, 'number': 91, 'orderInMemory': 97, 'rarity': 5, 'type': 'Helper', 'hasCombo': 1, 'price': 1800, 'mana_cost': 7, 'item_id': 91},
    'Trickster': {'DolphinAddress': '8025914e', 'element': 'Wood', 'hexCode': '63', 'isKeyCard': 0, 'isShopCard': 1, 'number': 92, 'orderInMemory': 98, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 1350, 'mana_cost': 8, 'item_id': 92},
    'Demon Skeleton': {'DolphinAddress': '802591ee', 'element': 'Water', 'hexCode': '6b', 'isKeyCard': 0, 'isShopCard': 1, 'number': 93, 'orderInMemory': 106, 'rarity': 4, 'type': 'Independent', 'hasCombo': 1, 'price': 1440, 'mana_cost': 9, 'item_id': 93},
    'Caterpoker': {'DolphinAddress': '80259162', 'element': 'Wood', 'hexCode': '64', 'isKeyCard': 0, 'isShopCard': 1, 'number': 94, 'orderInMemory': 99, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 135, 'mana_cost': 4, 'item_id': 94},
    'Beelzebub': {'DolphinAddress': '80259176', 'element': 'Neutral', 'hexCode': '65', 'isKeyCard': 0, 'isShopCard': 1, 'number': 95, 'orderInMemory': 100, 'rarity': 5, 'type': 'Helper', 'hasCombo': 0, 'price': 1080, 'mana_cost': 9, 'item_id': 95},
    'Mind Flayer': {'DolphinAddress': '80258bc2', 'element': 'Water', 'hexCode': '1c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 96, 'orderInMemory': 27, 'rarity': 6, 'type': 'Summons', 'hasCombo': 1, 'price': 3600, 'mana_cost': 14, 'item_id': 96},
    'Ice Golem': {'DolphinAddress': '8025918a', 'element': 'Water', 'hexCode': '66', 'isKeyCard': 0, 'isShopCard': 1, 'number': 97, 'orderInMemory': 101, 'rarity': 6, 'type': 'Summons', 'hasCombo': 1, 'price': 3600, 'mana_cost': 9, 'item_id': 97},
    'Cyclops': {'DolphinAddress': '8025923e', 'element': 'Earth', 'hexCode': '6f', 'isKeyCard': 0, 'isShopCard': 1, 'number': 98, 'orderInMemory': 110, 'rarity': 5, 'type': 'Helper', 'hasCombo': 0, 'price': 1200, 'mana_cost': 5, 'item_id': 98},
    'Black Dragon': {'DolphinAddress': '80258e92', 'element': 'Neutral', 'hexCode': '40', 'isKeyCard': 0, 'isShopCard': 1, 'number': 99, 'orderInMemory': 63, 'rarity': 7, 'type': 'Independent', 'hasCombo': 0, 'price': 5700, 'mana_cost': 16, 'item_id': 99},
    'Steel Skeleton': {'DolphinAddress': '80259252', 'element': 'Neutral', 'hexCode': '70', 'isKeyCard': 0, 'isShopCard': 1, 'number': 100, 'orderInMemory': 111, 'rarity': 6, 'type': 'Independent', 'hasCombo': 1, 'price': 3900, 'mana_cost': 10, 'item_id': 100},
    'Chaos Knight': {'DolphinAddress': '80259266', 'element': 'Neutral', 'hexCode': '71', 'isKeyCard': 0, 'isShopCard': 1, 'number': 101, 'orderInMemory': 112, 'rarity': 5, 'type': 'Weapon', 'hasCombo': 1, 'price': 1920, 'mana_cost': 6, 'item_id': 101},
    'Decoy Pillar': {'DolphinAddress': '8025927a', 'element': 'Neutral', 'hexCode': '72', 'isKeyCard': 0, 'isShopCard': 1, 'number': 102, 'orderInMemory': 113, 'rarity': 5, 'type': 'Helper', 'hasCombo': 1, 'price': 4800, 'mana_cost': 9, 'item_id': 102},
    'Elephant King': {'DolphinAddress': '80258c9e', 'element': 'Earth', 'hexCode': '27', 'isKeyCard': 0, 'isShopCard': 1, 'number': 103, 'orderInMemory': 38, 'rarity': 6, 'type': 'Summons', 'hasCombo': 1, 'price': 3900, 'mana_cost': 8, 'item_id': 103},
    'God of Destruction': {'DolphinAddress': '802592ca', 'element': 'Neutral', 'hexCode': '76', 'isKeyCard': 1, 'isShopCard': 0, 'number': 104, 'orderInMemory': 117, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 12, 'item_id': 104},
    'Doppelganger': {'DolphinAddress': '8025928e', 'element': 'Neutral', 'hexCode': '73', 'isKeyCard': 0, 'isShopCard': 0, 'number': 105, 'orderInMemory': 114, 'rarity': 8, 'type': 'Independent', 'hasCombo': 1, 'price': 0, 'mana_cost': 10, 'item_id': 105},
    'Earth Elemental': {'DolphinAddress': '802592de', 'element': 'Earth', 'hexCode': '77', 'isKeyCard': 0, 'isShopCard': 1, 'number': 106, 'orderInMemory': 118, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 1200, 'mana_cost': 6, 'item_id': 106},
    'Water Elemental': {'DolphinAddress': '802592f2', 'element': 'Water', 'hexCode': '78', 'isKeyCard': 0, 'isShopCard': 1, 'number': 107, 'orderInMemory': 119, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 1200, 'mana_cost': 6, 'item_id': 107},
    'Fire Elemental': {'DolphinAddress': '80259306', 'element': 'Fire', 'hexCode': '79', 'isKeyCard': 0, 'isShopCard': 1, 'number': 108, 'orderInMemory': 120, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 1200, 'mana_cost': 6, 'item_id': 108},
    'Wood Elemental': {'DolphinAddress': '8025931a', 'element': 'Wood', 'hexCode': '7a', 'isKeyCard': 0, 'isShopCard': 1, 'number': 109, 'orderInMemory': 121, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 1200, 'mana_cost': 6, 'item_id': 109},
    'Aggressor GL2': {'DolphinAddress': '80259aea', 'element': 'Mech', 'hexCode': 'de', 'isKeyCard': 0, 'isShopCard': 1, 'number': 110, 'orderInMemory': 214, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 180, 'mana_cost': 5, 'item_id': 110},
    'Succubus': {'DolphinAddress': '80258bd6', 'element': 'Neutral', 'hexCode': '1d', 'isKeyCard': 0, 'isShopCard': 1, 'number': 111, 'orderInMemory': 28, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 1500, 'mana_cost': 8, 'item_id': 111},
    'Incubus': {'DolphinAddress': '80258bea', 'element': 'Neutral', 'hexCode': '1e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 112, 'orderInMemory': 29, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 1500, 'mana_cost': 11, 'item_id': 112},
    'Valkyrie': {'DolphinAddress': '80258a0a', 'element': 'Fire', 'hexCode': '6', 'isKeyCard': 0, 'isShopCard': 1, 'number': 113, 'orderInMemory': 5, 'rarity': 7, 'type': 'Summons', 'hasCombo': 1, 'price': 7200, 'mana_cost': 8, 'item_id': 113},
    'Napalm Beast': {'DolphinAddress': '8025954a', 'element': 'Fire', 'hexCode': '96', 'isKeyCard': 0, 'isShopCard': 1, 'number': 114, 'orderInMemory': 149, 'rarity': 5, 'type': 'Helper', 'hasCombo': 0, 'price': 900, 'mana_cost': 7, 'item_id': 114},
    'Green Dragon': {'DolphinAddress': '8025955e', 'element': 'Wood', 'hexCode': '97', 'isKeyCard': 0, 'isShopCard': 1, 'number': 115, 'orderInMemory': 150, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 6000, 'mana_cost': 10, 'item_id': 115},
    'Wyvern': {'DolphinAddress': '802593ce', 'element': 'Neutral', 'hexCode': '83', 'isKeyCard': 0, 'isShopCard': 1, 'number': 116, 'orderInMemory': 130, 'rarity': 6, 'type': 'Transform', 'hasCombo': 0, 'price': 780, 'mana_cost': 4, 'item_id': 116},
    'Sprite': {'DolphinAddress': '802598ce', 'element': 'Water', 'hexCode': 'c3', 'isKeyCard': 0, 'isShopCard': 1, 'number': 117, 'orderInMemory': 190, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 480, 'mana_cost': 5, 'item_id': 117},
    'Leprechaun': {'DolphinAddress': '8025973e', 'element': 'Fire', 'hexCode': 'af', 'isKeyCard': 0, 'isShopCard': 1, 'number': 118, 'orderInMemory': 174, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 300, 'mana_cost': 6, 'item_id': 118},
    'Charadrius': {'DolphinAddress': '80259716', 'element': 'Water', 'hexCode': 'ad', 'isKeyCard': 0, 'isShopCard': 1, 'number': 119, 'orderInMemory': 172, 'rarity': 5, 'type': 'Weapon', 'hasCombo': 0, 'price': 450, 'mana_cost': 4, 'item_id': 119},
    'Yowie': {'DolphinAddress': '80259392', 'element': 'Water', 'hexCode': '80', 'isKeyCard': 0, 'isShopCard': 1, 'number': 120, 'orderInMemory': 127, 'rarity': 1, 'type': 'Independent', 'hasCombo': 0, 'price': 15, 'mana_cost': 0, 'item_id': 120},
    'Apsaras': {'DolphinAddress': '80259a22', 'element': 'Water', 'hexCode': 'd4', 'isKeyCard': 0, 'isShopCard': 1, 'number': 121, 'orderInMemory': 205, 'rarity': 6, 'type': 'Helper', 'hasCombo': 0, 'price': 2100, 'mana_cost': 9, 'item_id': 121},
    'Death': {'DolphinAddress': '802594d2', 'element': 'Neutral', 'hexCode': '90', 'isKeyCard': 0, 'isShopCard': 1, 'number': 122, 'orderInMemory': 143, 'rarity': 3, 'type': 'Weapon', 'hasCombo': 0, 'price': 540, 'mana_cost': 4, 'item_id': 122},
    'Porcupig': {'DolphinAddress': '802595c2', 'element': 'Earth', 'hexCode': '9c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 123, 'orderInMemory': 155, 'rarity': 1, 'type': 'Independent', 'hasCombo': 0, 'price': 15, 'mana_cost': 1, 'item_id': 123},
    'Golden Porcupig': {'DolphinAddress': '802595d6', 'element': 'Earth', 'hexCode': '9d', 'isKeyCard': 0, 'isShopCard': 1, 'number': 124, 'orderInMemory': 156, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 45, 'mana_cost': 2, 'item_id': 124},
    'Mandra Dancer': {'DolphinAddress': '802599aa', 'element': 'Wood', 'hexCode': 'ce', 'isKeyCard': 0, 'isShopCard': 1, 'number': 125, 'orderInMemory': 200, 'rarity': 4, 'type': 'Independent', 'hasCombo': 1, 'price': 270, 'mana_cost': 3, 'item_id': 125},
    'Super Pumper': {'DolphinAddress': '8025990a', 'element': 'Water', 'hexCode': 'c6', 'isKeyCard': 0, 'isShopCard': 1, 'number': 126, 'orderInMemory': 193, 'rarity': 7, 'type': 'Helper', 'hasCombo': 0, 'price': 2700, 'mana_cost': 5, 'item_id': 126},
    'Lucky Lion': {'DolphinAddress': '802597b6', 'element': 'Fire', 'hexCode': 'B5', 'isKeyCard': 0, 'isShopCard': 1, 'number': 127, 'orderInMemory': 180, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 1350, 'mana_cost': 8, 'item_id': 127},
    'Vodianoi': {'DolphinAddress': '802597ca', 'element': 'Water', 'hexCode': 'b6', 'isKeyCard': 0, 'isShopCard': 1, 'number': 128, 'orderInMemory': 181, 'rarity': 4, 'type': 'Independent', 'hasCombo': 0, 'price': 450, 'mana_cost': 9, 'item_id': 128},
    'Uroboros': {'DolphinAddress': '802597de', 'element': 'Earth', 'hexCode': 'b7', 'isKeyCard': 0, 'isShopCard': 0, 'number': 129, 'orderInMemory': 182, 'rarity': 8, 'type': 'Helper', 'hasCombo': 0, 'price': 0, 'mana_cost': 6, 'item_id': 129},
    'Yin Yang': {'DolphinAddress': '80259842', 'element': 'Neutral', 'hexCode': 'bc', 'isKeyCard': 0, 'isShopCard': 1, 'number': 130, 'orderInMemory': 184, 'rarity': 7, 'type': 'Independent', 'hasCombo': 0, 'price': 2700, 'mana_cost': 6, 'item_id': 130},
    'Dao': {'DolphinAddress': '80259446', 'element': 'Earth', 'hexCode': '89', 'isKeyCard': 0, 'isShopCard': 1, 'number': 131, 'orderInMemory': 136, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 840, 'mana_cost': 4, 'item_id': 131},
    'Manticore': {'DolphinAddress': '8025945a', 'element': 'Fire', 'hexCode': '8a', 'isKeyCard': 0, 'isShopCard': 1, 'number': 132, 'orderInMemory': 137, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 960, 'mana_cost': 7, 'item_id': 132},
    'March Hare': {'DolphinAddress': '8025950e', 'element': 'Water', 'hexCode': '93', 'isKeyCard': 0, 'isShopCard': 1, 'number': 133, 'orderInMemory': 146, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 1200, 'mana_cost': 6, 'item_id': 133},
    'Marid': {'DolphinAddress': '802594aa', 'element': 'Water', 'hexCode': '8E', 'isKeyCard': 0, 'isShopCard': 1, 'number': 134, 'orderInMemory': 141, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 510, 'mana_cost': 4, 'item_id': 134},
    'Elf': {'DolphinAddress': '80259356', 'element': 'Wood', 'hexCode': '7D', 'isKeyCard': 0, 'isShopCard': 1, 'number': 135, 'orderInMemory': 124, 'rarity': 3, 'type': 'Independent', 'hasCombo': 1, 'price': 450, 'mana_cost': 6, 'item_id': 135},
    'Elf Lord': {'DolphinAddress': '8025936a', 'element': 'Wood', 'hexCode': '7e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 136, 'orderInMemory': 125, 'rarity': 6, 'type': 'Independent', 'hasCombo': 1, 'price': 990, 'mana_cost': 8, 'item_id': 136},
    'Dark Elf': {'DolphinAddress': '80259482', 'element': 'Neutral', 'hexCode': '8c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 137, 'orderInMemory': 139, 'rarity': 5, 'type': 'Independent', 'hasCombo': 1, 'price': 1200, 'mana_cost': 7, 'item_id': 137},
    'Global Bust': {'DolphinAddress': '802596da', 'element': 'Earth', 'hexCode': 'aa', 'isKeyCard': 0, 'isShopCard': 1, 'number': 138, 'orderInMemory': 169, 'rarity': 5, 'type': 'Helper', 'hasCombo': 0, 'price': 630, 'mana_cost': 8, 'item_id': 138},
    'Garuda': {'DolphinAddress': '80258da2', 'element': 'Wood', 'hexCode': '34', 'isKeyCard': 0, 'isShopCard': 1, 'number': 139, 'orderInMemory': 51, 'rarity': 7, 'type': 'Transform', 'hasCombo': 0, 'price': 2100, 'mana_cost': 10, 'item_id': 139},
    'Popgun Charlie': {'DolphinAddress': '8025987e', 'element': 'Fire', 'hexCode': 'bf', 'isKeyCard': 0, 'isShopCard': 1, 'number': 140, 'orderInMemory': 187, 'rarity': 2, 'type': 'Independent', 'hasCombo': 0, 'price': 60, 'mana_cost': 2, 'item_id': 140},
    'Acid Cloud': {'DolphinAddress': '8025941e', 'element': 'Earth', 'hexCode': '87', 'isKeyCard': 0, 'isShopCard': 1, 'number': 141, 'orderInMemory': 134, 'rarity': 4, 'type': 'Independent', 'hasCombo': 1, 'price': 450, 'mana_cost': 2, 'item_id': 141},
    'Baby Dragon': {'DolphinAddress': '80259342', 'element': 'Earth', 'hexCode': '7c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 142, 'orderInMemory': 123, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 120, 'mana_cost': 2, 'item_id': 142},
    'Brine Dragon': {'DolphinAddress': '802594fa', 'element': 'Water', 'hexCode': '92', 'isKeyCard': 0, 'isShopCard': 1, 'number': 143, 'orderInMemory': 145, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 6300, 'mana_cost': 10, 'item_id': 143},
    'Circasaurus': {'DolphinAddress': '80259a36', 'element': 'Wood', 'hexCode': 'd5', 'isKeyCard': 0, 'isShopCard': 1, 'number': 144, 'orderInMemory': 206, 'rarity': 1, 'type': 'Transform', 'hasCombo': 0, 'price': 300, 'mana_cost': 3, 'item_id': 144},
    'Stone Golem': {'DolphinAddress': '80259a5e', 'element': 'Earth', 'hexCode': 'D7', 'isKeyCard': 1, 'isShopCard': 0, 'number': 145, 'orderInMemory': 208, 'rarity': 4, 'type': 'Transform', 'hasCombo': 1, 'price': 0, 'mana_cost': 8, 'item_id': 145},
    'Gizmolizer': {'DolphinAddress': '80259aae', 'element': 'Mech', 'hexCode': 'DB', 'isKeyCard': 0, 'isShopCard': 1, 'number': 146, 'orderInMemory': 212, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 840, 'mana_cost': 5, 'item_id': 146},
    'MechLance 5L': {'DolphinAddress': '80259b3a', 'element': 'Mech', 'hexCode': 'e2', 'isKeyCard': 0, 'isShopCard': 1, 'number': 147, 'orderInMemory': 218, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 150, 'mana_cost': 2, 'item_id': 147},
    'Fireworks': {'DolphinAddress': '8025968a', 'element': 'Fire', 'hexCode': 'a6', 'isKeyCard': 0, 'isShopCard': 1, 'number': 148, 'orderInMemory': 165, 'rarity': 6, 'type': 'Summons', 'hasCombo': 0, 'price': 720, 'mana_cost': 9, 'item_id': 148},
    'Sekmet': {'DolphinAddress': '80259946', 'element': 'Wood', 'hexCode': 'C9', 'isKeyCard': 0, 'isShopCard': 0, 'number': 149, 'orderInMemory': 196, 'rarity': 8, 'type': 'Weapon', 'hasCombo': 1, 'price': 0, 'mana_cost': 10, 'item_id': 149},
    'Undead Knight': {'DolphinAddress': '8025991e', 'element': 'Fire', 'hexCode': 'c7', 'isKeyCard': 0, 'isShopCard': 1, 'number': 150, 'orderInMemory': 194, 'rarity': 2, 'type': 'Independent', 'hasCombo': 0, 'price': 120, 'mana_cost': 2, 'item_id': 150},
    'Panther Mage': {'DolphinAddress': '80259932', 'element': 'Wood', 'hexCode': 'c8', 'isKeyCard': 0, 'isShopCard': 1, 'number': 151, 'orderInMemory': 195, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 1800, 'mana_cost': 8, 'item_id': 151},
    'Lamassu': {'DolphinAddress': '802593ba', 'element': 'Earth', 'hexCode': '82', 'isKeyCard': 0, 'isShopCard': 1, 'number': 152, 'orderInMemory': 129, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 480, 'mana_cost': 5, 'item_id': 152},
    'LazerBug 39K': {'DolphinAddress': '80259b76', 'element': 'Mech', 'hexCode': 'e5', 'isKeyCard': 0, 'isShopCard': 1, 'number': 153, 'orderInMemory': 221, 'rarity': 6, 'type': 'Summons', 'hasCombo': 0, 'price': 2100, 'mana_cost': 11, 'item_id': 153},
    'Myconid': {'DolphinAddress': '8025977a', 'element': 'Earth', 'hexCode': 'b2', 'isKeyCard': 0, 'isShopCard': 1, 'number': 154, 'orderInMemory': 177, 'rarity': 2, 'type': 'Helper', 'hasCombo': 0, 'price': 72, 'mana_cost': 1, 'item_id': 154},
    'Spartoi': {'DolphinAddress': '802597a2', 'element': 'Earth', 'hexCode': 'B4', 'isKeyCard': 0, 'isShopCard': 1, 'number': 155, 'orderInMemory': 179, 'rarity': 6, 'type': 'Weapon', 'hasCombo': 0, 'price': 1800, 'mana_cost': 4, 'item_id': 155},
    'Phantom Ship': {'DolphinAddress': '802599fa', 'element': 'Water', 'hexCode': 'd2', 'isKeyCard': 0, 'isShopCard': 1, 'number': 156, 'orderInMemory': 203, 'rarity': 7, 'type': 'Summons', 'hasCombo': 0, 'price': 7500, 'mana_cost': 13, 'item_id': 156},
    'Raflesia': {'DolphinAddress': '802598a6', 'element': 'Wood', 'hexCode': 'C1', 'isKeyCard': 0, 'isShopCard': 1, 'number': 157, 'orderInMemory': 189, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 240, 'mana_cost': 3, 'item_id': 157},
    'Daidarapochi': {'DolphinAddress': '80259586', 'element': 'Water', 'hexCode': '99', 'isKeyCard': 0, 'isShopCard': 1, 'number': 158, 'orderInMemory': 152, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 4500, 'mana_cost': 14, 'item_id': 158},
    'Gemini': {'DolphinAddress': '8025963a', 'element': 'Fire', 'hexCode': 'A2', 'isKeyCard': 0, 'isShopCard': 1, 'number': 159, 'orderInMemory': 161, 'rarity': 7, 'type': 'Summons', 'hasCombo': 0, 'price': 4200, 'mana_cost': 12, 'item_id': 159},
    'Amber Dragon': {'DolphinAddress': '802595ae', 'element': 'Earth', 'hexCode': '9B', 'isKeyCard': 0, 'isShopCard': 1, 'number': 160, 'orderInMemory': 154, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 6000, 'mana_cost': 10, 'item_id': 160},
    'Demon Lord': {'DolphinAddress': '80259806', 'element': 'Fire', 'hexCode': 'b9', 'isKeyCard': 0, 'isShopCard': 1, 'number': 161, 'orderInMemory': 183, 'rarity': 7, 'type': 'Weapon', 'hasCombo': 0, 'price': 1440, 'mana_cost': 9, 'item_id': 161},
    'Witchlette': {'DolphinAddress': '80259a0e', 'element': 'Water', 'hexCode': 'D3', 'isKeyCard': 0, 'isShopCard': 1, 'number': 162, 'orderInMemory': 204, 'rarity': 1, 'type': 'Independent', 'hasCombo': 0, 'price': 120, 'mana_cost': 1, 'item_id': 162},
    'AcidBot': {'DolphinAddress': '80259b9e', 'element': 'Mech', 'hexCode': 'E7', 'isKeyCard': 0, 'isShopCard': 1, 'number': 163, 'orderInMemory': 223, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 150, 'mana_cost': 3, 'item_id': 163},
    'Chameleus': {'DolphinAddress': '80258c76', 'element': 'Wood', 'hexCode': '25', 'isKeyCard': 0, 'isShopCard': 1, 'number': 164, 'orderInMemory': 36, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 3000, 'mana_cost': 6, 'item_id': 164},
    'Devil Plant': {'DolphinAddress': '80258ae6', 'element': 'Wood', 'hexCode': '11', 'isKeyCard': 0, 'isShopCard': 1, 'number': 165, 'orderInMemory': 16, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 840, 'mana_cost': 8, 'item_id': 165},
    'Centaur': {'DolphinAddress': '80258aaa', 'element': 'Wood', 'hexCode': '0e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 166, 'orderInMemory': 13, 'rarity': 6, 'type': 'Transform', 'hasCombo': 0, 'price': 4200, 'mana_cost': 6, 'item_id': 166},
    'Dark Treant': {'DolphinAddress': '80259612', 'element': 'Wood', 'hexCode': 'A0', 'isKeyCard': 0, 'isShopCard': 1, 'number': 167, 'orderInMemory': 159, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 840, 'mana_cost': 5, 'item_id': 167},
    'Coal Treant': {'DolphinAddress': '8025964e', 'element': 'Fire', 'hexCode': 'A3', 'isKeyCard': 0, 'isShopCard': 1, 'number': 168, 'orderInMemory': 162, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 600, 'mana_cost': 5, 'item_id': 168},
    'Sleeping Giant': {'DolphinAddress': '80259676', 'element': 'Wood', 'hexCode': 'a5', 'isKeyCard': 0, 'isShopCard': 1, 'number': 169, 'orderInMemory': 164, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 540, 'mana_cost': 6, 'item_id': 169},
    'Gravity Pillar': {'DolphinAddress': '802596ee', 'element': 'Neutral', 'hexCode': 'AB', 'isKeyCard': 0, 'isShopCard': 1, 'number': 170, 'orderInMemory': 170, 'rarity': 7, 'type': 'Helper', 'hasCombo': 1, 'price': 4800, 'mana_cost': 7, 'item_id': 170},
    'Storm Hagan': {'DolphinAddress': '8025969e', 'element': 'Wood', 'hexCode': 'a7', 'isKeyCard': 0, 'isShopCard': 1, 'number': 171, 'orderInMemory': 166, 'rarity': 2, 'type': 'Summons', 'hasCombo': 1, 'price': 240, 'mana_cost': 4, 'item_id': 171},
    'Rock Hagan': {'DolphinAddress': '802596b2', 'element': 'Water', 'hexCode': 'A8', 'isKeyCard': 0, 'isShopCard': 1, 'number': 172, 'orderInMemory': 167, 'rarity': 2, 'type': 'Summons', 'hasCombo': 1, 'price': 240, 'mana_cost': 4, 'item_id': 172},
    'Bum Hagan': {'DolphinAddress': '802596c6', 'element': 'Earth', 'hexCode': 'A9', 'isKeyCard': 0, 'isShopCard': 1, 'number': 173, 'orderInMemory': 168, 'rarity': 2, 'type': 'Summons', 'hasCombo': 1, 'price': 240, 'mana_cost': 4, 'item_id': 173},
    'Octobush': {'DolphinAddress': '80259996', 'element': 'Neutral', 'hexCode': 'cd', 'isKeyCard': 0, 'isShopCard': 1, 'number': 174, 'orderInMemory': 199, 'rarity': 7, 'type': 'Helper', 'hasCombo': 0, 'price': 1500, 'mana_cost': 9, 'item_id': 174},
    'Chariobot': {'DolphinAddress': '802599e6', 'element': 'Mech', 'hexCode': 'd1', 'isKeyCard': 0, 'isShopCard': 1, 'number': 175, 'orderInMemory': 202, 'rarity': 5, 'type': 'Transform', 'hasCombo': 0, 'price': 750, 'mana_cost': 6, 'item_id': 175},
    'Dark Sprite': {'DolphinAddress': '802598f6', 'element': 'Neutral', 'hexCode': 'c5', 'isKeyCard': 0, 'isShopCard': 1, 'number': 176, 'orderInMemory': 192, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 480, 'mana_cost': 5, 'item_id': 176},
    'Gargoyle': {'DolphinAddress': '8025995a', 'element': 'Fire', 'hexCode': 'ca', 'isKeyCard': 0, 'isShopCard': 1, 'number': 177, 'orderInMemory': 197, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 390, 'mana_cost': 2, 'item_id': 177},
    'MechaPult': {'DolphinAddress': '80259b12', 'element': 'Mech', 'hexCode': 'E0', 'isKeyCard': 0, 'isShopCard': 1, 'number': 178, 'orderInMemory': 216, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 480, 'mana_cost': 4, 'item_id': 178},
    'Aggressor DX5': {'DolphinAddress': '80259b26', 'element': 'Mech', 'hexCode': 'e1', 'isKeyCard': 0, 'isShopCard': 1, 'number': 179, 'orderInMemory': 217, 'rarity': 4, 'type': 'Independent', 'hasCombo': 0, 'price': 600, 'mana_cost': 8, 'item_id': 179},
    'Matador': {'DolphinAddress': '80259662', 'element': 'Fire', 'hexCode': 'a4', 'isKeyCard': 0, 'isShopCard': 1, 'number': 180, 'orderInMemory': 163, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 630, 'mana_cost': 5, 'item_id': 180},
    'Phooka': {'DolphinAddress': '80259626', 'element': 'Water', 'hexCode': 'a1', 'isKeyCard': 0, 'isShopCard': 1, 'number': 181, 'orderInMemory': 160, 'rarity': 5, 'type': 'Helper', 'hasCombo': 0, 'price': 1200, 'mana_cost': 5, 'item_id': 181},
    'Devata': {'DolphinAddress': '802594e6', 'element': 'Neutral', 'hexCode': '91', 'isKeyCard': 0, 'isShopCard': 1, 'number': 182, 'orderInMemory': 144, 'rarity': 4, 'type': 'Transform', 'hasCombo': 0, 'price': 1200, 'mana_cost': 6, 'item_id': 182},
    'Barometz': {'DolphinAddress': '80258b9a', 'element': 'Earth', 'hexCode': '1a', 'isKeyCard': 0, 'isShopCard': 1, 'number': 183, 'orderInMemory': 25, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 600, 'mana_cost': 4, 'item_id': 183},
    'Cerberus': {'DolphinAddress': '80258a32', 'element': 'Fire', 'hexCode': '08', 'isKeyCard': 0, 'isShopCard': 1, 'number': 184, 'orderInMemory': 7, 'rarity': 5, 'type': 'Transform', 'hasCombo': 0, 'price': 1500, 'mana_cost': 5, 'item_id': 184},
    'Thanatos': {'DolphinAddress': '80258a1e', 'element': 'Neutral', 'hexCode': '07', 'isKeyCard': 0, 'isShopCard': 1, 'number': 185, 'orderInMemory': 6, 'rarity': 7, 'type': 'Summons', 'hasCombo': 1, 'price': 6000, 'mana_cost': 12, 'item_id': 185},
    'Nueh': {'DolphinAddress': '80258e42', 'element': 'Wood', 'hexCode': '3C', 'isKeyCard': 0, 'isShopCard': 1, 'number': 186, 'orderInMemory': 59, 'rarity': 7, 'type': 'Summons', 'hasCombo': 0, 'price': 1950, 'mana_cost': 13, 'item_id': 186},
    'Horus': {'DolphinAddress': '802599be', 'element': 'Wood', 'hexCode': 'cf', 'isKeyCard': 0, 'isShopCard': 1, 'number': 187, 'orderInMemory': 201, 'rarity': 4, 'type': 'Independent', 'hasCombo': 0, 'price': 750, 'mana_cost': 4, 'item_id': 187},
    'Acid Dragon': {'DolphinAddress': '802598e2', 'element': 'Neutral', 'hexCode': 'C4', 'isKeyCard': 0, 'isShopCard': 1, 'number': 188, 'orderInMemory': 191, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 5400, 'mana_cost': 11, 'item_id': 188},
    'Rubber Froggy': {'DolphinAddress': '8025986a', 'element': 'Water', 'hexCode': 'be', 'isKeyCard': 0, 'isShopCard': 1, 'number': 189, 'orderInMemory': 186, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 330, 'mana_cost': 6, 'item_id': 189},
    'Boom Monkey': {'DolphinAddress': '80259856', 'element': 'Fire', 'hexCode': 'BD', 'isKeyCard': 0, 'isShopCard': 1, 'number': 190, 'orderInMemory': 185, 'rarity': 6, 'type': 'Independent', 'hasCombo': 0, 'price': 1200, 'mana_cost': 2, 'item_id': 190},
    'UberBomberBot': {'DolphinAddress': '80259ad6', 'element': 'Mech', 'hexCode': 'DD', 'isKeyCard': 0, 'isShopCard': 1, 'number': 191, 'orderInMemory': 213, 'rarity': 4, 'type': 'Independent', 'hasCombo': 0, 'price': 600, 'mana_cost': 5, 'item_id': 191},
    'Gorgon': {'DolphinAddress': '80259496', 'element': 'Neutral', 'hexCode': '8D', 'isKeyCard': 0, 'isShopCard': 1, 'number': 192, 'orderInMemory': 140, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 810, 'mana_cost': 8, 'item_id': 192},
    'Pixie': {'DolphinAddress': '80259432', 'element': 'Earth', 'hexCode': '88', 'isKeyCard': 0, 'isShopCard': 1, 'number': 193, 'orderInMemory': 135, 'rarity': 3, 'type': 'Independent', 'hasCombo': 1, 'price': 360, 'mana_cost': 4, 'item_id': 193},
    'Baba Yaga': {'DolphinAddress': '802593f6', 'element': 'Water', 'hexCode': '85', 'isKeyCard': 0, 'isShopCard': 1, 'number': 194, 'orderInMemory': 132, 'rarity': 5, 'type': 'Transform', 'hasCombo': 0, 'price': 1110, 'mana_cost': 9, 'item_id': 194},
    'Berserk Master': {'DolphinAddress': '8025940a', 'element': 'Fire', 'hexCode': '86', 'isKeyCard': 0, 'isShopCard': 1, 'number': 195, 'orderInMemory': 133, 'rarity': 7, 'type': 'Independent', 'hasCombo': 0, 'price': 2100, 'mana_cost': 5, 'item_id': 195},
    'Rabandos': {'DolphinAddress': '802593e2', 'element': 'Neutral', 'hexCode': '84', 'isKeyCard': 0, 'isShopCard': 0, 'number': 196, 'orderInMemory': 131, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 13, 'item_id': 196},
    'Hell Hound': {'DolphinAddress': '802593a6', 'element': 'Fire', 'hexCode': '81', 'isKeyCard': 1, 'isShopCard': 0, 'number': 197, 'orderInMemory': 128, 'rarity': 3, 'type': 'Transform', 'hasCombo': 0, 'price': 0, 'mana_cost': 7, 'item_id': 197},
    'Tumble Chick': {'DolphinAddress': '80259752', 'element': 'Earth', 'hexCode': 'b0', 'isKeyCard': 0, 'isShopCard': 1, 'number': 198, 'orderInMemory': 175, 'rarity': 1, 'type': 'Independent', 'hasCombo': 0, 'price': 15, 'mana_cost': 1, 'item_id': 198},
    'Mad Reverser': {'DolphinAddress': '80259766', 'element': 'Wood', 'hexCode': 'b1', 'isKeyCard': 0, 'isShopCard': 1, 'number': 199, 'orderInMemory': 176, 'rarity': 6, 'type': 'Helper', 'hasCombo': 0, 'price': 900, 'mana_cost': 6, 'item_id': 199},
    'Sleipnir': {'DolphinAddress': '8025978e', 'element': 'Water', 'hexCode': 'b3', 'isKeyCard': 0, 'isShopCard': 0, 'number': 200, 'orderInMemory': 178, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 15, 'item_id': 200},
    'Claws-R-Us': {'DolphinAddress': '80259b4e', 'element': 'Mech', 'hexCode': 'e3', 'isKeyCard': 0, 'isShopCard': 1, 'number': 201, 'orderInMemory': 219, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 900, 'mana_cost': 10, 'item_id': 201},
    'TriBlaster': {'DolphinAddress': '80259b62', 'element': 'Mech', 'hexCode': 'e4', 'isKeyCard': 0, 'isShopCard': 1, 'number': 202, 'orderInMemory': 220, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 1200, 'mana_cost': 11, 'item_id': 202},
    'Anarchy Owl': {'DolphinAddress': '80259a4a', 'element': 'Wood', 'hexCode': 'd6', 'isKeyCard': 0, 'isShopCard': 1, 'number': 203, 'orderInMemory': 207, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 900, 'mana_cost': 5, 'item_id': 203},
    'Pegasus': {'DolphinAddress': '80259982', 'element': 'Wood', 'hexCode': 'cc', 'isKeyCard': 0, 'isShopCard': 0, 'number': 204, 'orderInMemory': 198, 'rarity': 7, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 10, 'item_id': 204},
    'Phoenix': {'DolphinAddress': '80258a46', 'element': 'Fire', 'hexCode': '09', 'isKeyCard': 0, 'isShopCard': 1, 'number': 205, 'orderInMemory': 8, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 2400, 'mana_cost': 12, 'item_id': 205},
    'Ashura': {'DolphinAddress': '80258b0e', 'element': 'Fire', 'hexCode': '13', 'isKeyCard': 0, 'isShopCard': 1, 'number': 206, 'orderInMemory': 18, 'rarity': 8, 'type': 'Helper', 'hasCombo': 0, 'price': 9999, 'mana_cost': 10, 'item_id': 206},
    'Talos': {'DolphinAddress': '80259702', 'element': 'Earth', 'hexCode': 'ac', 'isKeyCard': 0, 'isShopCard': 0, 'number': 207, 'orderInMemory': 171, 'rarity': 7, 'type': 'Transform', 'hasCombo': 0, 'price': 0, 'mana_cost': 7, 'item_id': 207},
    'Crystal Magic': {'DolphinAddress': '8025972a', 'element': 'Neutral', 'hexCode': 'ae', 'isKeyCard': 0, 'isShopCard': 0, 'number': 208, 'orderInMemory': 173, 'rarity': 5, 'type': 'Helper', 'hasCombo': 0, 'price': 0, 'mana_cost': 16, 'item_id': 208},
    'Psycho Dice': {'DolphinAddress': '802595fe', 'element': 'Neutral', 'hexCode': '9f', 'isKeyCard': 0, 'isShopCard': 1, 'number': 209, 'orderInMemory': 158, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 3600, 'mana_cost': 6, 'item_id': 209},
    'Blue Mold': {'DolphinAddress': '80259572', 'element': 'Earth', 'hexCode': '98', 'isKeyCard': 0, 'isShopCard': 1, 'number': 210, 'orderInMemory': 151, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 510, 'mana_cost': 9, 'item_id': 210},
    'Jade Giant': {'DolphinAddress': '8025946e', 'element': 'Fire', 'hexCode': '8B', 'isKeyCard': 0, 'isShopCard': 1, 'number': 211, 'orderInMemory': 138, 'rarity': 3, 'type': 'Summons', 'hasCombo': 0, 'price': 360, 'mana_cost': 5, 'item_id': 211},
    'Fafnir': {'DolphinAddress': '8025932e', 'element': 'Fire', 'hexCode': '7b', 'isKeyCard': 0, 'isShopCard': 0, 'number': 212, 'orderInMemory': 122, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 16, 'item_id': 212},
    'Beaker': {'DolphinAddress': '8025937e', 'element': 'Water', 'hexCode': '7f', 'isKeyCard': 0, 'isShopCard': 1, 'number': 213, 'orderInMemory': 126, 'rarity': 1, 'type': 'Independent', 'hasCombo': 0, 'price': 24, 'mana_cost': 1, 'item_id': 213},
    'Pazuzu': {'DolphinAddress': '80259536', 'element': 'Earth', 'hexCode': '95', 'isKeyCard': 0, 'isShopCard': 0, 'number': 214, 'orderInMemory': 148, 'rarity': 8, 'type': 'Transform', 'hasCombo': 0, 'price': 0, 'mana_cost': 13, 'item_id': 214},
    'Super Scrubber': {'DolphinAddress': '80259afe', 'element': 'Mech', 'hexCode': 'DF', 'isKeyCard': 0, 'isShopCard': 1, 'number': 215, 'orderInMemory': 215, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 360, 'mana_cost': 2, 'item_id': 215},
    'AstroBot': {'DolphinAddress': '80259b8a', 'element': 'Mech', 'hexCode': 'E6', 'isKeyCard': 0, 'isShopCard': 1, 'number': 216, 'orderInMemory': 222, 'rarity': 7, 'type': 'Weapon', 'hasCombo': 0, 'price': 3600, 'mana_cost': 10, 'item_id': 216},
    'Vouivre': {'DolphinAddress': '802595ea', 'element': 'Earth', 'hexCode': '9e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 217, 'orderInMemory': 157, 'rarity': 7, 'type': 'Weapon', 'hasCombo': 0, 'price': 5400, 'mana_cost': 5, 'item_id': 217},
    'Fire Moray': {'DolphinAddress': '80259a72', 'element': 'Fire', 'hexCode': 'd8', 'isKeyCard': 0, 'isShopCard': 1, 'number': 218, 'orderInMemory': 209, 'rarity': 4, 'type': 'Helper', 'hasCombo': 1, 'price': 480, 'mana_cost': 3, 'item_id': 218},
    'Water Moray': {'DolphinAddress': '80259a86', 'element': 'Water', 'hexCode': 'D9', 'isKeyCard': 0, 'isShopCard': 1, 'number': 219, 'orderInMemory': 210, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 480, 'mana_cost': 3, 'item_id': 219},
    'Earth Moray': {'DolphinAddress': '80259a9a', 'element': 'Earth', 'hexCode': 'DA', 'isKeyCard': 0, 'isShopCard': 1, 'number': 220, 'orderInMemory': 211, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 480, 'mana_cost': 3, 'item_id': 220},
    'Ryuhi': {'DolphinAddress': '80259522', 'element': 'Wood', 'hexCode': '94', 'isKeyCard': 0, 'isShopCard': 0, 'number': 221, 'orderInMemory': 147, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 16, 'item_id': 221},
    'Demon Swordsman': {'DolphinAddress': '8025959a', 'element': 'Earth', 'hexCode': '9A', 'isKeyCard': 0, 'isShopCard': 0, 'number': 222, 'orderInMemory': 153, 'rarity': 7, 'type': 'Weapon', 'hasCombo': 0, 'price': 0, 'mana_cost': 10, 'item_id': 222},
    'Ice Skeleton': {'DolphinAddress': '80259892', 'element': 'Water', 'hexCode': 'C0', 'isKeyCard': 0, 'isShopCard': 0, 'number': 223, 'orderInMemory': 188, 'rarity': 8, 'type': 'Independent', 'hasCombo': 1, 'price': 0, 'mana_cost': 18, 'item_id': 223},
    'Sacred Umpire': {'DolphinAddress': '80259bb2', 'element': 'Mech', 'hexCode': 'E8', 'isKeyCard': 0, 'isShopCard': 0, 'number': 224, 'orderInMemory': 224, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 12, 'item_id': 224},
    'Emperor': {'DolphinAddress': '802594be', 'element': 'Neutral', 'hexCode': '8f', 'isKeyCard': 0, 'isShopCard': 0, 'number': 225, 'orderInMemory': 142, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 10, 'item_id': 225},
}

lost_kingdoms_2_key_items = {
    "Red Key": {"item_id": 10001},
    "Blue Key": {"item_id": 10002},
    "Green Key": {"item_id": 10003},
    "Fossil Head": {"item_id": 10004},
    "Fossil Torso": {"item_id": 10005},
    "Fossil Tail": {"item_id": 10006},
    "Fossil Rt Wing": {"item_id": 10007},
    "Fossil Lt Wing": {"item_id": 10008},
    "Fossil Rt Arm": {"item_id": 10009},
    "Fossil Lt Arm": {"item_id": 10010},
    "Fossil Rt Leg": {"item_id": 10011},
    "Fossil Lt Leg": {"item_id": 10012},
    "Bottle": {"item_id": 10013},
    "Black Liquid": {"item_id": 10014},
    "Mysterious Key": {"item_id": 10015},
    "Blade of Skill": {"item_id": 10016},
    "Blade of Power": {"item_id": 10017},
    "Blade of Wisdom": {"item_id": 10018},
    "Blade of Time": {"item_id": 10019},
    "Jewel of Alanjeh": {"item_id": 10020},
    "Eno Runestone": {"item_id": 10021},
    "Oht Runestone": {"item_id": 10022},
    "Elise Runestone": {"item_id": 10023},
    "Olf Runestone": {"item_id": 10024},
    "Ebin Runestone": {"item_id": 10025},
    "Keil Runestone": {"item_id": 10026},
    "Nebeth Runestone": {"item_id": 10027},
    "Stone of Sealing": {"item_id": 10028},
    "Castle Gate Key": {"item_id": 10029},
    "Key to Fountain": {"item_id": 10030},
}

lostkingdoms_2_custom_prices = {
    "Jack-O-Lantern": {"price": 1000},
    "Great Turtle": {"price": 8000},
    "Birdman": {"price": 1500},
    "Blue Dragon": {"price": 8000},
    "Golden Phoenix": {"price": 8000},
    "White Tiger": {"price": 8000},
    "God of Destruction": {"price": 9999},
    "Doppelganger": {"price": 9999},
    "Fafnir": {"price": 6000},
    "Hell Hound": {"price": 1200},
    "Rabandos": {"price": 3500},
    "Uroboros": {"price": 4500},
    "Sekmet": {"price": 3000},
    "Stone Golem": {"price": 2000},
    "Talos": {"price": 3000},
    "Crystal Magic": {"price": 3000},
    "Pegasus": {"price": 2500},
    "Ryuhi": {"price": 3000},
    "Demon Swordsman": {"price": 2000},
    "Ice Skeleton": {"price": 5000},
    "Sacred Umpire": {"price": 5000},
    "Emperor": {"price": 7000},
    "Sleipnir": {"price": 3500},
    "Pazuzu": {"price": 4000},
}

lost_kingdoms_2_flying_cards = ["Baba Yaga", "Birdman", "Garuda", "Wyvern", "Pazuzu"]
lost_kingdoms_2_jumping_cards = ["Hell Hound", "Cerberus", "Centaur"]
#lost_kingdoms_2_smashing_cards = ["Stone Golem", "Baba Yaga", "Talos", "CircaSaurus", "Devata", "Pazuzu", "Chariobot"]
#lost_kingdoms_2_stationary_cards = ["Dark Treant", "King Mandragora", "Rheebus", "Fairy", "Treant", "Gravity Pillar",
#                                    "Coal Treant", "Vampire Bush", "Mandragora", "Decoy Pillar", "Maelstrom", "Siren",
#                                    "MechaPult","Catoblepas","Myconid","Wood Elemental","Fire Elemental","Water Elemental",
#                                    "Kitty Trap", "Will 'o wisp", "Great Turtle", "Global Bust", "Super Pumper",
#                                    "AcidBot", "Claws-R-Us", "Earth Elemental", "Fire Moray", "Water Moray", "Earth Moray"]


for key in lost_kingdoms_2_cards:
    lost_kingdoms_2_items[key] = {}
    lost_kingdoms_2_items[key]["Type"] = "Card"
    lost_kingdoms_2_items[key]["Amount"] = 1
    lost_kingdoms_2_items[key]["item_id"] = lost_kingdoms_2_cards[key]["item_id"]

for key in lost_kingdoms_2_key_items:
    lost_kingdoms_2_items[key] = {}
    lost_kingdoms_2_items[key]["Type"] = "Key Item"
    lost_kingdoms_2_items[key]["Amount"] = 1
    lost_kingdoms_2_items[key]["item_id"] = lost_kingdoms_2_key_items[key]["item_id"]

lost_kingdoms_2_items["Magic Boosters"] = {"Type": "Magic Boosters", "Amount": 1, "item_id": 20001}
lost_kingdoms_2_items["Red Fairy"] = {"Type": "Red Fairy", "Amount": 100, "item_id": 20002}
lost_kingdoms_2_items["Progressive Player Level"] = {"Type": "Progressive Player Level", "Amount": 19, "item_id": 20003}
lost_kingdoms_2_items["Progressive Attribute Proficiency: Fire"] = {"Type": "Progressive Attribute Proficiency", "Amount": 5, "item_id": 20004}
lost_kingdoms_2_items["Progressive Attribute Proficiency: Water"] = {"Type": "Progressive Attribute Proficiency", "Amount": 5, "item_id": 20005}
lost_kingdoms_2_items["Progressive Attribute Proficiency: Earth"] = {"Type": "Progressive Attribute Proficiency", "Amount": 5, "item_id": 20006}
lost_kingdoms_2_items["Progressive Attribute Proficiency: Wood"] = {"Type": "Progressive Attribute Proficiency", "Amount": 5, "item_id": 20007}
lost_kingdoms_2_items["Progressive Attribute Proficiency: Neutral"] = {"Type": "Progressive Attribute Proficiency", "Amount": 7, "item_id": 20008}
lost_kingdoms_2_items["Progressive Attribute Proficiency: Mech"] = {"Type": "Progressive Attribute Proficiency", "Amount": 7, "item_id": 20009}

lost_kingdoms_2_level_unlocks = {
    #"Nobleman's Residence Unlock": { "RAMAddress": "8025dc0e", "levelID": 1, "item_id": 30000},
    "Bhashea High Road Unlock": { "RAMAddress": "8025dc4e", "levelID": 2, "item_id": 30001},
    "Isamat Urbur Unlock": { "RAMAddress": "8025e0ce", "levelID": 20, "item_id": 30002},
    "Kendarie Fortress Unlock": { "RAMAddress": "8025dcce", "levelID": 4, "item_id": 30003},
    "Kadishu Unlock": { "RAMAddress": "8025dc8e", "levelID": 3, "item_id": 30004},
    "Bhashea Castle Unlock": { "RAMAddress": "8025e10e", "levelID": 21, "item_id": 30005},
    "Kadishu Shop Unlock": { "RAMAddress": "8025e60e", "levelID": 41, "item_id": 30006},
    "Fairy House Unlock": { "RAMAddress": "8025e5ce", "levelID": 40, "item_id": 30007},
    "Gromtull Desert Unlock": { "RAMAddress": "8025e14e", "levelID": 22, "item_id": 30008},
    "Runestone Caverns - Upper Chambers Unlock": { "RAMAddress": "8025dd0e", "levelID": 5, "item_id": 30009},
    "Runestone Caverns - Lower Chambers Unlock": { "RAMAddress": "8025dd4e", "levelID": 6, "item_id": 30010},
    "Ruldo Forest Unlock": { "RAMAddress": "8025dd8e", "levelID": 7, "item_id": 30011},
    "Sacred Battle Arena 1 Unlock": { "RAMAddress": "8025e18e", "levelID": 23, "item_id": 30012},
    "Sacred Battle Arena 2 Unlock": { "RAMAddress": "8025e1ce", "levelID": 24, "item_id": 30013},
    "Fossil Boneyard Unlock": { "RAMAddress": "8025e00e", "levelID": 17, "item_id": 30014},
    "Sarvan Unlock": { "RAMAddress": "8025ddce", "levelID": 8, "item_id": 30015},
    "Holzogh Town Unlock": { "RAMAddress": "8025de0e", "levelID": 9, "item_id": 30016},
    "Plains of Rowahl Unlock": { "RAMAddress": "8025de4e", "levelID": 10, "item_id": 30017},
    "Alanjeh Castle Unlock": { "RAMAddress": "8025de8e", "levelID": 11, "item_id": 30018},
    "Royal Tower, Lower Unlock": { "RAMAddress": "8025dece", "levelID": 18, "item_id": 30019},
    "Royal Tower, Middle Unlock": { "RAMAddress": "8025df8e", "levelID": 15, "item_id": 30020},
    "Royal Tower, Upper Unlock": { "RAMAddress": "8025dfce", "levelID": 16, "item_id": 30021},
    "Krasheen Mountains Unlock": { "RAMAddress": "8025df0e", "levelID": 13, "item_id": 30022},
    "Grenfoel Cathedral Unlock": { "RAMAddress": "8025df4e", "levelID": 14, "item_id": 30023},
    "Temple of Sharacia Unlock": { "RAMAddress": "8025e28e", "levelID": 27, "item_id": 30024},
    "Grenfoel Cathedral Shop Unlock": { "RAMAddress": "8025e64e", "levelID": 42, "item_id": 30025},
    "Obenoix Gorge Unlock": { "RAMAddress": "8025e20e", "levelID": 25, "item_id": 30026},
}

for key in lost_kingdoms_2_level_unlocks:
    lost_kingdoms_2_items[key] = {}
    lost_kingdoms_2_items[key]["Type"] = "Level Unlock"
    lost_kingdoms_2_items[key]["Amount"] = 1
    lost_kingdoms_2_items[key]["item_id"] = lost_kingdoms_2_level_unlocks[key]["item_id"]