from typing import NamedTuple, Optional, List
from BaseClasses import Location, Region


class LK2LocationData(NamedTuple):
    id: int = 0

class LK2Location(Location):
    game = "Lost Kingdoms II"

    def __init__(self, player: int, name: str, parent: Region, data: LK2LocationData):
        if data is not None:
            super().__init__(player, name, data.id, parent)
        else:
            super().__init__(player, name, None, parent)

        self.region = parent.name
        self.data = data

lost_kingdoms_2_chests = {
    "NR - basement chest 1": {'level': "Nobleman's Residence", 'cardName': 'Dark Raven', 'isoAddress': '6D3FDB9', 'missable': 0, 'RAMAddress': '8025dc12', 'type': 'Chest', 'bitOffset': 1},
    "NR - basement chest 2": {'level': "Nobleman's Residence", 'cardName': 'Scythe Beast', 'isoAddress': '6D3FE79', 'missable': 0, 'RAMAddress': '8025dc12', 'type': 'Chest', 'bitOffset': 2},
    "BHR - chest near horses": {'level': 'Bhashea High Road', 'cardName': 'Porcupig', 'isoAddress': '729BDF9', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Chest', 'bitOffset': 11},
    "BHR - card throw challenge": {'level': 'Bhashea High Road', 'cardName': 'Elephant', 'isoAddress': '72A0B9F', 'missable': 1, 'RAMAddress': '8025dc50', 'type': 'Chest', 'bitOffset': 3},
    "BHR - chest near overlook": {'level': 'Bhashea High Road', 'cardName': 'Man Trap', 'isoAddress': '7299BD9', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Chest', 'bitOffset': 10},
    "BHR - chest near deck point": {'level': 'Bhashea High Road', 'cardName': 'Red Lizard', 'isoAddress': '729AD19', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Chest', 'bitOffset': 9},
    "BHR - jump/flight chest": {'level': 'Bhashea High Road', 'cardName': 'Golden Porcupig', 'isoAddress': '729C3F9', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Chest', 'bitOffset': 12},
    "BHR - flight chest": {'level': 'Bhashea High Road', 'cardName': 'Water Moray', 'isoAddress': '729B919', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Chest', 'bitOffset': 13},
    "Kadishu - chest outside town wall": {'level': 'Kadishu', 'cardName': 'Rock Hagan', 'isoAddress': '778E1D9', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Chest', 'bitOffset': 1},
    "Kadishu - chest up small steps": {'level': 'Kadishu', 'cardName': 'Demon Hound', 'isoAddress': '778DA59', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Chest', 'bitOffset': 4},
    "Kadishu - alleyway chest": {'level': 'Kadishu', 'cardName': 'Dragonoid', 'isoAddress': '778E119', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Chest', 'bitOffset': 5},
    "Kadishu - chest 4": {'level': 'Kadishu', 'cardName': 'Flayer Spawn', 'isoAddress': '778DB19', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Chest', 'bitOffset': 3},
    "Kadishu - chest by dog": {'level': 'Kadishu', 'cardName': 'Demon Hound', 'isoAddress': '778DBD9', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Chest', 'bitOffset': 2},
    "Kadishu - chest near monument": {'level': 'Kadishu', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Chest', 'bitOffset': 11},
    "Kadishu - garbage collection 1": {'level': 'Kadishu', 'cardName': 'Leprechaun', 'isoAddress': '7793797', 'missable': 0, 'RAMAddress': '8025dc90', 'type': 'Chest', 'bitOffset': 9},
    "Kadishu - garbage collection 2": {'level': 'Kadishu', 'cardName': 'Super Scrubber', 'isoAddress': '7793A5F', 'missable': 0, 'RAMAddress': '8025dc90', 'type': 'Chest', 'bitOffset': 10},
    "Kadishu - garbage collection 3": {'level': 'Kadishu', 'cardName': 'Larval Fly', 'isoAddress': '77938FB', 'missable': 0, 'RAMAddress': '8025dc90', 'type': 'Chest', 'bitOffset': 11},
    "BC - central room chest 1": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Chest', 'bitOffset': 5},
    "BC - west room chest": {'level': 'Bhashea Castle', 'cardName': 'Mole Monster', 'isoAddress': 'C4F2F19', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Chest', 'bitOffset': 7},
    "BC - throne chest": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Chest', 'bitOffset': 4},
    "BC - east jump chest": {'level': 'Bhashea Castle', 'cardName': 'Lamassu', 'isoAddress': 'C4F2A99', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Chest', 'bitOffset': 1},
    "BC - east stairway chest": {'level': 'Bhashea Castle', 'cardName': 'Gorgon', 'isoAddress': 'C4F2D99', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Chest', 'bitOffset': 6},
    "BC - break through wall chest": {'level': 'Bhashea Castle', 'cardName': 'Daidarapochi', 'isoAddress': 'C4F2B59', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Chest', 'bitOffset': 2},
    "BC - west stairway chest": {'level': 'Bhashea Castle', 'cardName': 'Death', 'isoAddress': 'C4F2C19', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Chest', 'bitOffset': 3},
    "GD - chest by backpack": {'level': 'Gromtull Desert', 'cardName': 'Venus Spider', 'isoAddress': 'C983379', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 7},
    "GD - cave chest 1": {'level': 'Gromtull Desert', 'cardName': 'Mummy', 'isoAddress': 'C982FB9', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 2},
    "GD - cave chest 2": {'level': 'Gromtull Desert', 'cardName': 'Pixie', 'isoAddress': 'C983079', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 3},
    "GD - cave chest 3": {'level': 'Gromtull Desert', 'cardName': 'Mummy', 'isoAddress': 'C982EF9', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 1},
    "GD - chest by oil": {'level': 'Gromtull Desert', 'cardName': 'Evil Eye', 'isoAddress': 'C9832B9', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 6},
    "GD - jarvi cave chest 1": {'level': 'Gromtull Desert', 'cardName': 'Running Bird', 'isoAddress': 'C983139', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 4},
    "GD - jarvi cave chest 2": {'level': 'Gromtull Desert', 'cardName': 'Sand Beetle', 'isoAddress': 'C9831F9', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 5},
    "GD - flight chest": {'level': 'Gromtull Desert', 'cardName': 'Bum Hagan', 'isoAddress': 'C983439', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 8},
    "KF - chest 1": {'level': 'Kendarie Fortress', 'cardName': 'Mandragora', 'isoAddress': '7C12519', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Chest', 'bitOffset': 1},
    "KF - chest 2": {'level': 'Kendarie Fortress', 'cardName': 'Aggressor GL2', 'isoAddress': '7C154B9', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Chest', 'bitOffset': 3},
    "KF - chest behind green door": {'level': 'Kendarie Fortress', 'cardName': 'Death', 'isoAddress': '7C153F9', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Chest', 'bitOffset': 2},
    "KF - chest 4": {'level': 'Kendarie Fortress', 'cardName': 'Venom Lizard', 'isoAddress': '7C156F9', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Chest', 'bitOffset': 5},
    "KF - chest 5": {'level': 'Kendarie Fortress', 'cardName': 'MechaPult', 'isoAddress': '7C15579', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Chest', 'bitOffset': 4},
    "KF - flight chest": {'level': 'Kendarie Fortress', 'cardName': 'UberBomberBot', 'isoAddress': '7C14979', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Chest', 'bitOffset': 6},
    "RC-UC - chest 1": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Dark Raven', 'isoAddress': '7FC89F9', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 13},
    "RC-UC - chest 2": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Land Shark', 'isoAddress': '7FC8579', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 5},
    "RC-UC - talk to Sol": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Stone Golem', 'isoAddress': '7FC9CD7', 'missable': 1, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 0},
    "RC-UC - lower chest 1": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Blood Bush', 'isoAddress': '7FC8639', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 7},
    "RC-UC - lower chest 2": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Undine', 'isoAddress': '7FC83F9', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 3},
    "RC-UC - chest behind ice 1": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Gorgon', 'isoAddress': '7FC86F9', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 6},
    "RC-UC - chest behind ice 2": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Land Shark', 'isoAddress': '7FC84B9', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 4},
    "RC-UC - dragon chest 1": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Baba Yaga', 'isoAddress': '7FC8339', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 1},
    "RC-UC - dragon chest 2": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Witchlette', 'isoAddress': '7FC8279', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 2},
    "RC-LC - chest 1": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Flayer Spawn', 'isoAddress': '843A839', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 1},
    "RC-LC - chest 2": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Basilisk', 'isoAddress': '843B079', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 7},
    "RC-LC - low water chest": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Maelstrom', 'isoAddress': '843A9B9', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 3},
    "RC-LC - high water chest 1": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Yowie', 'isoAddress': '843A8F9', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 2},
    "RC-LC - high water chest flight": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Maelstrom', 'isoAddress': '843AB39', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 4},
    "RC-LC - chest 6": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Flayer Spawn', 'isoAddress': '843ABF9', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 6},
    "RC-LC - chest 7": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Flayer Spawn', 'isoAddress': '843ACB9', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 5},
    "RF - chest 1": {'level': 'Ruldo Forest', 'cardName': 'Mandragora', 'isoAddress': '885D979', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Chest', 'bitOffset': 1},
    "RF - chest 2": {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '885D979', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Chest', 'bitOffset': 2},
    "RF - chest 3": {'level': 'Ruldo Forest', 'cardName': 'Dryad', 'isoAddress': '885DD39', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Chest', 'bitOffset': 3},
    "RF - jump chest": {'level': 'Ruldo Forest', 'cardName': 'Elf', 'isoAddress': '885DDF9', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Chest', 'bitOffset': 4},
    "RF - flight/jump chest": {'level': 'Ruldo Forest', 'cardName': 'Night Mare', 'isoAddress': '885DEB9', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Chest', 'bitOffset': 5},
    "RF - cockatrice chest 1": {'level': 'Ruldo Forest', 'cardName': 'Demon Hound', 'isoAddress': '885E039', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Chest', 'bitOffset': 7},
    "RF - cockatrice chest 2": {'level': 'Ruldo Forest', 'cardName': 'Raflesia', 'isoAddress': '885DF79', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Chest', 'bitOffset': 6},
    "SBA1 - defeat Lich": {'level': 'Sacred Battle Arena 1', 'cardName': 'Lich', 'isoAddress': 'CDB809B', 'missable': 1, 'RAMAddress': '8025e190', 'type': 'Chest', 'bitOffset': 3},
    "SBA1 - defeat Nueh": {'level': 'Sacred Battle Arena 1', 'cardName': 'Nueh', 'isoAddress': 'CDB78E3', 'missable': 1, 'RAMAddress': '8025e190', 'type': 'Chest', 'bitOffset': 1},
    "SBA1 - defeat Gemini": {'level': 'Sacred Battle Arena 1', 'cardName': 'Gemini', 'isoAddress': 'CDB7CBF', 'missable': 1, 'RAMAddress': '8025e190', 'type': 'Chest', 'bitOffset': 2},
    "SBA1 - defeat Kraken": {'level': 'Sacred Battle Arena 1', 'cardName': 'Kraken', 'isoAddress': 'CDB8477', 'missable': 1, 'RAMAddress': '8025e190', 'type': 'Chest', 'bitOffset': 4},
    "SBA2 - defeat Rabandos": {'level': 'Sacred Battle Arena 2', 'cardName': 'Rabandos', 'isoAddress': 'D293F83', 'missable': 1, 'RAMAddress': '8025e1d0', 'type': 'Chest', 'bitOffset': 3},
    "SBA2 - defeat Helena": {'level': 'Sacred Battle Arena 2', 'cardName': 'Ice Skeleton', 'isoAddress': 'D2943DF', 'missable': 1, 'RAMAddress': '8025e1d0', 'type': 'Chest', 'bitOffset': 4},
    "SBA2 - defeat Astrobot": {'level': 'Sacred Battle Arena 2', 'cardName': 'AstroBot', 'isoAddress': 'D29375B', 'missable': 1, 'RAMAddress': '8025e1d0', 'type': 'Chest', 'bitOffset': 1},
    "SBA2 - defeat Leod": {'level': 'Sacred Battle Arena 2', 'cardName': 'Sacred Umpire', 'isoAddress': 'D293B6F', 'missable': 1, 'RAMAddress': '8025e1d0', 'type': 'Chest', 'bitOffset': 2},
    "SBA2 - defeat Thalnos": {'level': 'Sacred Battle Arena 2', 'cardName': 'Sekmet', 'isoAddress': 'D2947FF', 'missable': 1, 'RAMAddress': '8025e1d0', 'type': 'Chest', 'bitOffset': 5},
    "SBA2 - defeat Katia": {'level': 'Sacred Battle Arena 2', 'cardName': 'Doppelganger', 'isoAddress': 'D294C3F', 'missable': 1, 'RAMAddress': '8025e1d0', 'type': 'Chest', 'bitOffset': 6},
    "FB - chest 1": {'level': 'Fossil Boneyard', 'cardName': 'Hell Hound', 'isoAddress': 'B45E8C9', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 1},
    "FB - chest behind cultist": {'level': 'Fossil Boneyard', 'cardName': 'Gnome', 'isoAddress': 'B45E939', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 8},
    "FB - chest 3": {'level': 'Fossil Boneyard', 'cardName': 'Hell Hound', 'isoAddress': 'B45E9F9', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 3},
    "FB - chest 4": {'level': 'Fossil Boneyard', 'cardName': 'Hell Hound', 'isoAddress': 'B45E7B9', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 6},
    "FB - chest 5": {'level': 'Fossil Boneyard', 'cardName': 'Caterpoker', 'isoAddress': 'B45EAB9', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 4},
    "FB - chest 6": {'level': 'Fossil Boneyard', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 5},
    "FB - chest 7": {'level': 'Fossil Boneyard', 'cardName': 'Dark Raven', 'isoAddress': 'B45EC39', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 7},
    "FB - flight chest 1": {'level': 'Fossil Boneyard', 'cardName': 'Catoblepas', 'isoAddress': 'B45ECF9', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 9},
    "FB - flight chest 2": {'level': 'Fossil Boneyard', 'cardName': 'Amber Dragon', 'isoAddress': 'B45EDB9', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 10},
    "FB - zombie dragon chest": {'level': 'Fossil Boneyard', 'cardName': 'Zombie Dragon', 'isoAddress': 'B45CB99', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 2},
    "Sarvan - jump chest": {'level': 'Sarvan', 'cardName': 'Marid', 'isoAddress': '8CCC9D9', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 3},
    "Sarvan - chest 1": {'level': 'Sarvan', 'cardName': 'Decoy Pillar', 'isoAddress': '8CCCAF9', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 4},
    "Sarvan - chest 2": {'level': 'Sarvan', 'cardName': 'Jade Giant', 'isoAddress': '8CCCBB9', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 5},
    "Sarvan - chest 3": {'level': 'Sarvan', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 6},
    "Sarvan - caged chest": {'level': 'Sarvan', 'cardName': 'Lucky Lion', 'isoAddress': '8CCC859', 'missable': 1, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 1},
    "Sarvan - chest 4": {'level': 'Sarvan', 'cardName': 'Mandragora', 'isoAddress': '8CCCDF9', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 8},
    "Sarvan - chest 5": {'level': 'Sarvan', 'cardName': 'Gold Butterfly', 'isoAddress': '8CCCD39', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 7},
    "Sarvan - caged chest 2": {'level': 'Sarvan', 'cardName': 'Hobgoblin', 'isoAddress': '8CCC919', 'missable': 1, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 2},
    "Sarvan - puzzle chest": {'level': 'Sarvan', 'cardName': 'Devata', 'isoAddress': '8CCE0B9', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 9},
    "HT - chest 1": {'level': 'Holzogh Town', 'cardName': 'Red Lizard', 'isoAddress': '920A899', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 3},
    "HT - chest 2": {'level': 'Holzogh Town', 'cardName': 'Efreet', 'isoAddress': '920AA19', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 7},
    "HT - chest 3": {'level': 'Holzogh Town', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 4},
    "HT - chest 4": {'level': 'Holzogh Town', 'cardName': 'Coal Treant', 'isoAddress': '920A7D9', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 1},
    "HT - chest 5": {'level': 'Holzogh Town', 'cardName': 'Salamander', 'isoAddress': '920AB99', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 6},
    "HT - chest 6": {'level': 'Holzogh Town', 'cardName': 'Popgun Charlie', 'isoAddress': '920AAD9', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 5},
    "HT - chest 7": {'level': 'Holzogh Town', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 9},
    "HT - fountain card": {'level': 'Holzogh Town', 'cardName': 'Mind Flayer', 'isoAddress': '9209AB9', 'missable': 1, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 2},
    "PoR - chest 1": {'level': 'Plains of Rowahl', 'cardName': 'Devil Plant', 'isoAddress': '96780F9', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 4},
    "PoR - chest 2": {'level': 'Plains of Rowahl', 'cardName': 'Sand Golem', 'isoAddress': '9678219', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 5},
    "PoR - flight chest": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 7},
    "PoR - chest under scrap": {'level': 'Plains of Rowahl', 'cardName': 'Dao', 'isoAddress': '9678CF9', 'missable': 1, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 8},
    "PoR - chest 4": {'level': 'Plains of Rowahl', 'cardName': 'Man Trap', 'isoAddress': '9678519', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 10},
    "PoR - chest 5": {'level': 'Plains of Rowahl', 'cardName': 'Night Mare', 'isoAddress': '9678459', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 9},
    "PoR - chest 6": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 2},
    "PoR - chest 7": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 3},
    "PoR - flight chest 2": {'level': 'Plains of Rowahl', 'cardName': 'King Mandragora', 'isoAddress': '96782D9', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 6},
    "PoR - GoD card": {'level': 'Plains of Rowahl', 'cardName': 'God of Destruction', 'isoAddress': '967A757', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': -1},
    "AC - chest 2": {'level': 'Alanjeh Castle', 'cardName': 'AcidBot', 'isoAddress': '9A83399', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Chest', 'bitOffset': 3},
    "AC - chest 3": {'level': 'Alanjeh Castle', 'cardName': 'Dark Treant', 'isoAddress': '9A832D9', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Chest', 'bitOffset': 2},
    "AC - chest 4": {'level': 'Alanjeh Castle', 'cardName': 'Gizmolizer', 'isoAddress': '9A83699', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Chest', 'bitOffset': 7},
    "AC - chest 5": {'level': 'Alanjeh Castle', 'cardName': 'Fairy', 'isoAddress': '9A83459', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Chest', 'bitOffset': 4},
    "AC - chest 6": {'level': 'Alanjeh Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Chest', 'bitOffset': 5},
    "AC - flight chest": {'level': 'Alanjeh Castle', 'cardName': 'Boom Monkey', 'isoAddress': '9A835D9', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Chest', 'bitOffset': 6},
    "RTL - chest 1": {'level': 'Royal Tower, Lower', 'cardName': 'Carbuncle', 'isoAddress': '9F0DE19', 'missable': 1, 'RAMAddress': '8025ded2', 'type': 'Chest', 'bitOffset': 1},
    "RTL - chest 2": {'level': 'Royal Tower, Lower', 'cardName': 'Sprite', 'isoAddress': '9F0DED9', 'missable': 1, 'RAMAddress': '8025ded2', 'type': 'Chest', 'bitOffset': 2},
    "RTL - chest 3": {'level': 'Royal Tower, Lower', 'cardName': 'Tiger Mage', 'isoAddress': 'B949EB9', 'missable': 1, 'RAMAddress': '8025e052', 'type': 'Chest', 'bitOffset': 1},
    "RTL - flight chest 1": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Chest', 'bitOffset': 3},
    "RTL - flight chest 2": {'level': 'Royal Tower, Lower', 'cardName': 'Puppet Master', 'isoAddress': 'B949F79', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Chest', 'bitOffset': 2},
    "RTL - jump chest 1": {'level': 'Royal Tower, Lower', 'cardName': 'Decoy Pillar', 'isoAddress': 'B94A0F9', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Chest', 'bitOffset': 4},
    "RTL - jump chest 2": {'level': 'Royal Tower, Lower', 'cardName': 'Fire Gargoyle', 'isoAddress': 'B94A1B9', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Chest', 'bitOffset': 5},
    "RTM - chest 1": {'level': 'Royal Tower, Middle', 'cardName': 'Rheebus', 'isoAddress': 'ABD9259', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Chest', 'bitOffset': 3},
    "RTM - chest 2": {'level': 'Royal Tower, Middle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Chest', 'bitOffset': 4},
    "RTM - breakable wall chest 1": {'level': 'Royal Tower, Middle', 'cardName': 'Sphinx', 'isoAddress': 'ABD9139', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Chest', 'bitOffset': 2},
    "RTM - breakable wall chest 2": {'level': 'Royal Tower, Middle', 'cardName': 'Hydra', 'isoAddress': 'ABD9079', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Chest', 'bitOffset': 1},
    "RTM - forcefield chest 1": {'level': 'Royal Tower, Middle', 'cardName': 'Unicorn', 'isoAddress': 'ABD93D9', 'missable': 1, 'RAMAddress': '8025df92', 'type': 'Chest', 'bitOffset': 5},
    "RTM - forcefield chest 2": {'level': 'Royal Tower, Middle', 'cardName': 'Red Dragon', 'isoAddress': 'ABD9499', 'missable': 1, 'RAMAddress': '8025df92', 'type': 'Chest', 'bitOffset': 6},
    "RTU - chest 1": {'level': 'Royal Tower, Upper', 'cardName': 'Wyvern', 'isoAddress': 'B02D5B9', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Chest', 'bitOffset': 1},
    "RTU - chest 2": {'level': 'Royal Tower, Upper', 'cardName': 'Unicorn', 'isoAddress': 'B02D679', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Chest', 'bitOffset': 3},
    "RTU - chest 3": {'level': 'Royal Tower, Upper', 'cardName': 'Spartoi', 'isoAddress': 'B02D739', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Chest', 'bitOffset': 2},
    "KM - black dragon's card": {'level': 'Krasheen Mountains', 'cardName': 'Birdman', 'isoAddress': 'A25D29F', 'missable': 1, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': -1},
    "KM - chest 1": {'level': 'Krasheen Mountains', 'cardName': 'Birdman', 'isoAddress': 'A25AED9', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': 1},
    "KM - chest 2": {'level': 'Krasheen Mountains', 'cardName': 'Charadrius', 'isoAddress': 'A25B059', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': 4},
    "KM - chest 3": {'level': 'Krasheen Mountains', 'cardName': 'Birdman', 'isoAddress': 'A25AE19', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': 2},
    "KM - chest 4": {'level': 'Krasheen Mountains', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': 3},
    "KM - chest 7": {'level': 'Krasheen Mountains', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': 7},
    "KM - chest 5": {'level': 'Krasheen Mountains', 'cardName': 'Acid Dragon', 'isoAddress': 'A25B1D9', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': 5},
    "KM - chest 6": {'level': 'Krasheen Mountains', 'cardName': 'Earth Moray', 'isoAddress': 'A25B119', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': 6},
    "GC - hidden chest 1": {'level': 'Grenfoel Cathedral', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Chest', 'bitOffset': 3},
    "GC - hidden chest 2": {'level': 'Grenfoel Cathedral', 'cardName': 'Vampire', 'isoAddress': 'A72FD39', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Chest', 'bitOffset': 1},
    "GC - hidden chest 3": {'level': 'Grenfoel Cathedral', 'cardName': 'Plague Rat', 'isoAddress': 'A72FDF9', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Chest', 'bitOffset': 2},
    "GC - organ chest 1": {'level': 'Grenfoel Cathedral', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Chest', 'bitOffset': 5},
    "GC - organ chest 2": {'level': 'Grenfoel Cathedral', 'cardName': 'Gravity Pillar', 'isoAddress': 'A72FF79', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Chest', 'bitOffset': 4},
    "ToS - flight chest": {'level': 'Temple of Sharacia', 'cardName': 'Cerberus', 'isoAddress': 'DBBBBD9', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Chest', 'bitOffset': 1},
    "ToS - chest 1": {'level': 'Temple of Sharacia', 'cardName': 'Salamander', 'isoAddress': 'DBBBD59', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Chest', 'bitOffset': 3},
    "ToS - chest 2": {'level': 'Temple of Sharacia', 'cardName': 'Hell Hound', 'isoAddress': 'DBBBC99', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Chest', 'bitOffset': 2},
    "ToS - chest 3": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Chest', 'bitOffset': 4},
    "ToS - chest 4": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Chest', 'bitOffset': 6},
    "ToS - chest 5": {'level': 'Temple of Sharacia', 'cardName': 'Fire Elemental', 'isoAddress': 'DBBC059', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Chest', 'bitOffset': 7},
    "ToS - chest 6": {'level': 'Temple of Sharacia', 'cardName': 'Fire Gargoyle', 'isoAddress': 'DBBBE19', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Chest', 'bitOffset': 5},
    "ToS - help valkyrie": {'level': 'Temple of Sharacia', 'cardName': 'Valkyrie', 'isoAddress': 'DBBE7FD', 'missable': 1, 'RAMAddress': '8025e290', 'type': 'Chest', 'bitOffset': 3},
    "ToS - help ashura": {'level': 'Temple of Sharacia', 'cardName': 'Ashura', 'isoAddress': 'DBBE4A7', 'missable': 1, 'RAMAddress': '8025e290', 'type': 'Chest', 'bitOffset': 1},
    "IU - chest 1": {'level': 'Isamat Urbur', 'cardName': 'Green Dragon', 'isoAddress': 'BFF2A19', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Chest', 'bitOffset': 1},
    "IU - chest 2": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Chest', 'bitOffset': 5},
    "IU - chest 3": {'level': 'Isamat Urbur', 'cardName': 'Succubus', 'isoAddress': 'BFF2B99', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Chest', 'bitOffset': 3},
    "IU - chest 4": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Chest', 'bitOffset': 4},
    "IU - chest 5": {'level': 'Isamat Urbur', 'cardName': 'Incubus', 'isoAddress': 'BFF2AD9', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Chest', 'bitOffset': 2},
    "IU - chest 6": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Chest', 'bitOffset': 6},
    "OG - chest 1": {'level': 'Obenoix Gorge', 'cardName': 'Water Elemental', 'isoAddress': 'D7106D9', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 1},
    "OG - chest 2": {'level': 'Obenoix Gorge', 'cardName': 'Sasquatch', 'isoAddress': 'D710799', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 2},
    "OG - flight chest 1": {'level': 'Obenoix Gorge', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 4},
    "OG - flight chest 2": {'level': 'Obenoix Gorge', 'cardName': 'Crystal Rose', 'isoAddress': 'D710859', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 3},
    "OG - chest 3": {'level': 'Obenoix Gorge', 'cardName': 'Siren', 'isoAddress': 'D710A99', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 6},
    "OG - chest 4": {'level': 'Obenoix Gorge', 'cardName': 'Chameleus', 'isoAddress': 'D7109D9', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 5},
    "OG - chest behind ice": {'level': 'Obenoix Gorge', 'cardName': 'Thanatos', 'isoAddress': 'D710D99', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 13},
    "OG - flight chest 3": {'level': 'Obenoix Gorge', 'cardName': 'Hydra', 'isoAddress': 'D710B59', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 7},
    "FH - collect 1 fairy": {'level': 'Fairy House', 'cardName': 'Tumble Chick', 'isoAddress': '183A31', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 1},
    "FH - collect 10 fairies": {'level': 'Fairy House', 'cardName': 'Carbuncle', 'isoAddress': '183A33', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 10},
    "FH - collect 20 fairies": {'level': 'Fairy House', 'cardName': 'Berserker', 'isoAddress': '183A35', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 20},
    "FH - collect 30 fairies": {'level': 'Fairy House', 'cardName': 'Fire Moray', 'isoAddress': '183A37', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 30},
    "FH - collect 50 fairies": {'level': 'Fairy House', 'cardName': 'Psycho Dice', 'isoAddress': '183A39', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 50},
    "FH - collect 70 fairies": {'level': 'Fairy House', 'cardName': 'Whip Worm', 'isoAddress': '183A3B', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 70},
    "FH - collect 80 fairies": {'level': 'Fairy House', 'cardName': 'Global Bust', 'isoAddress': '183A3D', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 80},
    "FH - collect 90 fairies": {'level': 'Fairy House', 'cardName': 'Crystal Magic', 'isoAddress': '183A3F', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 90},
    "FH - collect 100 fairies": {'level': 'Fairy House', 'cardName': 'Circasaurus', 'isoAddress': '183A41', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 100}
}

lost_kingdoms_2_red_fairies = {
    "NR - Red Fairy sculpture": {'level': "Nobleman's Residence", 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc12', 'type': 'Red Fairy', 'bitOffset': 6},
    "NR - Red Fairy central": {'level': "Nobleman's Residence", 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc12', 'type': 'Red Fairy', 'bitOffset': 7},
    "NR - Red Fairy office": {'level': "Nobleman's Residence", 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc12', 'type': 'Red Fairy', 'bitOffset': 5},
    "BHR - Red Fairy across bridge": {'level': 'Bhashea High Road', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Red Fairy', 'bitOffset': 8},
    "BHR - Red Fairy across bridge in rubble": {'level': 'Bhashea High Road', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Red Fairy', 'bitOffset': 6},
    "BHR - Red Fairy chaos knight": {'level': 'Bhashea High Road', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Red Fairy', 'bitOffset': 7},
    "Kadishu - Red Fairy by dog": {'level': 'Kadishu', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Red Fairy', 'bitOffset': 8},
    "Kadishu - Red Fairy on bridge": {'level': 'Kadishu', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Red Fairy', 'bitOffset': 10},
    "Kadishu - Red Fairy in well": {'level': 'Kadishu', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Red Fairy', 'bitOffset': 6},
    "Kadishu - Red Fairy by fountain": {'level': 'Kadishu', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Red Fairy', 'bitOffset': 7},
    "Kadishu - Red Fairy in alley": {'level': 'Kadishu', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Red Fairy', 'bitOffset': 9},
    "BC - Red Fairy near start": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Red Fairy', 'bitOffset': 12},
    "BC - Red Fairy central room": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Red Fairy', 'bitOffset': 11},
    "BC - Red Fairy rubble": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Red Fairy', 'bitOffset': 9},
    "BC - Red Fairy throne": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Red Fairy', 'bitOffset': 13},
    "BC - Red Fairy wall break rubble": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Red Fairy', 'bitOffset': 10},
    "GD - Red Fairy 1": {'level': 'Gromtull Desert', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Red Fairy', 'bitOffset': 10},
    "GD - Red Fairy 2": {'level': 'Gromtull Desert', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Red Fairy', 'bitOffset': 11},
    "GD - Red Fairy jump": {'level': 'Gromtull Desert', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Red Fairy', 'bitOffset': 12},
    "GD - Red Fairy Jarvi 1": {'level': 'Gromtull Desert', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Red Fairy', 'bitOffset': 13},
    "GD - Red Fairy Jarvi 2": {'level': 'Gromtull Desert', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Red Fairy', 'bitOffset': 9},
    "KF - Red Fairy at start": {'level': 'Kendarie Fortress', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Red Fairy', 'bitOffset': 10},
    "KF - Red Fairy fly across": {'level': 'Kendarie Fortress', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Red Fairy', 'bitOffset': 9},
    "KF - Red Fairy past blue gate": {'level': 'Kendarie Fortress', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Red Fairy', 'bitOffset': 7},
    "KF - Red Fairy near Mechapult": {'level': 'Kendarie Fortress', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Red Fairy', 'bitOffset': 8},
    "RC-UC - Red Fairy near start": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Red Fairy', 'bitOffset': 12},
    "RC-UC - Red Fairy near sluice gate": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Red Fairy', 'bitOffset': 8},
    "RC-UC - Red Fairy near dragon": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Red Fairy', 'bitOffset': 9},
    "RC-UC - Red Fairy near golem": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Red Fairy', 'bitOffset': 10},
    "RC-UC - Red Fairy near Sol": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Red Fairy', 'bitOffset': 11},
    "RC-LC - Red Fairy near start": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 8},
    "RC-LC - Red Fairy in rubble": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 10},
    "RC-LC - Red Fairy low water": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 11},
    "RC-LC - Red Fairy on stairs": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 9},
    "RF Red Fairy at start": {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Red Fairy', 'bitOffset': 8},
    "RF Red Fairy at start 2": {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Red Fairy', 'bitOffset': 12},
    "RF Red Fairy in tree": {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Red Fairy', 'bitOffset': 11},
    "RF Red Fairy near machine": {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Red Fairy', 'bitOffset': 9},
    "RF Red past Cockatrice": {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Red Fairy', 'bitOffset': 10},
    "SBA1 - Red Fairy 1": {'level': 'Sacred Battle Arena 1', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e192', 'type': 'Red Fairy', 'bitOffset': 2},
    "SBA1 - Red Fairy 2": {'level': 'Sacred Battle Arena 1', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e192', 'type': 'Red Fairy', 'bitOffset': 1},
    "SBA1 - Red Fairy 3": {'level': 'Sacred Battle Arena 1', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e192', 'type': 'Red Fairy', 'bitOffset': 3},
    "SBA2 - Red Fairy hallway": {'level': 'Sacred Battle Arena 2', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e1d2', 'type': 'Red Fairy', 'bitOffset': 2},
    "SBA2 - Red Fairy machines": {'level': 'Sacred Battle Arena 2', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e1d2', 'type': 'Red Fairy', 'bitOffset': 3},
    "SBA2 - Red Fairy Queen Katia": {'level': 'Sacred Battle Arena 2', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e1d2', 'type': 'Red Fairy', 'bitOffset': 1},
    "FB - Red Fairy near start": {'level': 'Fossil Boneyard', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 11},
    "FB - Red Fairy near jump pad": {'level': 'Fossil Boneyard', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 12},
    "FB - Red Fairy near 2nd jump pad": {'level': 'Fossil Boneyard', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 13},
    "Sarvan - Red Fairy near start": {'level': 'Sarvan', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 10},
    "Sarvan - Red Fairy under bridge": {'level': 'Sarvan', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 12},
    "Sarvan - Red Fairy magic circle": {'level': 'Sarvan', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 11},
    "HT - Red Fairy near start": {'level': 'Holzogh Town', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 11},
    "HT - Red Fairy stairs": {'level': 'Holzogh Town', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 13},
    "HT - Red Fairy rubble": {'level': 'Holzogh Town', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 10},
    "HT - Red Fairy rubble 2": {'level': 'Holzogh Town', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 14},
    "PoR - Red Fairy near start": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Red Fairy', 'bitOffset': 11},
    "PoR - Red Fairy in catapult": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Red Fairy', 'bitOffset': 12},
    "PoR - Red Fairy in golem": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Red Fairy', 'bitOffset': 13},
    "PoR - Red Fairy past gate": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Red Fairy', 'bitOffset': 14},
    "AC - Red Fairy near start": {'level': 'Alanjeh Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Red Fairy', 'bitOffset': 9},
    "AC - Red Fairy jump": {'level': 'Alanjeh Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Red Fairy', 'bitOffset': 8},
    "AC - Red Fairy end": {'level': 'Alanjeh Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Red Fairy', 'bitOffset': 9},
    "RTL - Red Fairy start": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ded2', 'type': 'Red Fairy', 'bitOffset': 3},
    "RTL - Red Fairy up elevator": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ded2', 'type': 'Red Fairy', 'bitOffset': 4},
    "RTL - Red Fairy over pillar": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Red Fairy', 'bitOffset': 7},
    "RTL - Red Fairy chandelier": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Red Fairy', 'bitOffset': 8},
    "RTL - Red Fairy outside": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Red Fairy', 'bitOffset': 10},
    "RTL - Red Fairy flight": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Red Fairy', 'bitOffset': 9},
    "RTM - Red Fairy near start": {'level': 'Royal Tower, Middle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Red Fairy', 'bitOffset': 7},
    "RTM - Red Fairy hallway": {'level': 'Royal Tower, Middle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Red Fairy', 'bitOffset': 9},
    "RTM - Red Fairy breakable wall 1": {'level': 'Royal Tower, Middle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Red Fairy', 'bitOffset': 8},
    "RTM - Red Fairy breakable wall 2": {'level': 'Royal Tower, Middle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Red Fairy', 'bitOffset': 10},
    "RTU - Red Fairy rubble": {'level': 'Royal Tower, Upper', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Red Fairy', 'bitOffset': 4},
    "RTU - Red Fairy sphinx": {'level': 'Royal Tower, Upper', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Red Fairy', 'bitOffset': 6},
    "RTU - Red Fairy stairs 1": {'level': 'Royal Tower, Upper', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Red Fairy', 'bitOffset': 7},
    "RTU - Red Fairy stairs 2": {'level': 'Royal Tower, Upper', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Red Fairy', 'bitOffset': 5},
    "KM - Red Fairy cave 1": {'level': 'Krasheen Mountains', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Red Fairy', 'bitOffset': 9},
    "KM - Red Fairy bridge": {'level': 'Krasheen Mountains', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Red Fairy', 'bitOffset': 8},
    "KM - Red Fairy broken bridge": {'level': 'Krasheen Mountains', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Red Fairy', 'bitOffset': 10},
    "KM - Red Fairy broken bridge 2": {'level': 'Krasheen Mountains', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Red Fairy', 'bitOffset': 11},
    "GC - Red Fairy near organ": {'level': 'Grenfoel Cathedral', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Red Fairy', 'bitOffset': 6},
    "GC - Red Fairy right side": {'level': 'Grenfoel Cathedral', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Red Fairy', 'bitOffset': 9},
    "GC - Red Fairy hidden 1": {'level': 'Grenfoel Cathedral', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Red Fairy', 'bitOffset': 8},
    "GC - Red Fairy hidden 2": {'level': 'Grenfoel Cathedral', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Red Fairy', 'bitOffset': 10},
    "GC - Red Fairy library": {'level': 'Grenfoel Cathedral', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Red Fairy', 'bitOffset': 7},
    "ToS - Red Fairy near start": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Red Fairy', 'bitOffset': 8},
    "ToS - Red Fairy near start 2": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Red Fairy', 'bitOffset': 9},
    "ToS - Red Fairy up left stairs": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Red Fairy', 'bitOffset': 13},
    "ToS - Red Fairy up right side": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Red Fairy', 'bitOffset': 10},
    "ToS - Red Fairy rubble": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Red Fairy', 'bitOffset': 12},
    "ToS - Red Fairy Valkyrie": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Red Fairy', 'bitOffset': 11},
    "IU - Red Fairy near start": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Red Fairy', 'bitOffset': 10},
    "IU - Red Fairy east room": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Red Fairy', 'bitOffset': 8},
    "IU - Red Fairy northeast": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Red Fairy', 'bitOffset': 9},
    "IU - Red Fairy southwest": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Red Fairy', 'bitOffset': 7},
    "OG - Red Fairy near start": {'level': 'Obenoix Gorge', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Red Fairy', 'bitOffset': 8},
    "OG - Red Fairy in tree": {'level': 'Obenoix Gorge', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Red Fairy', 'bitOffset': 10},
    "OG - Red Fairy near flight": {'level': 'Obenoix Gorge', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Red Fairy', 'bitOffset': 9},
    "OG - Red Fairy in tree 2": {'level': 'Obenoix Gorge', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Red Fairy', 'bitOffset': 11},
    "OG - Red Fairy near ship": {'level': 'Obenoix Gorge', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Red Fairy', 'bitOffset': 12}
}
lost_kingdoms_2_key_locations = {
    "Red Key": {'level': 'Kendarie Fortress', 'type': 'Key Item','bitOffset': 1, 'missable': 1},
    "Blue Key": {'level': 'Kendarie Fortress', 'type': 'Key Item','bitOffset': 2, 'missable': 1},
    "Green Key": {'level': 'Kendarie Fortress', 'type': 'Key Item', 'bitOffset': 3, 'missable': 1},
    "Fossil Head": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 4},
    "Fossil Torso": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 5},
    "Fossil Tail": {'level': 'Fossil Boneyard', 'type': 'Key Item', 'bitOffset': 6},
    "Fossil Rt Wing": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 7},
    "Fossil Lt Wing": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 8},
    "Fossil Rt Arm": {'level': 'Fossil Boneyard', 'type': 'Key Item', 'bitOffset': 9},
    "Fossil Lt Arm": {'level': 'Fossil Boneyard', 'type': 'Key Item', 'bitOffset': 10},
    "Fossil Rt Leg": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 11},
    "Fossil Lt Leg": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 12},
    "Bottle": {'level': 'Gromtull Desert', 'type': 'Key Item', 'bitOffset': 13},
    "Black Liquid": {'level': 'Gromtull Desert', 'type': 'Key Item','bitOffset': 14},
    "Mysterious Key": {'level': 'Sacred Battle Arena 1', 'type': 'Key Item','bitOffset': 15},
    "Blade of Skill": {'level': 'Bhashea Castle', 'type': 'Key Item', 'bitOffset': 16},
    "Blade of Power": {'level': 'Bhashea Castle', 'type': 'Key Item','bitOffset': 17},
    "Blade of Wisdom": {'level': 'Bhashea Castle', 'type': 'Key Item','bitOffset': 18},
    "Blade of Time": {'level': 'Bhashea Castle', 'type': 'Key Item', 'bitOffset': 19},
    "Jewel of Alanjeh": {'level': 'Grenfoel Cathedral', 'type': 'Key Item', 'bitOffset': 20},
    "Eno Runestone": {'level': 'Ruldo Forest', 'type': 'Key Item','bitOffset': 21},
    "Oht Runestone": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 22},
    "Elise Runestone": {'level': 'Plains of Rowahl', 'type': 'Key Item', 'bitOffset': 23},
    "Olf Runestone": {'level': 'Sacred Battle Arena 1', 'type': 'Key Item','bitOffset': 24},
    "Ebin Runestone": {'level': 'Gromtull Desert', 'type': 'Key Item','bitOffset': 25},
    "Keil Runestone": {'level': "Nobleman's Residence", 'type': 'Key Item', 'bitOffset': 26},
    "Nebeth Runestone": {'level': 'Isamat Urbur', 'type': 'Key Item','bitOffset': 27},
    "Stone of Sealing": {'level': 'Isamat Urbur', 'type': 'Key Item','bitOffset': 28},
    "Castle Gate Key": {'level': 'Plains of Rowahl', 'type': 'Key Item', 'bitOffset': 29},
    "Key to Fountain": {'level': 'Holzogh Town', 'type': 'Key Item', 'bitOffset': 30}
}

magic_boosters_location = {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '', 'missable': 0,
                                      'RAMAddress': '8025dd90', 'type': 'Magic Boosters', 'bitOffset': 3}

lost_kingdoms_2_regions = {
    "Nobleman's Residence": { "RAMAddress": "8025dc0e"},
    "Bhashea High Road": { "RAMAddress": "8025dc4e"},
    "Kadishu": { "RAMAddress": "8025dc8e" },
    "Kadishu Shop": { "RAMAddress": "8025e60e" },
    "Fairy House": { "RAMAddress": "8025e5ce" },
    "Bhashea Castle": { "RAMAddress": "8025e10e"},
    "Gromtull Desert": { "RAMAddress": "8025e14e"},
    "Kendarie Fortress": { "RAMAddress": "8025dcce"},
    "Runestone Caverns - Upper Chambers": { "RAMAddress": "8025dd0e"},
    "Runestone Caverns - Lower Chambers": { "RAMAddress": "8025dd4e"},
    "Ruldo Forest": { "RAMAddress": "8025dd8e"},
    "Sacred Battle Arena 1": { "RAMAddress": "8025e18e"},
    "Sacred Battle Arena 2": { "RAMAddress": "8025e1ce"},
    "Fossil Boneyard": { "RAMAddress": "8025e00e"},
    "Sarvan": { "RAMAddress": "8025ddce"},
    "Holzogh Town": { "RAMAddress": "8025de0e"},
    "Plains of Rowahl": { "RAMAddress": "8025de4e"},
    "Alanjeh Castle": { "RAMAddress": "8025de8e"},
    "Royal Tower, Lower": { "RAMAddress": "8025dece"},
    "Royal Tower, Middle": { "RAMAddress": "8025df8e"},
    "Royal Tower, Upper": { "RAMAddress": "8025dfce"},
    "Krasheen Mountains": { "RAMAddress": "8025df0e"},
    "Grenfoel Cathedral": { "RAMAddress": "8025df4e"},
    "Temple of Sharacia": { "RAMAddress": "8025e28e"},
    "Grenfoel Cathedral Shop": { "RAMAddress": "8025e64e"},
    "Isamat Urbur": { "RAMAddress": "8025e0ce"},
    "Obenoix Gorge": { "RAMAddress": "8025e20e"},
    "Proving Grounds": { "RAMAddress": "8025e84e"}
}

lost_kingdoms_2_combos = {
    "Combo - Triple Hagan" : { "bitOffset" : 33, "type": "Combo", "level":"Menu"},
    "Combo - Ultimate Pasta" : { "bitOffset" : 34, "type": "Combo", "level":"Menu"},
    "Combo - Rotary Death" : { "bitOffset" : 35, "type": "Combo", "level":"Menu"},
    "Combo - Lizard War" : { "bitOffset" : 36, "type": "Combo", "level":"Menu"},
    "Combo - Rocky Forecast" : { "bitOffset" : 37, "type": "Combo", "level":"Menu"},
    "Combo - Sir Spear-A-Lot" : { "bitOffset" : 38, "type": "Combo", "level":"Menu"},
    "Combo - Temper Tantrum" : { "bitOffset" : 39, "type": "Combo", "level":"Menu"},
    "Combo - Goblin Guts" : { "bitOffset" : 40, "type": "Combo", "level":"Menu"},
    "Combo - Lethal Orbit" : { "bitOffset" : 41, "type": "Combo", "level":"Menu"},
    "Combo - Crystal Rage" : { "bitOffset" : 42, "type": "Combo", "level":"Menu"},
    "Combo - Mandragora Mixer" : { "bitOffset" : 43, "type": "Combo", "level":"Menu"},
    "Combo - Rust and Roll!" : { "bitOffset" : 44, "type": "Combo", "level":"Menu"},
    "Combo - EconoMagic" : { "bitOffset" : 45, "type": "Combo", "level":"Menu"},
    "Combo - Just Visiting" : { "bitOffset" : 46, "type": "Combo", "level":"Menu"},
    "Combo - Djinn and Bear It" : { "bitOffset" : 47, "type": "Combo", "level":"Menu"},
    "Combo - Triple Kamikaze" : { "bitOffset" : 48, "type": "Combo", "level":"Menu"},
    "Combo - One Way Ticket" : { "bitOffset" : 49, "type": "Combo", "level":"Menu"},
    "Combo - The Masters Four" : { "bitOffset" : 50, "type": "Combo", "level":"Menu"},
    "Combo - The Big Save" : { "bitOffset" : 51, "type": "Combo", "level":"Menu"},
    "Combo - Brutal Nightmare" : { "bitOffset" : 52, "type": "Combo", "level":"Menu"},
    "Combo - Phantom BullDozer" : { "bitOffset" : 53, "type": "Combo", "level":"Menu"},
    "Combo - Living Large" : { "bitOffset" : 54, "type": "Combo", "level":"Menu"},
    "Combo - Elemental Victory" : { "bitOffset" : 55, "type": "Combo", "level":"Menu"},
    "Combo - Skullapalooza" : { "bitOffset" : 56, "type": "Combo", "level":"Menu"},
    "Combo - Stone Cold Sniper" : { "bitOffset" : 57, "type": "Combo", "level":"Menu"},
    "Combo - Mega Tremor" : { "bitOffset" : 58, "type": "Combo", "level":"Menu"},
    "Combo - Time Out!" : { "bitOffset" : 60, "type": "Combo", "level":"Menu"},
    "Combo - Hell Hole" : { "bitOffset" : 61, "type": "Combo", "level":"Menu"},
    "Combo - Spiritual Force" : { "bitOffset" : 62, "type": "Combo", "level":"Menu"},
    "Combo - Air Raid" : { "bitOffset" : 0, "type": "Combo", "level":"Menu"},
    "Combo - Tech Support!" : { "bitOffset" : 2, "type": "Combo", "level":"Menu"},
    "Combo - Song of Hades" : { "bitOffset" : 3, "type": "Combo", "level":"Menu"},
    "Combo - Hearing Aid" : { "bitOffset" : 4, "type": "Combo", "level":"Menu"},
    "Combo - Uber Vampire Root" : { "bitOffset" : 6, "type": "Combo", "level":"Menu"},
    "Combo - Mo Better Moray" : { "bitOffset" : 7, "type": "Combo", "level":"Menu"},
    "Combo - Prayer of the Wise" : { "bitOffset" : 10, "type": "Combo", "level":"Menu"},
    "Combo - Hawging the Action" : { "bitOffset" : 17, "type": "Combo", "level":"Menu"},
    "Combo - Stone All Around" : { "bitOffset" : 19, "type": "Combo", "level":"Menu"},
    "Combo - Tender Mercy" : { "bitOffset" : 20, "type": "Combo", "level":"Menu"},
    "Combo - Green Guardian" : { "bitOffset" : 26, "type": "Combo", "level":"Menu"},
}

lost_kingdoms_2_shop_purchases = {
    "Kadishu Shop 1 - 1st card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 0, 'missable': 1},
    "Kadishu Shop 1 - 2nd card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 1, 'missable': 1},
    "Kadishu Shop 1 - 3rd card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 2, 'missable': 1},
    "Kadishu Shop 1 - 4th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 3, 'missable': 1},
    "Kadishu Shop 1 - 5th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 4, 'missable': 1},
    "Kadishu Shop 1 - 6th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 5, 'missable': 1},
    "Kadishu Shop 1 - 7th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 6, 'missable': 1},
    "Kadishu Shop 1 - 8th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 7, 'missable': 1},
    "Kadishu Shop 1 - 9th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 8, 'missable': 1},
    "Kadishu Shop 1 - 10th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 9, 'missable': 1},

    "Kadishu Shop 2 - 1st card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 10, 'missable': 1},
    "Kadishu Shop 2 - 2nd card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 11, 'missable': 1},
    "Kadishu Shop 2 - 3rd card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 12, 'missable': 1},
    "Kadishu Shop 2 - 4th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 13, 'missable': 1},
    "Kadishu Shop 2 - 5th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 14, 'missable': 1},
    "Kadishu Shop 2 - 6th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 15, 'missable': 1},
    "Kadishu Shop 2 - 7th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 16, 'missable': 1},
    "Kadishu Shop 2 - 8th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 17, 'missable': 1},
    "Kadishu Shop 2 - 9th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 18, 'missable': 1},
    "Kadishu Shop 2 - 10th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 19, 'missable': 1},

    "Kadishu Shop 3 - 1st card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 20, 'missable': 0},
    "Kadishu Shop 3 - 2nd card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 21, 'missable': 0},
    "Kadishu Shop 3 - 3rd card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 22, 'missable': 0},
    "Kadishu Shop 3 - 4th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 23, 'missable': 0},
    "Kadishu Shop 3 - 5th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 24, 'missable': 0},
    "Kadishu Shop 3 - 6th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 25, 'missable': 0},
    "Kadishu Shop 3 - 7th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 26, 'missable': 0},
    "Kadishu Shop 3 - 8th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 27, 'missable': 0},
    "Kadishu Shop 3 - 9th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 28, 'missable': 0},
    "Kadishu Shop 3 - 10th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 29, 'missable': 0},

    "Cathedral Shop - 1st card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 30, 'missable': 0},
    "Cathedral Shop - 2nd card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 31, 'missable': 0},
    "Cathedral Shop - 3rd card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 32, 'missable': 0},
    "Cathedral Shop - 4th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 33, 'missable': 0},
    "Cathedral Shop - 5th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 34, 'missable': 0},
    "Cathedral Shop - 6th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 35, 'missable': 0},
    "Cathedral Shop - 7th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 36, 'missable': 0},
    "Cathedral Shop - 8th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 37, 'missable': 0},
    "Cathedral Shop - 9th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 38, 'missable': 0},
    "Cathedral Shop - 10th card": {"level": "Kadishu Shop", "type": "Shop Purchase", "bitOffset": 39, 'missable': 0},

}

lost_kingdoms_2_bonus_draws = {
    "NR Bonus Draw - Common 1": {"level": "Nobleman's Residence", "rarity": "Common", "cardGroup": 1, "address": "183169", "cardId": 19, "type": "Bonus Draw"},
    "NR Bonus Draw - Common 2": {"level": "Nobleman's Residence", "rarity": "Common", "cardGroup": 1, "address": "18316B", "cardId": 53, "type": "Bonus Draw"},
    "NR Bonus Draw - Common 3": {"level": "Nobleman's Residence", "rarity": "Common", "cardGroup": 1, "address": "18316D", "cardId": 53, "type": "Bonus Draw"},
    "NR Bonus Draw - Uncommon 1": {"level": "Nobleman's Residence", "rarity": "Uncommon", "cardGroup": 2, "address": "18316F", "cardId": 213, "type": "Bonus Draw"},
    "NR Bonus Draw - Uncommon 2": {"level": "Nobleman's Residence", "rarity": "Uncommon", "cardGroup": 2, "address": "183171", "cardId": 213, "type": "Bonus Draw"},
    "NR Bonus Draw - Rare": {"level": "Nobleman's Residence", "rarity": "Rare", "cardGroup": 3, "address": "183173", "cardId": 213, "type": "Bonus Draw"},

    "BHR Bonus Draw - Common 1": {"level": "Bhashea High Road", "rarity": "Common", "cardGroup": 4, "address": "183175", "cardId": 12, "type": "Bonus Draw"},
    "BHR Bonus Draw - Common 2": {"level": "Bhashea High Road", "rarity": "Common", "cardGroup": 4, "address": "183177", "cardId": 12, "type": "Bonus Draw"},
    "BHR Bonus Draw - Common 3": {"level": "Bhashea High Road", "rarity": "Common", "cardGroup": 4, "address": "183179", "cardId": 12, "type": "Bonus Draw"},
    "BHR Bonus Draw - Uncommon 1": {"level": "Bhashea High Road", "rarity": "Uncommon", "cardGroup": 5, "address": "18317B", "cardId": 123, "type": "Bonus Draw"},
    "BHR Bonus Draw - Uncommon 2": {"level": "Bhashea High Road", "rarity": "Uncommon", "cardGroup": 5, "address": "18317D", "cardId": 123, "type": "Bonus Draw"},
    "BHR Bonus Draw - Rare": {"level": "Bhashea High Road", "rarity": "Rare", "cardGroup": 6, "address": "18317F", "cardId": 171, "type": "Bonus Draw"},

    "KF Bonus Draw - Common 1": {"level": "Kendarie Fortress", "rarity": "Common", "cardGroup": 7, "address": "18318D", "cardId": 5, "type": "Bonus Draw"},
    "KF Bonus Draw - Common 2": {"level": "Kendarie Fortress", "rarity": "Common", "cardGroup": 7, "address": "18318F", "cardId": 5, "type": "Bonus Draw"},
    "KF Bonus Draw - Common 3": {"level": "Kendarie Fortress", "rarity": "Common", "cardGroup": 7, "address": "183191", "cardId": 110, "type": "Bonus Draw"},
    "KF Bonus Draw - Uncommon 1": {"level": "Kendarie Fortress", "rarity": "Uncommon", "cardGroup": 8, "address": "183193", "cardId": 110, "type": "Bonus Draw"},
    "KF Bonus Draw - Uncommon 2": {"level": "Kendarie Fortress", "rarity": "Uncommon", "cardGroup": 8, "address": "183195", "cardId": 178, "type": "Bonus Draw"},
    "KF Bonus Draw - Rare": {"level": "Kendarie Fortress", "rarity": "Rare", "cardGroup": 9, "address": "183197", "cardId": 178, "type": "Bonus Draw"},

    "RC-UC Bonus Draw - Common 1": {"level": "Runestone Caverns - Upper Chambers", "rarity": "Common", "cardGroup": 10, "address": "183199", "cardId": 34, "type": "Bonus Draw"},
    "RC-UC Bonus Draw - Common 2": {"level": "Runestone Caverns - Upper Chambers", "rarity": "Common", "cardGroup": 10, "address": "18319B", "cardId": 34, "type": "Bonus Draw"},
    "RC-UC Bonus Draw - Common 3": {"level": "Runestone Caverns - Upper Chambers", "rarity": "Common", "cardGroup": 10, "address": "18319D", "cardId": 34, "type": "Bonus Draw"},
    "RC-UC Bonus Draw - Uncommon 1": {"level": "Runestone Caverns - Upper Chambers", "rarity": "Uncommon", "cardGroup": 11, "address": "18319F", "cardId": 52, "type": "Bonus Draw"},
    "RC-UC Bonus Draw - Uncommon 2": {"level": "Runestone Caverns - Upper Chambers", "rarity": "Uncommon", "cardGroup": 11, "address": "1831A1", "cardId": 52, "type": "Bonus Draw"},
    "RC-UC Bonus Draw - Rare": {"level": "Runestone Caverns - Upper Chambers", "rarity": "Rare", "cardGroup": 12, "address": "1831A3", "cardId": 145, "type": "Bonus Draw"},

    "RC-LC Bonus Draw - Common 1": {"level": "Runestone Caverns - Lower Chambers", "rarity": "Common", "cardGroup": 13, "address": "1831A5", "cardId": 23, "type": "Bonus Draw"},
    "RC-LC Bonus Draw - Common 2": {"level": "Runestone Caverns - Lower Chambers", "rarity": "Common", "cardGroup": 13, "address": "1831A7", "cardId": 23, "type": "Bonus Draw"},
    "RC-LC Bonus Draw - Common 3": {"level": "Runestone Caverns - Lower Chambers", "rarity": "Common", "cardGroup": 13, "address": "1831A9", "cardId": 27, "type": "Bonus Draw"},
    "RC-LC Bonus Draw - Uncommon 1": {"level": "Runestone Caverns - Lower Chambers", "rarity": "Uncommon", "cardGroup": 14, "address": "1831AB", "cardId": 27, "type": "Bonus Draw"},
    "RC-LC Bonus Draw - Uncommon 2": {"level": "Runestone Caverns - Lower Chambers", "rarity": "Uncommon", "cardGroup": 14, "address": "1831AD", "cardId": 120, "type": "Bonus Draw"},
    "RC-LC Bonus Draw - Rare": {"level": "Runestone Caverns - Lower Chambers", "rarity": "Rare", "cardGroup": 15, "address": "1831AF", "cardId": 120, "type": "Bonus Draw"},

    "RF Bonus Draw - Common 1": {"level": "Ruldo Forest", "rarity": "Common", "cardGroup": 16, "address": "1831B1", "cardId": 15, "type": "Bonus Draw"},
    "RF Bonus Draw - Common 2": {"level": "Ruldo Forest", "rarity": "Common", "cardGroup": 16, "address": "1831B3", "cardId": 135, "type": "Bonus Draw"},
    "RF Bonus Draw - Common 3": {"level": "Ruldo Forest", "rarity": "Common", "cardGroup": 16, "address": "1831B5", "cardId": 135, "type": "Bonus Draw"},
    "RF Bonus Draw - Uncommon 1": {"level": "Ruldo Forest", "rarity": "Uncommon", "cardGroup": 17, "address": "1831B7", "cardId": 154, "type": "Bonus Draw"},
    "RF Bonus Draw - Uncommon 2": {"level": "Ruldo Forest", "rarity": "Uncommon", "cardGroup": 17, "address": "1831B9", "cardId": 154, "type": "Bonus Draw"},
    "RF Bonus Draw - Rare": {"level": "Ruldo Forest", "rarity": "Rare", "cardGroup": 18, "address": "1831BB", "cardId": 154, "type": "Bonus Draw"},

    "Sarvan Bonus Draw - Common 1": {"level": "Sarvan", "rarity": "Common", "cardGroup": 19, "address": "1831BD", "cardId": 46, "type": "Bonus Draw"},
    "Sarvan Bonus Draw - Common 2": {"level": "Sarvan", "rarity": "Common", "cardGroup": 19, "address": "1831BF", "cardId": 46, "type": "Bonus Draw"},
    "Sarvan Bonus Draw - Common 3": {"level": "Sarvan", "rarity": "Common", "cardGroup": 19, "address": "1831C1", "cardId": 46, "type": "Bonus Draw"},
    "Sarvan Bonus Draw - Uncommon 1": {"level": "Sarvan", "rarity": "Uncommon", "cardGroup": 20, "address": "1831C3", "cardId": 74, "type": "Bonus Draw"},
    "Sarvan Bonus Draw - Uncommon 2": {"level": "Sarvan", "rarity": "Uncommon", "cardGroup": 20, "address": "1831C5", "cardId": 74, "type": "Bonus Draw"},
    "Sarvan Bonus Draw - Rare": {"level": "Sarvan", "rarity": "Rare", "cardGroup": 21, "address": "1831C7", "cardId": 76, "type": "Bonus Draw"},

    "HT Bonus Draw - Common 1": {"level": "Holzogh Town", "rarity": "Common", "cardGroup": 22, "address": "1831C9", "cardId": 54, "type": "Bonus Draw"},
    "HT Bonus Draw - Common 2": {"level": "Holzogh Town", "rarity": "Common", "cardGroup": 22, "address": "1831CB", "cardId": 54, "type": "Bonus Draw"},
    "HT Bonus Draw - Common 3": {"level": "Holzogh Town", "rarity": "Common", "cardGroup": 22, "address": "1831CD", "cardId": 54, "type": "Bonus Draw"},
    "HT Bonus Draw - Uncommon 1": {"level": "Holzogh Town", "rarity": "Uncommon", "cardGroup": 23, "address": "1831CF", "cardId": 168, "type": "Bonus Draw"},
    "HT Bonus Draw - Uncommon 2": {"level": "Holzogh Town", "rarity": "Uncommon", "cardGroup": 23, "address": "1831D1", "cardId": 168, "type": "Bonus Draw"},
    "HT Bonus Draw - Rare": {"level": "Holzogh Town", "rarity": "Rare", "cardGroup": 24, "address": "1831D3", "cardId": 153, "type": "Bonus Draw"},

    "PoR Bonus Draw - Common 1": {"level": "Plains of Rowahl", "rarity": "Common", "cardGroup": 25, "address": "1831D5", "cardId": 10, "type": "Bonus Draw"},
    "PoR Bonus Draw - Common 2": {"level": "Plains of Rowahl", "rarity": "Common", "cardGroup": 25, "address": "1831D7", "cardId": 10, "type": "Bonus Draw"},
    "PoR Bonus Draw - Common 3": {"level": "Plains of Rowahl", "rarity": "Common", "cardGroup": 25, "address": "1831D9", "cardId": 10, "type": "Bonus Draw"},
    "PoR Bonus Draw - Uncommon 1": {"level": "Plains of Rowahl", "rarity": "Uncommon", "cardGroup": 26, "address": "1831DB", "cardId": 77, "type": "Bonus Draw"},
    "PoR Bonus Draw - Uncommon 2": {"level": "Plains of Rowahl", "rarity": "Uncommon", "cardGroup": 26, "address": "1831DD", "cardId": 77, "type": "Bonus Draw"},
    "PoR Bonus Draw - Rare": {"level": "Plains of Rowahl", "rarity": "Rare", "cardGroup": 27, "address": "1831DF", "cardId": 132, "type": "Bonus Draw"},

    "AC Bonus Draw - Common 1": {"level": "Alanjeh Castle", "rarity": "Common", "cardGroup": 28, "address": "1831E1", "cardId": 183, "type": "Bonus Draw"},
    "AC Bonus Draw - Common 2": {"level": "Alanjeh Castle", "rarity": "Common", "cardGroup": 28, "address": "1831E3", "cardId": 183, "type": "Bonus Draw"},
    "AC Bonus Draw - Common 3": {"level": "Alanjeh Castle", "rarity": "Common", "cardGroup": 28, "address": "1831E5", "cardId": 147, "type": "Bonus Draw"},
    "AC Bonus Draw - Uncommon 1": {"level": "Alanjeh Castle", "rarity": "Uncommon", "cardGroup": 29, "address": "1831E7", "cardId": 147, "type": "Bonus Draw"},
    "AC Bonus Draw - Uncommon 2": {"level": "Alanjeh Castle", "rarity": "Uncommon", "cardGroup": 29, "address": "1831E9", "cardId": 201, "type": "Bonus Draw"},
    "AC Bonus Draw - Rare": {"level": "Alanjeh Castle", "rarity": "Rare", "cardGroup": 30, "address": "1831EB", "cardId": 201, "type": "Bonus Draw"},

    "KM Bonus Draw - Common 1": {"level": "Krasheen Mountains", "rarity": "Common", "cardGroup": 31, "address": "1831F9", "cardId": 99, "type": "Bonus Draw"},
    "KM Bonus Draw - Common 2": {"level": "Krasheen Mountains", "rarity": "Common", "cardGroup": 31, "address": "1831FB", "cardId": 192, "type": "Bonus Draw"},
    "KM Bonus Draw - Common 3": {"level": "Krasheen Mountains", "rarity": "Common", "cardGroup": 31, "address": "1831FD", "cardId": 192, "type": "Bonus Draw"},
    "KM Bonus Draw - Uncommon 1": {"level": "Krasheen Mountains", "rarity": "Uncommon", "cardGroup": 32, "address": "1831FF", "cardId": 177, "type": "Bonus Draw"},
    "KM Bonus Draw - Uncommon 2": {"level": "Krasheen Mountains", "rarity": "Uncommon", "cardGroup": 32, "address": "183201", "cardId": 177, "type": "Bonus Draw"},
    "KM Bonus Draw - Rare": {"level": "Krasheen Mountains", "rarity": "Rare", "cardGroup": 33, "address": "183203", "cardId": 177, "type": "Bonus Draw"},

    "RTM Bonus Draw - Common 1": {"level": "Royal Tower, Middle", "rarity": "Common", "cardGroup": 34, "address": "183211", "cardId": 95, "type": "Bonus Draw"},
    "RTM Bonus Draw - Common 2": {"level": "Royal Tower, Middle", "rarity": "Common", "cardGroup": 34, "address": "183213", "cardId": 95, "type": "Bonus Draw"},
    "RTM Bonus Draw - Common 3": {"level": "Royal Tower, Middle", "rarity": "Common", "cardGroup": 34, "address": "183215", "cardId": 179, "type": "Bonus Draw"},
    "RTM Bonus Draw - Uncommon 1": {"level": "Royal Tower, Middle", "rarity": "Uncommon", "cardGroup": 35, "address": "183217", "cardId": 179, "type": "Bonus Draw"},
    "RTM Bonus Draw - Uncommon 2": {"level": "Royal Tower, Middle", "rarity": "Uncommon", "cardGroup": 35, "address": "183219", "cardId": 179, "type": "Bonus Draw"},
    "RTM Bonus Draw - Rare": {"level": "Royal Tower, Middle", "rarity": "Rare", "cardGroup": 35, "address": "18321B", "cardId": 179, "type": "Bonus Draw"},

    "RTU Bonus Draw - Common 1": {"level": "Royal Tower, Upper", "rarity": "Common", "cardGroup": 36, "address": "18321D", "cardId": 86, "type": "Bonus Draw"},
    "RTU Bonus Draw - Common 2": {"level": "Royal Tower, Upper", "rarity": "Common", "cardGroup": 36, "address": "18321F", "cardId": 116, "type": "Bonus Draw"},
    "RTU Bonus Draw - Common 3": {"level": "Royal Tower, Upper", "rarity": "Common", "cardGroup": 36, "address": "183221", "cardId": 116, "type": "Bonus Draw"},
    "RTU Bonus Draw - Uncommon 1": {"level": "Royal Tower, Upper", "rarity": "Uncommon", "cardGroup": 37, "address": "183223", "cardId": 116, "type": "Bonus Draw"},
    "RTU Bonus Draw - Uncommon 2": {"level": "Royal Tower, Upper", "rarity": "Uncommon", "cardGroup": 37, "address": "183225", "cardId": 188, "type": "Bonus Draw"},
    "RTU Bonus Draw - Rare": {"level": "Royal Tower, Upper", "rarity": "Rare", "cardGroup": 38, "address": "183227", "cardId": 188, "type": "Bonus Draw"},

    "FB Bonus Draw - Common 1": {"level": "Fossil Boneyard", "rarity": "Common", "cardGroup": 39, "address": "183229", "cardId": 94, "type": "Bonus Draw"},
    "FB Bonus Draw - Common 2": {"level": "Fossil Boneyard", "rarity": "Common", "cardGroup": 39, "address": "18322B", "cardId": 94, "type": "Bonus Draw"},
    "FB Bonus Draw - Common 3": {"level": "Fossil Boneyard", "rarity": "Common", "cardGroup": 39, "address": "18322D", "cardId": 142, "type": "Bonus Draw"},
    "FB Bonus Draw - Uncommon 1": {"level": "Fossil Boneyard", "rarity": "Uncommon", "cardGroup": 40, "address": "18322F", "cardId": 142, "type": "Bonus Draw"},
    "FB Bonus Draw - Uncommon 2": {"level": "Fossil Boneyard", "rarity": "Uncommon", "cardGroup": 40, "address": "183231", "cardId": 142, "type": "Bonus Draw"},
    "FB Bonus Draw - Rare": {"level": "Fossil Boneyard", "rarity": "Rare", "cardGroup": 41, "address": "183233", "cardId": 160, "type": "Bonus Draw"},

    "RTL Bonus Draw - Common 1": {"level": "Royal Tower, Lower", "rarity": "Common", "cardGroup": 42, "address": "183235", "cardId": 175, "type": "Bonus Draw"},
    "RTL Bonus Draw - Common 2": {"level": "Royal Tower, Lower", "rarity": "Common", "cardGroup": 42, "address": "183237", "cardId": 175, "type": "Bonus Draw"},
    "RTL Bonus Draw - Common 3": {"level": "Royal Tower, Lower", "rarity": "Common", "cardGroup": 42, "address": "183239", "cardId": 202, "type": "Bonus Draw"},
    "RTL Bonus Draw - Uncommon 1": {"level": "Royal Tower, Lower", "rarity": "Uncommon", "cardGroup": 43, "address": "18323B", "cardId": 202, "type": "Bonus Draw"},
    "RTL Bonus Draw - Uncommon 2": {"level": "Royal Tower, Lower", "rarity": "Uncommon", "cardGroup": 43, "address": "18323D", "cardId": 202, "type": "Bonus Draw"},
    "RTL Bonus Draw - Rare": {"level": "Royal Tower, Lower", "rarity": "Rare", "cardGroup": 43, "address": "18323F", "cardId": 202, "type": "Bonus Draw"},

    "IU Bonus Draw - Common 1": {"level": "Isamat Urbur", "rarity": "Common", "cardGroup": 44, "address": "18324D", "cardId": 65, "type": "Bonus Draw"},
    "IU Bonus Draw - Common 2": {"level": "Isamat Urbur", "rarity": "Common", "cardGroup": 44, "address": "18324F", "cardId": 65, "type": "Bonus Draw"},
    "IU Bonus Draw - Common 3": {"level": "Isamat Urbur", "rarity": "Common", "cardGroup": 44, "address": "183251", "cardId": 88, "type": "Bonus Draw"},
    "IU Bonus Draw - Uncommon 1": {"level": "Isamat Urbur", "rarity": "Uncommon", "cardGroup": 45, "address": "183253", "cardId": 88, "type": "Bonus Draw"},
    "IU Bonus Draw - Uncommon 2": {"level": "Isamat Urbur", "rarity": "Uncommon", "cardGroup": 45, "address": "183255", "cardId": 182, "type": "Bonus Draw"},
    "IU Bonus Draw - Rare": {"level": "Isamat Urbur", "rarity": "Rare", "cardGroup": 46, "address": "183257", "cardId": 182, "type": "Bonus Draw"},

    "BC Bonus Draw - Common 1": {"level": "Bhashea Castle", "rarity": "Common", "cardGroup": 47, "address": "183259", "cardId": 57, "type": "Bonus Draw"},
    "BC Bonus Draw - Common 2": {"level": "Bhashea Castle", "rarity": "Common", "cardGroup": 47, "address": "18325B", "cardId": 57, "type": "Bonus Draw"},
    "BC Bonus Draw - Common 3": {"level": "Bhashea Castle", "rarity": "Common", "cardGroup": 47, "address": "18325D", "cardId": 57, "type": "Bonus Draw"},
    "BC Bonus Draw - Uncommon 1": {"level": "Bhashea Castle", "rarity": "Uncommon", "cardGroup": 48, "address": "18325F", "cardId": 60, "type": "Bonus Draw"},
    "BC Bonus Draw - Uncommon 2": {"level": "Bhashea Castle", "rarity": "Uncommon", "cardGroup": 48, "address": "183261", "cardId": 60, "type": "Bonus Draw"},
    "BC Bonus Draw - Rare": {"level": "Bhashea Castle", "rarity": "Rare", "cardGroup": 49, "address": "183263", "cardId": 100, "type": "Bonus Draw"},

    "GD Bonus Draw - Common 1": {"level": "Gromtull Desert", "rarity": "Common", "cardGroup": 50, "address": "183265", "cardId": 13, "type": "Bonus Draw"},
    "GD Bonus Draw - Common 2": {"level": "Gromtull Desert", "rarity": "Common", "cardGroup": 50, "address": "183267", "cardId": 14, "type": "Bonus Draw"},
    "GD Bonus Draw - Common 3": {"level": "Gromtull Desert", "rarity": "Common", "cardGroup": 50, "address": "183269", "cardId": 14, "type": "Bonus Draw"},
    "GD Bonus Draw - Uncommon 1": {"level": "Gromtull Desert", "rarity": "Uncommon", "cardGroup": 51, "address": "18326B", "cardId": 14, "type": "Bonus Draw"},
    "GD Bonus Draw - Uncommon 2": {"level": "Gromtull Desert", "rarity": "Uncommon", "cardGroup": 51, "address": "18326D", "cardId": 43, "type": "Bonus Draw"},
    "GD Bonus Draw - Rare": {"level": "Gromtull Desert", "rarity": "Rare", "cardGroup": 52, "address": "18326F", "cardId": 43, "type": "Bonus Draw"},

    "SBA1 Bonus Draw - Common 1": {"level": "Sacred Battle Arena 1", "rarity": "Common", "cardGroup": 53, "address": "183271", "cardId": 1, "type": "Bonus Draw"},
    "SBA1 Bonus Draw - Common 2": {"level": "Sacred Battle Arena 1", "rarity": "Common", "cardGroup": 53, "address": "183273", "cardId": 1, "type": "Bonus Draw"},
    "SBA1 Bonus Draw - Common 3": {"level": "Sacred Battle Arena 1", "rarity": "Common", "cardGroup": 53, "address": "183275", "cardId": 1, "type": "Bonus Draw"},
    "SBA1 Bonus Draw - Uncommon 1": {"level": "Sacred Battle Arena 1", "rarity": "Uncommon", "cardGroup": 53, "address": "183277", "cardId": 1, "type": "Bonus Draw"},
    "SBA1 Bonus Draw - Uncommon 2": {"level": "Sacred Battle Arena 1", "rarity": "Uncommon", "cardGroup": 53, "address": "183279", "cardId": 1, "type": "Bonus Draw"},
    "SBA1 Bonus Draw - Rare": {"level": "Sacred Battle Arena 1", "rarity": "Rare", "cardGroup": 53, "address": "18327B", "cardId": 1, "type": "Bonus Draw"},

    "SBA2 Bonus Draw - Common 1": {"level": "Sacred Battle Arena 2", "rarity": "Common", "cardGroup": 54, "address": "18327D", "cardId": 153, "type": "Bonus Draw"},
    "SBA2 Bonus Draw - Common 2": {"level": "Sacred Battle Arena 2", "rarity": "Common", "cardGroup": 54, "address": "18327F", "cardId": 153, "type": "Bonus Draw"},
    "SBA2 Bonus Draw - Common 3": {"level": "Sacred Battle Arena 2", "rarity": "Common", "cardGroup": 54, "address": "183281", "cardId": 153, "type": "Bonus Draw"},
    "SBA2 Bonus Draw - Uncommon 1": {"level": "Sacred Battle Arena 2", "rarity": "Uncommon", "cardGroup": 54, "address": "183283", "cardId": 153, "type": "Bonus Draw"},
    "SBA2 Bonus Draw - Uncommon 2": {"level": "Sacred Battle Arena 2", "rarity": "Uncommon", "cardGroup": 54, "address": "183285", "cardId": 153, "type": "Bonus Draw"},
    "SBA2 Bonus Draw - Rare": {"level": "Sacred Battle Arena 2", "rarity": "Rare", "cardGroup": 54, "address": "183287", "cardId": 153, "type": "Bonus Draw"},

    "OG Bonus Draw - Common 1": {"level": "Obenoix Gorge", "rarity": "Common", "cardGroup": 55, "address": "183289", "cardId": 185, "type": "Bonus Draw"},
    "OG Bonus Draw - Common 2": {"level": "Obenoix Gorge", "rarity": "Common", "cardGroup": 55, "address": "18328B", "cardId": 73, "type": "Bonus Draw"},
    "OG Bonus Draw - Common 3": {"level": "Obenoix Gorge", "rarity": "Common", "cardGroup": 55, "address": "18328D", "cardId": 73, "type": "Bonus Draw"},
    "OG Bonus Draw - Uncommon 1": {"level": "Obenoix Gorge", "rarity": "Uncommon", "cardGroup": 56, "address": "18328F", "cardId": 128, "type": "Bonus Draw"},
    "OG Bonus Draw - Uncommon 2": {"level": "Obenoix Gorge", "rarity": "Uncommon", "cardGroup": 56, "address": "183291", "cardId": 128, "type": "Bonus Draw"},
    "OG Bonus Draw - Rare": {"level": "Obenoix Gorge", "rarity": "Rare", "cardGroup": 57, "address": "183293", "cardId": 128, "type": "Bonus Draw"},

    "ToS Bonus Draw - Common 1": {"level": "Temple of Sharacia", "rarity": "Common", "cardGroup": 58, "address": "1832A1", "cardId": 3, "type": "Bonus Draw"},
    "ToS Bonus Draw - Common 2": {"level": "Temple of Sharacia", "rarity": "Common", "cardGroup": 58, "address": "1832A3", "cardId": 3, "type": "Bonus Draw"},
    "ToS Bonus Draw - Common 3": {"level": "Temple of Sharacia", "rarity": "Common", "cardGroup": 58, "address": "1832A5", "cardId": 205, "type": "Bonus Draw"},
    "ToS Bonus Draw - Uncommon 1": {"level": "Temple of Sharacia", "rarity": "Uncommon", "cardGroup": 59, "address": "1832A7", "cardId": 205, "type": "Bonus Draw"},
    "ToS Bonus Draw - Uncommon 2": {"level": "Temple of Sharacia", "rarity": "Uncommon", "cardGroup": 59, "address": "1832A9", "cardId": 66, "type": "Bonus Draw"},
    "ToS Bonus Draw - Rare": {"level": "Temple of Sharacia", "rarity": "Rare", "cardGroup": 60, "address": "1832AB", "cardId": 66, "type": "Bonus Draw"},
}

lost_kingdoms_2_locations = lost_kingdoms_2_chests | lost_kingdoms_2_red_fairies | lost_kingdoms_2_key_locations | lost_kingdoms_2_combos | lost_kingdoms_2_bonus_draws | lost_kingdoms_2_shop_purchases
lost_kingdoms_2_locations["Magic Boosters Activation"] = magic_boosters_location