from typing import NamedTuple, Optional, List
from BaseClasses import Location, Region

class LK2LocationData(NamedTuple):
    id: int = 0

class LK2Location(Location):
    game = "Lost Kingdoms II"

    def __init__(self, player: int, name: str, parent: Region, data: LK2LocationData):
        if data is not None:
            super().__init__(player, name, data.id, parent)
        else:
            super().__init__(player, name, None, parent)

        self.region = parent.name
        self.data = data

lost_kingdoms_2_chests = {
    "NR - basement chest 1": {'level': "Nobleman's Residence", 'cardName': 'Dark Raven', 'isoAddress': '6D3FDB9', 'missable': 0, 'RAMAddress': '8025dc12', 'type': 'Chest', 'bitOffset': 1},
    "NR - basement chest 2": {'level': "Nobleman's Residence", 'cardName': 'Scythe Beast', 'isoAddress': '6D3FE79', 'missable': 0, 'RAMAddress': '8025dc12', 'type': 'Chest', 'bitOffset': 2},
    "BHR - chest near horses": {'level': 'Bhashea High Road', 'cardName': 'Porcupig', 'isoAddress': '729BDF9', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Chest', 'bitOffset': 11},
    "BHR - card throw challenge": {'level': 'Bhashea High Road', 'cardName': 'Elephant', 'isoAddress': '72A0B9F', 'missable': 1, 'RAMAddress': '8025dc52', 'type': 'Chest', 'bitOffset': 1},
    "BHR - chest near overlook": {'level': 'Bhashea High Road', 'cardName': 'Man Trap', 'isoAddress': '7299BD9', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Chest', 'bitOffset': 10},
    "BHR - chest near deck point": {'level': 'Bhashea High Road', 'cardName': 'Red Lizard', 'isoAddress': '729AD19', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Chest', 'bitOffset': 9},
    "BHR - jump/flight chest": {'level': 'Bhashea High Road', 'cardName': 'Golden Porcupig', 'isoAddress': '729C3F9', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Chest', 'bitOffset': 12},
    "BHR - flight chest": {'level': 'Bhashea High Road', 'cardName': 'Water Moray', 'isoAddress': '729B919', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Chest', 'bitOffset': 13},
    "Kadishu - chest outside town wall": {'level': 'Kadishu', 'cardName': 'Rock Hagan', 'isoAddress': '778E1D9', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Chest', 'bitOffset': 1},
    "Kadishu - chest up small steps": {'level': 'Kadishu', 'cardName': 'Demon Hound', 'isoAddress': '778DA59', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Chest', 'bitOffset': 4},
    "Kadishu - alleyway chest": {'level': 'Kadishu', 'cardName': 'Dragonoid', 'isoAddress': '778E119', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Chest', 'bitOffset': 5},
    "Kadishu - chest 4": {'level': 'Kadishu', 'cardName': 'Flayer Spawn', 'isoAddress': '778DB19', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Chest', 'bitOffset': 3},
    "Kadishu - chest by dog": {'level': 'Kadishu', 'cardName': 'Demon Hound', 'isoAddress': '778DBD9', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Chest', 'bitOffset': 2},
    "Kadishu - chest near monument": {'level': 'Kadishu', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Stones', 'bitOffset': 11},
    "Kadishu - garbage collection 1": {'level': 'Kadishu', 'cardName': 'Leprechaun', 'isoAddress': '7793797', 'missable': 0, 'RAMAddress': '8025dc90', 'type': 'Chest', 'bitOffset': 9},
    "Kadishu - garbage collection 2": {'level': 'Kadishu', 'cardName': 'Super Scrubber', 'isoAddress': '7793A5F', 'missable': 0, 'RAMAddress': '8025dc90', 'type': 'Chest', 'bitOffset': 10},
    "Kadishu - garbage collection 3": {'level': 'Kadishu', 'cardName': 'Larval Fly', 'isoAddress': '77938FB', 'missable': 0, 'RAMAddress': '8025dc90', 'type': 'Chest', 'bitOffset': 11},
    "BC - central room chest 1": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Stones', 'bitOffset': 5},
    "BC - west room chest": {'level': 'Bhashea Castle', 'cardName': 'Mole Monster', 'isoAddress': 'C4F2F19', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Chest', 'bitOffset': 7},
    "BC - throne chest": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Stones', 'bitOffset': 4},
    "BC - east jump chest": {'level': 'Bhashea Castle', 'cardName': 'Lamassu', 'isoAddress': 'C4F2A99', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Chest', 'bitOffset': 1},
    "BC - east stairway chest": {'level': 'Bhashea Castle', 'cardName': 'Gorgon', 'isoAddress': 'C4F2D99', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Chest', 'bitOffset': 6},
    "BC - break through wall chest": {'level': 'Bhashea Castle', 'cardName': 'Daidarapochi', 'isoAddress': 'C4F2B59', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Chest', 'bitOffset': 2},
    "BC - west stairway chest": {'level': 'Bhashea Castle', 'cardName': 'Death', 'isoAddress': 'C4F2C19', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Chest', 'bitOffset': 3},
    "GD - chest by backpack": {'level': 'Gromtull Desert', 'cardName': 'Venus Spider', 'isoAddress': 'C983379', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 7},
    "GD - cave chest 1": {'level': 'Gromtull Desert', 'cardName': 'Mummy', 'isoAddress': 'C982FB9', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 2},
    "GD - cave chest 2": {'level': 'Gromtull Desert', 'cardName': 'Pixie', 'isoAddress': 'C983079', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 3},
    "GD - cave chest 3": {'level': 'Gromtull Desert', 'cardName': 'Mummy', 'isoAddress': 'C982EF9', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 1},
    "GD - chest by oil": {'level': 'Gromtull Desert', 'cardName': 'Evil Eye', 'isoAddress': 'C9832B9', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 6},
    "GD - jarvi cave chest 1": {'level': 'Gromtull Desert', 'cardName': 'Running Bird', 'isoAddress': 'C983139', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 4},
    "GD - jarvi cave chest 2": {'level': 'Gromtull Desert', 'cardName': 'Sand Beetle', 'isoAddress': 'C9831F9', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 5},
    "GD - flight chest": {'level': 'Gromtull Desert', 'cardName': 'Bum Hagan', 'isoAddress': 'C983439', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Chest', 'bitOffset': 8},
    "KF - chest 1": {'level': 'Kendarie Fortress', 'cardName': 'Mandragora', 'isoAddress': '7C12519', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Chest', 'bitOffset': 1},
    "KF - chest 2": {'level': 'Kendarie Fortress', 'cardName': 'Aggressor GL2', 'isoAddress': '7C154B9', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Chest', 'bitOffset': 3},
    "KF - chest behind green door": {'level': 'Kendarie Fortress', 'cardName': 'Death', 'isoAddress': '7C153F9', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Chest', 'bitOffset': 2},
    "KF - chest 4": {'level': 'Kendarie Fortress', 'cardName': 'Venom Lizard', 'isoAddress': '7C156F9', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Chest', 'bitOffset': 5},
    "KF - chest 5": {'level': 'Kendarie Fortress', 'cardName': 'MechaPult', 'isoAddress': '7C15579', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Chest', 'bitOffset': 4},
    "KF - flight chest": {'level': 'Kendarie Fortress', 'cardName': 'UberBomberBot', 'isoAddress': '7C14979', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Chest', 'bitOffset': 6},
    "RC-UC - chest 1": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Dark Raven', 'isoAddress': '8025dd12', 'missable': 0, 'RAMAddress': '', 'type': 'Chest', 'bitOffset': 13},
    "RC-UC - chest 2": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Land Shark', 'isoAddress': '8025dd12', 'missable': 0, 'RAMAddress': '', 'type': 'Chest', 'bitOffset': 5},
    "RC-UC - talk to Sol": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Stone Golem', 'isoAddress': '7FC9CD7', 'missable': 1, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 0},
    "RC-UC - lower chest 1": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Blood Bush', 'isoAddress': '7FC8639', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 7},
    "RC-UC - lower chest 2": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Undine', 'isoAddress': '7FC83F9', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 3},
    "RC-UC - chest behind ice 1": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Gorgon', 'isoAddress': '7FC86F9', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 6},
    "RC-UC - chest behind ice 2": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Land Shark', 'isoAddress': '7FC84B9', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 4},
    "RC-UC - dragon chest 1": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Baba Yaga', 'isoAddress': '7FC8339', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 1},
    "RC-UC - dragon chest 2": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': 'Witchlette', 'isoAddress': '7FC8279', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Chest', 'bitOffset': 2},
    "RC-LC - chest 1": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Flayer Spawn', 'isoAddress': '843A839', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 1},
    "RC-LC - chest 2": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Basilisk', 'isoAddress': '843B079', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 7},
    "RC-LC - low water chest": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Maelstrom', 'isoAddress': '843A9B9', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 3},
    "RC-LC - high water chest 1": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Yowie', 'isoAddress': '843A8F9', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 2},
    "RC-LC - high water chest flight": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Maelstrom', 'isoAddress': '843AB39', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 4},
    "RC-LC - chest 6": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Flayer Spawn', 'isoAddress': '843ABF9', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 6},
    "RC-LC - chest 7": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': 'Flayer Spawn', 'isoAddress': '843ACB9', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Chest', 'bitOffset': 5},
    "RF - chest 1": {'level': 'Ruldo Forest', 'cardName': 'Mandragora', 'isoAddress': '885D979', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Chest', 'bitOffset': 1},
    "RF - chest 2": {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '885D979', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Stones', 'bitOffset': 2},
    "RF - chest 3": {'level': 'Ruldo Forest', 'cardName': 'Dryad', 'isoAddress': '885DD39', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Chest', 'bitOffset': 3},
    "RF - jump chest": {'level': 'Ruldo Forest', 'cardName': 'Elf', 'isoAddress': '885DDF9', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Chest', 'bitOffset': 4},
    "RF - flight/jump chest": {'level': 'Ruldo Forest', 'cardName': 'Night Mare', 'isoAddress': '885DEB9', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Chest', 'bitOffset': 5},
    "RF - cockatrice chest 1": {'level': 'Ruldo Forest', 'cardName': 'Demon Hound', 'isoAddress': '885E039', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Chest', 'bitOffset': 7},
    "RF - cockatrice chest 2": {'level': 'Ruldo Forest', 'cardName': 'Raflesia', 'isoAddress': '885DF79', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Chest', 'bitOffset': 6},
    "SBA1 - defeat Lich": {'level': 'Sacred Battle Arena 1', 'cardName': 'Lich', 'isoAddress': 'CDB809B', 'missable': 1, 'RAMAddress': '8025e190', 'type': 'Chest', 'bitOffset': 3},
    "SBA1 - defeat Nueh": {'level': 'Sacred Battle Arena 1', 'cardName': 'Nueh', 'isoAddress': 'CDB78E3', 'missable': 1, 'RAMAddress': '8025e190', 'type': 'Chest', 'bitOffset': 1},
    "SBA1 - defeat Gemini": {'level': 'Sacred Battle Arena 1', 'cardName': 'Gemini', 'isoAddress': 'CDB7CBF', 'missable': 1, 'RAMAddress': '8025e190', 'type': 'Chest', 'bitOffset': 2},
    "SBA1 - defeat Kraken": {'level': 'Sacred Battle Arena 1', 'cardName': 'Kraken', 'isoAddress': 'CDB8477', 'missable': 1, 'RAMAddress': '8025e190', 'type': 'Chest', 'bitOffset': 4},
    "SBA2 - defeat Rabandos": {'level': 'Sacred Battle Arena 2', 'cardName': 'Rabandos', 'isoAddress': 'D293F83', 'missable': 1, 'RAMAddress': '8025e1d0', 'type': 'Chest', 'bitOffset': 3},
    "SBA2 - defeat Helena": {'level': 'Sacred Battle Arena 2', 'cardName': 'Ice Skeleton', 'isoAddress': 'D2943DF', 'missable': 1, 'RAMAddress': '', 'type': 'Chest', 'bitOffset': 4},
    "SBA2 - defeat Astrobot": {'level': 'Sacred Battle Arena 2', 'cardName': 'AstroBot', 'isoAddress': 'D29375B', 'missable': 1, 'RAMAddress': '8025e1d0', 'type': 'Chest', 'bitOffset': 1},
    "SBA2 - defeat Leod": {'level': 'Sacred Battle Arena 2', 'cardName': 'Sacred Umpire', 'isoAddress': 'D293B6F', 'missable': 1, 'RAMAddress': '', 'type': 'Chest', 'bitOffset': 2},
    "SBA2 - defeat Thalnos": {'level': 'Sacred Battle Arena 2', 'cardName': 'Sekmet', 'isoAddress': 'D2947FF', 'missable': 1, 'RAMAddress': '', 'type': 'Chest', 'bitOffset': 5},
    "SBA2 - defeat Katia": {'level': 'Sacred Battle Arena 2', 'cardName': 'Doppelganger', 'isoAddress': 'D294C3F', 'missable': 1, 'RAMAddress': '', 'type': 'Chest', 'bitOffset': 6},
    "FB - chest 1": {'level': 'Fossil Boneyard', 'cardName': 'Hell Hound', 'isoAddress': 'B45E8C9', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 1},
    "FB - chest behind cultist": {'level': 'Fossil Boneyard', 'cardName': 'Gnome', 'isoAddress': 'B45E939', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 8},
    "FB - chest 3": {'level': 'Fossil Boneyard', 'cardName': 'Hell Hound', 'isoAddress': 'B45E9F9', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 3},
    "FB - chest 4": {'level': 'Fossil Boneyard', 'cardName': 'Hell Hound', 'isoAddress': 'B45E7B9', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 6},
    "FB - chest 5": {'level': 'Fossil Boneyard', 'cardName': 'Caterpoker', 'isoAddress': 'B45EAB9', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 4},
    "FB - chest 6": {'level': 'Fossil Boneyard', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Stones', 'bitOffset': 5},
    "FB - chest 7": {'level': 'Fossil Boneyard', 'cardName': 'Dark Raven', 'isoAddress': 'B45EC39', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 7},
    "FB - flight chest 1": {'level': 'Fossil Boneyard', 'cardName': 'Catoblepas', 'isoAddress': 'B45ECF9', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 9},
    "FB - flight chest 2": {'level': 'Fossil Boneyard', 'cardName': 'Amber Dragon', 'isoAddress': 'B45EDB9', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 10},
    "FB - zombie dragon chest": {'level': 'Fossil Boneyard', 'cardName': 'Zombie Dragon', 'isoAddress': 'B45CB99', 'missable': 0, 'RAMAddress': '8025e012', 'type': 'Chest', 'bitOffset': 2},
    "Sarvan - jump chest": {'level': 'Sarvan', 'cardName': 'Marid', 'isoAddress': '8CCC9D9', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 3},
    "Sarvan - chest 1": {'level': 'Sarvan', 'cardName': 'Decoy Pillar', 'isoAddress': '8CCCAF9', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 4},
    "Sarvan - chest 2": {'level': 'Sarvan', 'cardName': 'Jade Giant', 'isoAddress': '8CCCBB9', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 5},
    "Sarvan - chest 3": {'level': 'Sarvan', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Stones', 'bitOffset': 6},
    "Sarvan - caged chest": {'level': 'Sarvan', 'cardName': 'Lucky Lion', 'isoAddress': '8CCC859', 'missable': 1, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 1},
    "Sarvan - chest 4": {'level': 'Sarvan', 'cardName': 'Mandragora', 'isoAddress': '8CCCDF9', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 8},
    "Sarvan - chest 5": {'level': 'Sarvan', 'cardName': 'Gold Butterfly', 'isoAddress': '8CCCD39', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 7},
    "Sarvan - caged chest 2": {'level': 'Sarvan', 'cardName': 'Hobgoblin', 'isoAddress': '8CCC919', 'missable': 1, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 2},
    "Sarvan - puzzle chest": {'level': 'Sarvan', 'cardName': 'Devata', 'isoAddress': '8CCE0B9', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Chest', 'bitOffset': 9},
    "HT - chest 1": {'level': 'Holzogh Town', 'cardName': 'Red Lizard', 'isoAddress': '920A899', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 3},
    "HT - chest 2": {'level': 'Holzogh Town', 'cardName': 'Efreet', 'isoAddress': '920AA19', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 7},
    "HT - chest 3": {'level': 'Holzogh Town', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Stones', 'bitOffset': 4},
    "HT - chest 4": {'level': 'Holzogh Town', 'cardName': 'Coal Treant', 'isoAddress': '920A7D9', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 1},
    "HT - chest 5": {'level': 'Holzogh Town', 'cardName': 'Salamander', 'isoAddress': '920AB99', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 6},
    "HT - chest 6": {'level': 'Holzogh Town', 'cardName': 'Popgun Charlie', 'isoAddress': '920AAD9', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 5},
    "HT - chest 7": {'level': 'Holzogh Town', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de12', 'type': 'Stones', 'bitOffset': 9},
    "HT - fountain card": {'level': 'Holzogh Town', 'cardName': 'Mind Flayer', 'isoAddress': '9209AB9', 'missable': 1, 'RAMAddress': '8025de12', 'type': 'Chest', 'bitOffset': 2},
    "PoR - chest 1": {'level': 'Plains of Rowahl', 'cardName': 'Devil Plant', 'isoAddress': '96780F9', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 4},
    "PoR - chest 2": {'level': 'Plains of Rowahl', 'cardName': 'Sand Golem', 'isoAddress': '9678219', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 5},
    "PoR - flight chest": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Stones', 'bitOffset': 7},
    "PoR - chest under scrap": {'level': 'Plains of Rowahl', 'cardName': 'Dao', 'isoAddress': '9678CF9', 'missable': 1, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 8},
    "PoR - chest 4": {'level': 'Plains of Rowahl', 'cardName': 'Man Trap', 'isoAddress': '9678519', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 10},
    "PoR - chest 5": {'level': 'Plains of Rowahl', 'cardName': 'Night Mare', 'isoAddress': '9678459', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 9},
    "PoR - chest 6": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Stones', 'bitOffset': 2},
    "PoR - chest 7": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Stones', 'bitOffset': 3},
    "PoR - flight chest 2": {'level': 'Plains of Rowahl', 'cardName': 'King Mandragora', 'isoAddress': '96782D9', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': 6},
    "PoR - GoD card": {'level': 'Plains of Rowahl', 'cardName': 'God of Destruction', 'isoAddress': '967A757', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Chest', 'bitOffset': -1},
    "AC - chest 2": {'level': 'Alanjeh Castle', 'cardName': 'AcidBot', 'isoAddress': '9A83399', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Chest', 'bitOffset': 3},
    "AC - chest 3": {'level': 'Alanjeh Castle', 'cardName': 'Dark Treant', 'isoAddress': '9A832D9', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Chest', 'bitOffset': 2},
    "AC - chest 4": {'level': 'Alanjeh Castle', 'cardName': 'Gizmolizer', 'isoAddress': '9A83699', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Chest', 'bitOffset': 7},
    "AC - chest 5": {'level': 'Alanjeh Castle', 'cardName': 'Fairy', 'isoAddress': '9A83459', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Chest', 'bitOffset': 4},
    "AC - chest 6": {'level': 'Alanjeh Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Stones', 'bitOffset': 5},
    "AC - flight chest": {'level': 'Alanjeh Castle', 'cardName': 'Boom Monkey', 'isoAddress': '9A835D9', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Chest', 'bitOffset': 6},
    "RTL - chest 1": {'level': 'Royal Tower, Lower', 'cardName': 'Carbuncle', 'isoAddress': '9F0DE19', 'missable': 1, 'RAMAddress': '8025ded2', 'type': 'Chest', 'bitOffset': 1},
    "RTL - chest 2": {'level': 'Royal Tower, Lower', 'cardName': 'Sprite', 'isoAddress': '9F0DED9', 'missable': 1, 'RAMAddress': '8025ded2', 'type': 'Chest', 'bitOffset': 2},
    "RTL - chest 3": {'level': 'Royal Tower, Lower', 'cardName': 'Tiger Mage', 'isoAddress': 'B949EB9', 'missable': 1, 'RAMAddress': '8025e052', 'type': 'Chest', 'bitOffset': 1},
    "RTL - flight chest 1": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Stones', 'bitOffset': 3},
    "RTL - flight chest 2": {'level': 'Royal Tower, Lower', 'cardName': 'Puppet Master', 'isoAddress': 'B949F79', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Chest', 'bitOffset': 2},
    "RTL - jump chest 1": {'level': 'Royal Tower, Lower', 'cardName': 'Decoy Pillar', 'isoAddress': 'B94A0F9', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Chest', 'bitOffset': 4},
    "RTL - jump chest 2": {'level': 'Royal Tower, Lower', 'cardName': 'Fire Gargoyle', 'isoAddress': 'B94A1B9', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Chest', 'bitOffset': 5},
    "RTM - chest 1": {'level': 'Royal Tower, Middle', 'cardName': 'Rheebus', 'isoAddress': 'ABD9259', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Chest', 'bitOffset': 3},
    "RTM - chest 2": {'level': 'Royal Tower, Middle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Stones', 'bitOffset': 4},
    "RTM - breakable wall chest 1": {'level': 'Royal Tower, Middle', 'cardName': 'Sphinx', 'isoAddress': 'ABD9139', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Chest', 'bitOffset': 2},
    "RTM - breakable wall chest 2": {'level': 'Royal Tower, Middle', 'cardName': 'Hydra', 'isoAddress': 'ABD9079', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Chest', 'bitOffset': 1},
    "RTM - forcefield chest 1": {'level': 'Royal Tower, Middle', 'cardName': 'Unicorn', 'isoAddress': 'ABD93D9', 'missable': 1, 'RAMAddress': '8025df92', 'type': 'Chest', 'bitOffset': 5},
    "RTM - forcefield chest 2": {'level': 'Royal Tower, Middle', 'cardName': 'Red Dragon', 'isoAddress': 'ABD9499', 'missable': 1, 'RAMAddress': '8025df92', 'type': 'Chest', 'bitOffset': 6},
    "RTU - chest 1": {'level': 'Royal Tower, Upper', 'cardName': 'Wyvern', 'isoAddress': 'B02D5B9', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Chest', 'bitOffset': 1},
    "RTU - chest 2": {'level': 'Royal Tower, Upper', 'cardName': 'Unicorn', 'isoAddress': 'B02D679', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Chest', 'bitOffset': 3},
    "RTU - chest 3": {'level': 'Royal Tower, Upper', 'cardName': 'Spartoi', 'isoAddress': 'B02D739', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Chest', 'bitOffset': 2},
    "KM - black dragon's card": {'level': 'Krasheen Mountains', 'cardName': 'Birdman', 'isoAddress': 'A25D29F', 'missable': 1, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': -1},
    "KM - chest 1": {'level': 'Krasheen Mountains', 'cardName': 'Birdman', 'isoAddress': 'A25AED9', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': 1},
    "KM - chest 2": {'level': 'Krasheen Mountains', 'cardName': 'Charadrius', 'isoAddress': 'A25B059', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': 4},
    "KM - chest 3": {'level': 'Krasheen Mountains', 'cardName': 'Birdman', 'isoAddress': 'A25AE19', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': 2},
    "KM - chest 4": {'level': 'Krasheen Mountains', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Stones', 'bitOffset': 3},
    "KM - chest 7": {'level': 'Krasheen Mountains', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Stones', 'bitOffset': 7},
    "KM - chest 5": {'level': 'Krasheen Mountains', 'cardName': 'Acid Dragon', 'isoAddress': 'A25B1D9', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': 5},
    "KM - chest 6": {'level': 'Krasheen Mountains', 'cardName': 'Earth Moray', 'isoAddress': 'A25B119', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Chest', 'bitOffset': 6},
    "GC - hidden chest 1": {'level': 'Grenfoel Church', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Stones', 'bitOffset': 3},
    "GC - hidden chest 2": {'level': 'Grenfoel Church', 'cardName': 'Vampire', 'isoAddress': 'A72FD39', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Chest', 'bitOffset': 1},
    "GC - hidden chest 3": {'level': 'Grenfoel Church', 'cardName': 'Plague Rat', 'isoAddress': 'A72FDF9', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Chest', 'bitOffset': 2},
    "GC - organ chest 1": {'level': 'Grenfoel Church', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Stones', 'bitOffset': 5},
    "GC - organ chest 2": {'level': 'Grenfoel Church', 'cardName': 'Gravity Pillar', 'isoAddress': 'A72FF79', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Chest', 'bitOffset': 4},
    "ToS - flight chest": {'level': 'Temple of Sharacia', 'cardName': 'Cerberus', 'isoAddress': 'DBBBBD9', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Chest', 'bitOffset': 1},
    "ToS - chest 1": {'level': 'Temple of Sharacia', 'cardName': 'Salamander', 'isoAddress': 'DBBBD59', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Chest', 'bitOffset': 3},
    "ToS - chest 2": {'level': 'Temple of Sharacia', 'cardName': 'Hell Hound', 'isoAddress': 'DBBBC99', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Chest', 'bitOffset': 2},
    "ToS - chest 3": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Stones', 'bitOffset': 4},
    "ToS - chest 4": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Stones', 'bitOffset': 6},
    "ToS - chest 5": {'level': 'Temple of Sharacia', 'cardName': 'Fire Elemental', 'isoAddress': 'DBBC059', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Chest', 'bitOffset': 7},
    "ToS - chest 6": {'level': 'Temple of Sharacia', 'cardName': 'Fire Gargoyle', 'isoAddress': 'DBBBE19', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Chest', 'bitOffset': 5},
    "ToS - help valkyrie": {'level': 'Temple of Sharacia', 'cardName': 'Valkyrie', 'isoAddress': 'DBBE7FD', 'missable': 1, 'RAMAddress': '8025e290', 'type': 'Chest', 'bitOffset': 3},
    "ToS - help ashura": {'level': 'Temple of Sharacia', 'cardName': 'Ashura', 'isoAddress': 'DBBE4A7', 'missable': 1, 'RAMAddress': '8025e290', 'type': 'Chest', 'bitOffset': 1},
    "IU - chest 1": {'level': 'Isamat Urbur', 'cardName': 'Green Dragon', 'isoAddress': 'BFF2A19', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Chest', 'bitOffset': 1},
    "IU - chest 2": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Stones', 'bitOffset': 5},
    "IU - chest 3": {'level': 'Isamat Urbur', 'cardName': 'Succubus', 'isoAddress': 'BFF2B99', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Chest', 'bitOffset': 3},
    "IU - chest 4": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Stones', 'bitOffset': 4},
    "IU - chest 5": {'level': 'Isamat Urbur', 'cardName': 'Incubus', 'isoAddress': 'BFF2AD9', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Chest', 'bitOffset': 2},
    "IU - chest 6": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Stones', 'bitOffset': 6},
    "OG - chest 1": {'level': 'Obenoix Gorge', 'cardName': 'Water Elemental', 'isoAddress': 'D7106D9', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 1},
    "OG - chest 2": {'level': 'Obenoix Gorge', 'cardName': 'Sasquatch', 'isoAddress': 'D710799', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 2},
    "OG - flight chest 1": {'level': 'Obenoix Gorge', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Stones', 'bitOffset': 4},
    "OG - flight chest 2": {'level': 'Obenoix Gorge', 'cardName': 'Crystal Rose', 'isoAddress': 'D710859', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 3},
    "OG - chest 3": {'level': 'Obenoix Gorge', 'cardName': 'Siren', 'isoAddress': 'D710A99', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 6},
    "OG - chest 4": {'level': 'Obenoix Gorge', 'cardName': 'Chameleus', 'isoAddress': 'D7109D9', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 5},
    "OG - chest behind ice": {'level': 'Obenoix Gorge', 'cardName': 'Thanatos', 'isoAddress': 'D710D99', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 13},
    "OG - flight chest 3": {'level': 'Obenoix Gorge', 'cardName': 'Hydra', 'isoAddress': 'D710B59', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Chest', 'bitOffset': 7},
    "FH - collect 1 fairy": {'level': 'Fairy House', 'cardName': 'Tumble Chick', 'isoAddress': '183A31', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 1},
    "FH - collect 10 fairies": {'level': 'Fairy House', 'cardName': 'Carbuncle', 'isoAddress': '183A33', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 10},
    "FH - collect 20 fairies": {'level': 'Fairy House', 'cardName': 'Berserker', 'isoAddress': '183A35', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 20},
    "FH - collect 30 fairies": {'level': 'Fairy House', 'cardName': 'Fire Moray', 'isoAddress': '183A37', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 30},
    "FH - collect 50 fairies": {'level': 'Fairy House', 'cardName': 'Psycho Dice', 'isoAddress': '183A39', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 50},
    "FH - collect 70 fairies": {'level': 'Fairy House', 'cardName': 'Whip Worm', 'isoAddress': '183A3B', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 70},
    "FH - collect 80 fairies": {'level': 'Fairy House', 'cardName': 'Global Bust', 'isoAddress': '183A3D', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 80},
    "FH - collect 90 fairies": {'level': 'Fairy House', 'cardName': 'Crystal Magic', 'isoAddress': '183A3F', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 90},
    "FH - collect 100 fairies": {'level': 'Fairy House', 'cardName': 'Circasaurus', 'isoAddress': '183A41', 'missable': 1, 'RAMAddress': '8025d033', 'type': 'Chest', 'bitOffset': 100}
}

lost_kingdoms_2_red_fairies = {
    "NR - Red Fairy sculpture": {'level': "Nobleman's Residence", 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc12', 'type': 'Red Fairy', 'bitOffset': 7},
    "NR - Red Fairy central": {'level': "Nobleman's Residence", 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc12', 'type': 'Red Fairy', 'bitOffset': 8},
    "NR - Red Fairy office": {'level': "Nobleman's Residence", 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc12', 'type': 'Red Fairy', 'bitOffset': 6},
    "BHR - Red Fairy across bridge": {'level': 'Bhashea High Road', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Red Fairy', 'bitOffset': 8},
    "BHR - Red Fairy across bridge in rubble": {'level': 'Bhashea High Road', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Red Fairy', 'bitOffset': 6},
    "BHR - Red Fairy chaos knight": {'level': 'Bhashea High Road', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc52', 'type': 'Red Fairy', 'bitOffset': 7},
    "Kadishu - Red Fairy by dog": {'level': 'Kadishu', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Red Fairy', 'bitOffset': 8},
    "Kadishu - Red Fairy on bridge": {'level': 'Kadishu', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Red Fairy', 'bitOffset': 10},
    "Kadishu - Red Fairy in well": {'level': 'Kadishu', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Red Fairy', 'bitOffset': 6},
    "Kadishu - Red Fairy by fountain": {'level': 'Kadishu', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Red Fairy', 'bitOffset': 7},
    "Kadishu - Red Fairy in alley": {'level': 'Kadishu', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dc92', 'type': 'Red Fairy', 'bitOffset': 9},
    "BC - Red Fairy near start": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Red Fairy', 'bitOffset': 12},
    "BC - Red Fairy central room": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Red Fairy', 'bitOffset': 11},
    "BC - Red Fairy rubble": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Red Fairy', 'bitOffset': 9},
    "BC - Red Fairy throne": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Red Fairy', 'bitOffset': 13},
    "BC - Red Fairy wall break rubble": {'level': 'Bhashea Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e112', 'type': 'Red Fairy', 'bitOffset': 10},
    "GD - Red Fairy 1": {'level': 'Gromtull Desert', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Red Fairy', 'bitOffset': 10},
    "GD - Red Fairy 2": {'level': 'Gromtull Desert', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Red Fairy', 'bitOffset': 11},
    "GD - Red Fairy jump": {'level': 'Gromtull Desert', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Red Fairy', 'bitOffset': 12},
    "GD - Red Fairy Jarvi 1": {'level': 'Gromtull Desert', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Red Fairy', 'bitOffset': 13},
    "GD - Red Fairy Jarvi 2": {'level': 'Gromtull Desert', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e152', 'type': 'Red Fairy', 'bitOffset': 9},
    "KF - Red Fairy at start": {'level': 'Kendarie Fortress', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Red Fairy', 'bitOffset': 10},
    "KF - Red Fairy fly across": {'level': 'Kendarie Fortress', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Red Fairy', 'bitOffset': 9},
    "KF - Red Fairy past blue gate": {'level': 'Kendarie Fortress', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Red Fairy', 'bitOffset': 7},
    "KF - Red Fairy near Mechapult": {'level': 'Kendarie Fortress', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dcd2', 'type': 'Red Fairy', 'bitOffset': 8},
    "RC-UC - Red Fairy near start": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Red Fairy', 'bitOffset': 12},
    "RC-UC - Red Fairy near sluice gate": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Red Fairy', 'bitOffset': 8},
    "RC-UC - Red Fairy near dragon": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Red Fairy', 'bitOffset': 9},
    "RC-UC - Red Fairy near golem": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Red Fairy', 'bitOffset': 10},
    "RC-UC - Red Fairy near Sol": {'level': 'Runestone Caverns - Upper Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd12', 'type': 'Red Fairy', 'bitOffset': 11},
    "RC-LC - Red Fairy near start": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 8},
    "RC-LC - Red Fairy in rubble": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 10},
    "RC-LC - Red Fairy low water": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 11},
    "RC-LC - Red Fairy on stairs": {'level': 'Runestone Caverns - Lower Chambers', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 9},
    "RF Red Fairy at start": {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Red Fairy', 'bitOffset': 8},
    "RF Red Fairy at start 2": {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Red Fairy', 'bitOffset': 12},
    "RF Red Fairy in tree": {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Red Fairy', 'bitOffset': 11},
    "RF Red Fairy near machine": {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Red Fairy', 'bitOffset': 9},
    "RF Red past Cockatrice": {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd92', 'type': 'Red Fairy', 'bitOffset': 10},
    "SBA1 - Red Fairy 1": {'level': 'Sacred Battle Arena 1', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e192', 'type': 'Red Fairy', 'bitOffset': 2},
    "SBA1 - Red Fairy 2": {'level': 'Sacred Battle Arena 1', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e192', 'type': 'Red Fairy', 'bitOffset': 1},
    "SBA1 - Red Fairy 3": {'level': 'Sacred Battle Arena 1', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e192', 'type': 'Red Fairy', 'bitOffset': 3},
    "SBA2 - Red Fairy hallway": {'level': 'Sacred Battle Arena 2', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e1d2', 'type': 'Red Fairy', 'bitOffset': 2},
    "SBA2 - Red Fairy machines": {'level': 'Sacred Battle Arena 2', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e1d2', 'type': 'Red Fairy', 'bitOffset': 3},
    "SBA2 - Red Fairy Queen Katia": {'level': 'Sacred Battle Arena 2', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e1d2', 'type': 'Red Fairy', 'bitOffset': 1},
    "FB - Red Fairy near start": {'level': 'Fossil Boneyard', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 11},
    "FB - Red Fairy near jump pad": {'level': 'Fossil Boneyard', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 12},
    "FB - Red Fairy jumping": {'level': 'Fossil Boneyard', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dd52', 'type': 'Red Fairy', 'bitOffset': 13},
    "Sarvan - Red Fairy near start": {'level': 'Sarvan', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 10},
    "Sarvan - Red Fairy under bridge": {'level': 'Sarvan', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 12},
    "Sarvan - Red Fairy magic circle": {'level': 'Sarvan', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 11},
    "HT - Red Fairy near start": {'level': 'Holzogh Town', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 11},
    "HT - Red Fairy stairs": {'level': 'Holzogh Town', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 13},
    "HT - Red Fairy rubble": {'level': 'Holzogh Town', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 10},
    "HT - Red Fairy rubble 2": {'level': 'Holzogh Town', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ddd2', 'type': 'Red Fairy', 'bitOffset': 14},
    "PoR - Red Fairy near start": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Red Fairy', 'bitOffset': 11},
    "PoR - Red Fairy in catapult": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Red Fairy', 'bitOffset': 12},
    "PoR - Red Fairy in golem": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Red Fairy', 'bitOffset': 13},
    "PoR - Red Fairy past gate": {'level': 'Plains of Rowahl', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de52', 'type': 'Red Fairy', 'bitOffset': 14},
    "AC - Red Fairy near start": {'level': 'Alanjeh Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Red Fairy', 'bitOffset': 9},
    "AC - Red Fairy jump": {'level': 'Alanjeh Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Red Fairy', 'bitOffset': 8},
    "AC - Red Fairy end": {'level': 'Alanjeh Castle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025de92', 'type': 'Red Fairy', 'bitOffset': 9},
    "RTL - Red Fairy start": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ded2', 'type': 'Red Fairy', 'bitOffset': 3},
    "RTL - Red Fairy up elevator": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025ded2', 'type': 'Red Fairy', 'bitOffset': 4},
    "RTL - Red Fairy over pillar": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Red Fairy', 'bitOffset': 7},
    "RTL - Red Fairy chandelier": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Red Fairy', 'bitOffset': 8},
    "RTL - Red Fairy outside": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Red Fairy', 'bitOffset': 10},
    "RTL - Red Fairy flight": {'level': 'Royal Tower, Lower', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e052', 'type': 'Red Fairy', 'bitOffset': 9},
    "RTM - Red Fairy near start": {'level': 'Royal Tower, Middle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Red Fairy', 'bitOffset': 7},
    "RTM - Red Fairy hallway": {'level': 'Royal Tower, Middle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Red Fairy', 'bitOffset': 9},
    "RTM - Red Fairy breakable wall 1": {'level': 'Royal Tower, Middle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Red Fairy', 'bitOffset': 8},
    "RTM - Red Fairy breakable wall 2": {'level': 'Royal Tower, Middle', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df92', 'type': 'Red Fairy', 'bitOffset': 10},
    "RTU - Red Fairy rubble": {'level': 'Royal Tower, Upper', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Red Fairy', 'bitOffset': 4},
    "RTU - Red Fairy sphinx": {'level': 'Royal Tower, Upper', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Red Fairy', 'bitOffset': 6},
    "RTU - Red Fairy stairs 1": {'level': 'Royal Tower, Upper', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Red Fairy', 'bitOffset': 7},
    "RTU - Red Fairy stairs 2": {'level': 'Royal Tower, Upper', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025dfd2', 'type': 'Red Fairy', 'bitOffset': 5},
    "KM - Red Fairy cave 1": {'level': 'Krasheen Mountains', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Red Fairy', 'bitOffset': 9},
    "KM - Red Fairy bridge": {'level': 'Krasheen Mountains', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Red Fairy', 'bitOffset': 8},
    "KM - Red Fairy broken bridge": {'level': 'Krasheen Mountains', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Red Fairy', 'bitOffset': 10},
    "KM - Red Fairy broken bridge 2": {'level': 'Krasheen Mountains', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df12', 'type': 'Red Fairy', 'bitOffset': 11},
    "GC - Red Fairy near organ": {'level': 'Grenfoel Church', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Red Fairy', 'bitOffset': 6},
    "GC - Red Fairy right side": {'level': 'Grenfoel Church', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Red Fairy', 'bitOffset': 9},
    "GC - Red Fairy hidden 1": {'level': 'Grenfoel Church', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Red Fairy', 'bitOffset': 8},
    "GC - Red Fairy hidden 2": {'level': 'Grenfoel Church', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Red Fairy', 'bitOffset': 10},
    "GC - Red Fairy library": {'level': 'Grenfoel Church', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025df52', 'type': 'Red Fairy', 'bitOffset': 7},
    "ToS - Red Fairy near start": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Red Fairy', 'bitOffset': 8},
    "ToS - Red Fairy near start 2": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Red Fairy', 'bitOffset': 9},
    "ToS - Red Fairy up left stairs": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Red Fairy', 'bitOffset': 13},
    "ToS - Red Fairy up right side": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Red Fairy', 'bitOffset': 10},
    "ToS - Red Fairy rubble": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Red Fairy', 'bitOffset': 12},
    "ToS - Red Fairy Valkyrie": {'level': 'Temple of Sharacia', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e292', 'type': 'Red Fairy', 'bitOffset': 11},
    "IU - Red Fairy near start": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Red Fairy', 'bitOffset': 10},
    "IU - Red Fairy east room": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Red Fairy', 'bitOffset': 8},
    "IU - Red Fairy northeast": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Red Fairy', 'bitOffset': 9},
    "IU - Red Fairy southwest": {'level': 'Isamat Urbur', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e0d2', 'type': 'Red Fairy', 'bitOffset': 7},
    "OG - Red Fairy near start": {'level': 'Obenoix Gorge', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Red Fairy', 'bitOffset': 8},
    "OG - Red Fairy in tree": {'level': 'Obenoix Gorge', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Red Fairy', 'bitOffset': 10},
    "OG - Red Fairy near flight": {'level': 'Obenoix Gorge', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Red Fairy', 'bitOffset': 9},
    "OG - Red Fairy in tree 2": {'level': 'Obenoix Gorge', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Red Fairy', 'bitOffset': 11},
    "OG - Red Fairy near ship": {'level': 'Obenoix Gorge', 'cardName': '', 'isoAddress': '', 'missable': 0, 'RAMAddress': '8025e212', 'type': 'Red Fairy', 'bitOffset': 12}
}
lost_kingdoms_2_key_locations = {
    "Red Key": {'level': 'Kendarie Fortress', 'type': 'Key Item','bitOffset': 1},
    "Blue Key": {'level': 'Kendarie Fortress', 'type': 'Key Item','bitOffset': 2},
    "Green Key": {'level': 'Kendarie Fortress', 'type': 'Key Item', 'bitOffset': 3},
    "Fossil Head": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 4},
    "Fossil Torso": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 5},
    "Fossil Tail": {'level': 'Fossil Boneyard', 'type': 'Key Item', 'bitOffset': 6},
    "Fossil Rt Wing": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 7},
    "Fossil Lt Wing": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 8},
    "Fossil Rt Arm": {'level': 'Fossil Boneyard', 'type': 'Key Item', 'bitOffset': 9},
    "Fossil Lt Arm": {'level': 'Fossil Boneyard', 'type': 'Key Item', 'bitOffset': 10},
    "Fossil Rt Leg": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 11},
    "Fossil Lt Leg": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 12},
    "Bottle": {'level': 'Gromtull Desert', 'type': 'Key Item', 'bitOffset': 13},
    "Black Liquid": {'level': 'Gromtull Desert', 'type': 'Key Item','bitOffset': 14},
    "Mysterious Key": {'level': 'Sacred Battle Arena 1', 'type': 'Key Item','bitOffset': 15},
    "Blade of Skill": {'level': 'Bhashea Castle', 'type': 'Key Item', 'bitOffset': 16},
    "Blade of Power": {'level': 'Bhashea Castle', 'type': 'Key Item','bitOffset': 17},
    "Blade of Wisdom": {'level': 'Bhashea Castle', 'type': 'Key Item','bitOffset': 18},
    "Blade of Time": {'level': 'Bhashea Castle', 'type': 'Key Item', 'bitOffset': 19},
    "Jewel of Alanjeh": {'level': 'Grenfoel Church', 'type': 'Key Item', 'bitOffset': 20},
    "Eno Runestone": {'level': 'Ruldo Forest', 'type': 'Key Item','bitOffset': 21},
    "Oht Runestone": {'level': 'Fossil Boneyard', 'type': 'Key Item','bitOffset': 22},
    "Elise Runestone": {'level': 'Plains of Rowahl', 'type': 'Key Item', 'bitOffset': 23},
    "Olf Runestone": {'level': 'Sacred Battle Arena 1', 'type': 'Key Item','bitOffset': 24},
    "Ebin Runestone": {'level': 'Gromtull Desert', 'type': 'Key Item','bitOffset': 25},
    "Keil Runestone": {'level': "Nobleman's Residence", 'type': 'Key Item', 'bitOffset': 26},
    "Nebeth Runestone": {'level': 'Isamat Urbur', 'type': 'Key Item','bitOffset': 27},
    "Stone of Sealing": {'level': 'Isamat Urbur', 'type': 'Key Item','bitOffset': 28},
    "Castle Gate Key": {'level': 'Plains of Rowahl', 'type': 'Key Item', 'bitOffset': 29},
    "Key to Fountain": {'level': 'Holzogh Town', 'type': 'Key Item', 'bitOffset': 30}
}

magic_boosters_location = {'level': 'Ruldo Forest', 'cardName': '', 'isoAddress': '', 'missable': 0,
                                      'RAMAddress': '80003eec', 'type': 'Magic Booster', 'bitOffset': 3}

lost_kingdoms_2_regions = {
    "Nobleman's Residence": { "RAMAddress": "8025dc0e"},
    "Bhashea High Road": { "RAMAddress": "8025dc4e"},
    "Kadishu": { "RAMAddress": "8025dc8e" },
    "Kadishu Shop": { "RAMAddress": "8025e60e" },
    "Fairy House": { "RAMAddress": "8025e5ce" },
    "Bhashea Castle": { "RAMAddress": "8025e10e"},
    "Gromtull Desert": { "RAMAddress": "8025e14e"},
    "Kendarie Fortress": { "RAMAddress": "8025dcce"},
    "Runestone Caverns - Upper Chambers": { "RAMAddress": "8025dd0e"},
    "Runestone Caverns - Lower Chambers": { "RAMAddress": "8025dd4e"},
    "Ruldo Forest": { "RAMAddress": "8025dd8e"},
    "Sacred Battle Arena 1": { "RAMAddress": "8025e18e"},
    "Sacred Battle Arena 2": { "RAMAddress": "8025e1ce"},
    "Fossil Boneyard": { "RAMAddress": "8025e00e"},
    "Sarvan": { "RAMAddress": "8025ddce"},
    "Holzogh Town": { "RAMAddress": "8025de0e"},
    "Plains of Rowahl": { "RAMAddress": "8025de4e"},
    "Alanjeh Castle": { "RAMAddress": "8025de8e"},
    "Royal Tower, Lower": { "RAMAddress": "8025dece"},
    "Royal Tower, Middle": { "RAMAddress": "8025df8e"},
    "Royal Tower, Upper": { "RAMAddress": "8025dfce"},
    "Krasheen Mountains": { "RAMAddress": "8025df0e"},
    "Grenfoel Church": { "RAMAddress": "8025df4e"},
    "Temple of Sharacia": { "RAMAddress": "8025e28e"},
    "Grenfoel Church Shop": { "RAMAddress": "8025e64e"},
    "Isamat Urbur": { "RAMAddress": "8025e0ce"},
    "Obenoix Gorge": { "RAMAddress": "8025e20e"},
    "Proving Grounds": { "RAMAddress": "8025e84e"}
}

lost_kingdoms_2_combos = {
    "Triple Hagan" : { "BitOffset" : 18, "type": "Combo", "level":"Menu"},
    "Ultimate Pasta" : { "BitOffset" : 19, "type": "Combo", "level":"Menu"},
    "Rotary Death" : { "BitOffset" : 20, "type": "Combo", "level":"Menu"},
    "Lizard War" : { "BitOffset" : 21, "type": "Combo", "level":"Menu"},
    "Rocky Forecast" : { "BitOffset" : 22, "type": "Combo", "level":"Menu"},
    "Sir Spear-A-Lot" : { "BitOffset" : 23, "type": "Combo", "level":"Menu"},
    "Temper Tantrum" : { "BitOffset" : 24, "type": "Combo", "level":"Menu"},
    "Goblin Guts" : { "BitOffset" : 25, "type": "Combo", "level":"Menu"},
    "Lethal Orbit" : { "BitOffset" : 26, "type": "Combo", "level":"Menu"},
    "Crystal Rage" : { "BitOffset" : 27, "type": "Combo", "level":"Menu"},
    "Mandragora Mixer" : { "BitOffset" : 28, "type": "Combo", "level":"Menu"},
    "Rust and Roll!" : { "BitOffset" : 29, "type": "Combo", "level":"Menu"},
    "EconoMagic" : { "BitOffset" : 30, "type": "Combo", "level":"Menu"},
    "Just Visiting" : { "BitOffset" : 31, "type": "Combo", "level":"Menu"},
    "Djinn and Bear It" : { "BitOffset" : 32, "type": "Combo", "level":"Menu"},
    "Triple Kamikaze" : { "BitOffset" : 33, "type": "Combo", "level":"Menu"},
    "One Way Ticket" : { "BitOffset" : 34, "type": "Combo", "level":"Menu"},
    "The Masters Four" : { "BitOffset" : 35, "type": "Combo", "level":"Menu"},
    "The Big Save" : { "BitOffset" : 36, "type": "Combo", "level":"Menu"},
    "Brutal Nightmare" : { "BitOffset" : 37, "type": "Combo", "level":"Menu"},
    "Phantom BullDozer" : { "BitOffset" : 38, "type": "Combo", "level":"Menu"},
    "Living Large" : { "BitOffset" : 31, "type": "Combo", "level":"Menu"},
    "Elemental Victory" : { "BitOffset" : 32, "type": "Combo", "level":"Menu"},
    "Skullapalooza" : { "BitOffset" : 33, "type": "Combo", "level":"Menu"},
    "Stone Cold Sniper" : { "BitOffset" : 34, "type": "Combo", "level":"Menu"},
    "Mega Tremor" : { "BitOffset" : 35, "type": "Combo", "level":"Menu"},
    "Time Out!" : { "BitOffset" : 37, "type": "Combo", "level":"Menu"},
    "Hell Hole" : { "BitOffset" : 38, "type": "Combo", "level":"Menu"},
    "Spiritual Force" : { "BitOffset" : 39, "type": "Combo", "level":"Menu"},
    "Air Raid" : { "BitOffset" : 0, "type": "Combo", "level":"Menu"},
    "Tech Support!" : { "BitOffset" : 2, "type": "Combo", "level":"Menu"},
    "Song of Hades" : { "BitOffset" : 3, "type": "Combo", "level":"Menu"},
    "Hearing Aid" : { "BitOffset" : 4, "type": "Combo", "level":"Menu"},
    "Uber Vampire Root" : { "BitOffset" : 6, "type": "Combo", "level":"Menu"},
    "Mo Better Moray" : { "BitOffset" : 7, "type": "Combo", "level":"Menu"},
    "Prayer of the Wise" : { "BitOffset" : 10, "type": "Combo", "level":"Menu"},
    "Hawging the Action" : { "BitOffset" : 17, "type": "Combo", "level":"Menu"},
    "Stone All Around" : { "BitOffset" : 19, "type": "Combo", "level":"Menu"},
    "Tender Mercy" : { "BitOffset" : 20, "type": "Combo", "level":"Menu"},
    "Green Guardian" : { "BitOffset" : 26, "type": "Combo", "level":"Menu"},
}

lost_kingdoms_2_locations = lost_kingdoms_2_chests | lost_kingdoms_2_red_fairies | lost_kingdoms_2_key_locations | lost_kingdoms_2_combos
lost_kingdoms_2_locations["Magic Boosters Activation"] = magic_boosters_location